### ISSUE TITLE
No Admin Translations

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#101]
After installtion data hub and activating the package, then clearing the cache and reopening the backend interface, DataHub doesn't have user friendly labels:

![000189](https://user-images.githubusercontent.com/8310677/64189540-c483a200-ce74-11e9-9fc8-228a4f9df9c4.png)
![000192](https://user-images.githubusercontent.com/8310677/64190182-12e57080-ce76-11e9-972a-eeb63ac421b7.png)

The installation guide doesn't mention any additional tasks, so I assume this is a bug.

**Comment by julmot** [comment]
For those of you having the same issue: Manually importing this converted translation file at least provides the missing translations in EN:
[convertcsv.zip](https://github.com/pimcore/data-hub/files/3570436/convertcsv.zip)

**Comment by weisswurstkanone** [comment]
This is neither the right place nor the right solution. Please follow the official pimcore installation guide.

**Comment by julmot** [comment]
@weisswurstkanone Of course it's not, this was a workaround for the meantime.

Would you mind to point out that `official pimcore installation guide` where translations of packages are covered?
Places where I searched unsuccessful:

* https://pimcore.com/docs/5.x/Development_Documentation/Getting_Started/Installation.html
* https://pimcore.com/docs/5.x/Development_Documentation/Extending_Pimcore/Add_Your_Own_Dependencies_and_Packages.html
* https://pimcore.com/docs/5.x/Development_Documentation/Multi_Language_i18n/Admin_Translations.html
* https://pimcore.com/docs/5.x/Development_Documentation/Multi_Language_i18n/Shared_Translations.html
* https://pimcore.com/docs/5.x/Development_Documentation/Installation_and_Upgrade/System_Setup_and_Hosting/Additional_Tools_Installation.html
