### ISSUE TITLE
Add button click does nothing – Only arrow works

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#102]
Clicking on the following button (plugin_pimcore_datahub_configpanel_add) does nothing – only clicking explicitly on the arrow opens the dropdown:

![000191](https://user-images.githubusercontent.com/8310677/64189718-25ab7580-ce75-11e9-8f3a-d8f14b3ead8d.png)

**Comment by weisswurstkanone** [comment]
Works as designed as additional channels are in the pipeline. For now we could make it as default.
PRs are welcome ;-)

**Comment by julmot** [comment]
I would suggest to open the same dropdown like the arrow, what do you think?

**Comment by weisswurstkanone** [comment]
that's a standard split button - but as you can see there is only one option right now.

**Comment by nerdsklickpark** [comment]
I think he refers to that if you click on the label (1), no event handler is implemented, nothing happens.
An event handler is implemented for the arrow (2), it opens the dropdown.

Maybe clicking on the label (1) could also open the dropdown.

If the label should not open the dropdown, what could be an alternative function?

![Screenshot 2019-09-04 at 9 10 20 AM](https://user-images.githubusercontent.com/46604496/64233527-b8d7c000-cef4-11e9-9b7e-061b36d99774.jpg)

**Comment by julmot** [comment]
Thanks @nerdsklickpark for the explanation, indeed this is what I was talking about.
