### ISSUE TITLE
Error: Mutation datatype 'numeric' not supported yet (?)

### ISSUE THREAD

**Issue by ceefour** [pimcore/data-hub#107]
https://github.com/pimcore/data-hub/blob/master/doc/graphl/Mutations.md says that most of the basic data types are already supported.

But I've just tried this using datahub v.master at Sep 6, 2019 (running on Pimcore 6.1.2) and throws error:

![image](https://user-images.githubusercontent.com/24123/64401568-a8ae1500-d09b-11e9-9612-05950de36cfb.png)

All I can do is add the "system fields". Any user-created field is not working, even string data type.

**Comment by weisswurstkanone** [comment]
regression of https://github.com/pimcore/data-hub/commit/2f8558017c6e02b510d701ddaf05a213669404ef
