### ISSUE TITLE
Assets fullpath(thumbnail:) not working on relations

### ISSUE THREAD

**Issue by SimoneCarnio** [pimcore/data-hub#121]
I'm trying to get thumbnail from asset linked by relation to an object, but I cannot get it to work. I tried to check over the code but without results.

To reproduce, this is a simple class:
![image](https://user-images.githubusercontent.com/8537252/67484853-330d0100-f669-11e9-9bfd-5e2366553024.png)

This is an object created with that class:
![image](https://user-images.githubusercontent.com/8537252/67484905-4c15b200-f669-11e9-89b5-01b64db85faf.png)

This is the schema in datahub config:
![image](https://user-images.githubusercontent.com/8537252/67485011-82ebc800-f669-11e9-8e48-f759bd48f820.png)

This is a sample GraphQl Query tho show the error:
![image](https://user-images.githubusercontent.com/8537252/67485337-145b3a00-f66a-11e9-8217-d9f60ff95608.png)

The field "thumb" in the asset linked by the relation is always the original asset path, never the thumbnail path. (As you can see in the direct getAsset query).

**Comment by NiklasBr** [comment]
Have you tried using the Thumbnail *Transformer* (bottom in the left column) when specifying the Query Schema Fields?

**Comment by SimoneCarnio** [comment]
With the Thumbnail transformer seems to work, but I need to change the thumbnail configuration from the query. 
Moreover, I cant use (I think) the Thumbnail Transformer if I insert a relation inside a FieldCollection, as like this: 

Object:
![image](https://user-images.githubusercontent.com/8537252/67486923-3c986800-f66d-11e9-9bae-507040d51501.png)

FieldCollection (_ListaDocumenti_):
![image](https://user-images.githubusercontent.com/8537252/67486968-55088280-f66d-11e9-8fdd-635bf7474e1d.png)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/67488679-820a6480-f670-11e9-9c1b-d64e2c95c865.png)

**Comment by SimoneCarnio** [comment]
Thank you @weisswurstkanone for your prompt reply/fix.
I think you should add also something like this to get the document preview

```php
if ($image instanceof Asset\Image || $image instanceof Asset\Video) {
    if (isset($args["thumbnail"])) {
        return $image->getThumbnail($args["thumbnail"], false);
    } else {
        return $image->getFullPath();
    }
}
```

I think it should also be fixed this on data(thumbnail)

What do you thin?

**Comment by SimoneCarnio** [comment]
Thank you @weisswurstkanone for your prompt reply/fix.
I think you should add also something like this to get the document preview

```php
if ($image instanceof Asset\Document)
{
            if (isset($args["thumbnail"])) {
        return $image->getImageThumbnail($args["thumbnail"]);
    } else {
        return $image->getFullPath();
    }
}

```

I think it should also be fixed this on data(thumbnail)

What do you think?

**Comment by weisswurstkanone** [comment]
can you create a PR ? :-)
