### ISSUE TITLE
Mutation not working as soon as defaultLanguage used

### ISSUE THREAD

**Issue by Ben305** [pimcore/data-hub#123]
I have a mutation which can be executed successfully as long as I don't specify the defaultLanguage.

When the defaultLanguage is specified, an error is thrown here:
https://github.com/pimcore/data-hub/blob/master/src/GraphQL/Mutation/MutationType.php#L389
because `$localeService` is null.

Any help would be kindly appreciated!

**Comment by weisswurstkanone** [comment]
Unable to reproduce.

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/67548638-97c86a00-f702-11e9-9c26-8e3decc834f4.png)

**Comment by Ben305** [comment]
Oh, defaultLanguage has to be part of the input? Will try that and report back!

**Comment by weisswurstkanone** [comment]
it is not part of the input, the screenshot is not optimal :-)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/67548809-1b825680-f703-11e9-9718-0bb722541489.png)

**Comment by Ben305** [comment]
Here are some screenshots from my configuration:

**Class definition**
<img width="311" alt="Class" src="https://user-images.githubusercontent.com/2217367/67551414-17593780-f709-11e9-9e9d-6a001d419828.png">

**Data-Hub configuration**
<img width="948" alt="DataHub Config" src="https://user-images.githubusercontent.com/2217367/67551478-512a3e00-f709-11e9-8128-22198b6ea6c1.png">

**Mutation without defaultLanguage**
<img width="700" alt="Mutation without DefaultLanguage" src="https://user-images.githubusercontent.com/2217367/67551499-5d160000-f709-11e9-9edc-c0fa9491c822.png">

**Mutation with defaultLanguage set**
<img width="701" alt="Mutation with DefaultLanguage" src="https://user-images.githubusercontent.com/2217367/67551464-4a033000-f709-11e9-8d0c-57386400db95.png">

**Comment by weisswurstkanone** [comment]
please try to debug it. I don't see how localeService could be null.

**Comment by Ben305** [comment]
Okay, will do that. Anything special I should have a look at?

**Comment by Ben305** [comment]
@weisswurstkanone Found it, the local variables where not assigned correctly when the entity config only contained update mutations.

**Comment by weisswurstkanone** [comment]
Excellent! As an alternative we could use $this->localService inside getUpdateObjectResolver
