### ISSUE TITLE
Thumbnail Transformer is not aware of media queries

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#13]
## Steps to reproduce

1. Create a new *Image Thumbnail*
2. Define at least one breakpoint.
3. Run a client query against the thumbnail field.

## Expected result

To either be able to get an entire `<img srcset...>` tag or an array with data objects representing the different image objects (which may include the different paths).

## Actual result

I get the path to one of the thumbnails only.

**Comment by weisswurstkanone** [comment]
@NiklasBr can this be closed ?

**Comment by NiklasBr** [comment]
I tried a query like this now:

```gql
  getProduct(id: 2383) {
    gallery {
      image {
        srcset(thumbnail: "productImage") {
          descriptor
          url
        }
      }
    }
  }
```

...and got the expected result.

**Comment by weisswurstkanone** [comment]
thx for testing!
