### ISSUE TITLE
Images in fieldcollection

### ISSUE THREAD

**Issue by DzemalBecirevic** [pimcore/data-hub#133]
I have a class with a fieldcollection that contains images, when trying to read the data in Graphql Im experiencing problems.

According to the documentation this should work without any problems so what am I doing wrong?

Query:
`Images {
    ... on fieldcollection_image {
        __typename
            ... on Image {
                fullpath
            }
       }
}`

Error:
`{
  "errors": [
    {
      "message": "Unknown type \"Image\".",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 14,
          "column": 20
        }
      ]
    }
  ]
}`

And in the Pimcore log:
` pimcore.ERROR: Class: Pimcore\Model\DataObject\Simple => call to undefined method getImage [] []`

Pimcore 6.1.2
DataHub: dev-master

**Comment by weisswurstkanone** [comment]
can you paste a screenshot of your field collection definition?

**Comment by DzemalBecirevic** [comment]
In Simple class:
![image](https://user-images.githubusercontent.com/1179974/68763135-04ef6100-0618-11ea-9a24-6173d5a05b7b.png)

Field collection (Image):
![image](https://user-images.githubusercontent.com/1179974/68763192-22bcc600-0618-11ea-8901-6bf61669d5df.png)

Thanks in advance.

**Comment by weisswurstkanone** [comment]
did you check your query with graphql explorer. my gut feeling is that the query is not right.

**Comment by weisswurstkanone** [comment]
also make sure that you are on dev-master. there are a couple modifications going on right now.

**Comment by DzemalBecirevic** [comment]
I have tried both

... on Image { fullpath }

and even

... on asset { fullpath }

but without any results.

I have debugged and seen that the AbstractFieldHelper.php returns the correct data but for some reason later on "getImage" is called on "Simple".

**Comment by weisswurstkanone** [comment]
my "... on" ? the image is always an asset (not a union)

Try something like

{
  getTest(id: 1130) {
    mycol {
      __typename
      ... on fieldcollection_testcoll {
        myimage {
          fullpath
        }
        fcinput
      }
    }
  }
}


and make sure you are on the latest version.

**Comment by DzemalBecirevic** [comment]
I've checked up the lastest version and it is now working with the following query:

`query {
  getSimple(id: 4) {
      Images {
        ... on fieldcollection_image {
          Image {
            fullpath
          }
        }
      }
    }
}`

Thanks for the help!

**Comment by weisswurstkanone** [comment]
welcome
