### ISSUE TITLE
Install manually

### ISSUE THREAD

**Issue by devondahon** [pimcore/data-hub#134]
I have a server based in China, the install command `composer require pimcore/data-hub:dev-master` seems to be blocked by the GFW, how can to install `data-hub` manually ?

**Comment by NiklasBr** [comment]
If you can fork the code you could perhaps set up a custom local repository, I believe [the Composer docs](https://getcomposer.org/doc/05-repositories.md) can help you .

**Comment by brusch** [comment]
Please download the code and use a local "path" composer repository.
