### ISSUE TITLE
Nothing in the menu after installation

### ISSUE THREAD

**Issue by devondahon** [pimcore/data-hub#135]
I have installed **data-hub** with:
```
composer require pimcore/data-hub:dev-master
```

It seems properly installed:
```
/var/www/html/pimcore/skeleton$ ls -l vendor/pimcore/
total 8
drwxrwxr-x  5 zhy www-data 4096 Nov 20 09:43 data-hub
drwxrwxr-x 10 zhy www-data 4096 Nov 20 09:43 pimcore
```
But I don't see anything in the Pimcore admin interface menu:
![image](https://user-images.githubusercontent.com/612946/69242442-d22b0700-0bdb-11ea-93c9-00065969849c.png)

**Comment by weisswurstkanone** [comment]
Is it enabled? Check the extension manager. File | Bundles.

**Comment by dvesh3** [comment]
It should be installed and enabled here
![image](https://user-images.githubusercontent.com/5137917/69242909-287b5400-0ba2-11ea-8ee5-8ecad7b2de26.png)

**Comment by NiklasBr** [comment]
Can you run the command `pimcore:migrations:migrate --bundle=PimcoreDataHubBundle`?

**Comment by devondahon** [comment]
Ok, great, thanks!
Knowing that my website is `my.website.com`, what URL should I call to get GraphQL data ?

**Comment by weisswurstkanone** [comment]
It is documented here: https://github.com/pimcore/data-hub/blob/master/doc/GraphQL.md

**Comment by devondahon** [comment]
Thanks!

**Comment by arsenepotsi** [comment]
Bonjour pouvez-vous m'aider avec cette erreur ?

There is no extension able to load the configuration for "pimcore_ecommerce_framework" (in /var/www/html/pimcore/src/AppBundle/Resources/config/pimcore/ecommerce/ecommerce-config.yml). Looked for namespace "pimcore_ecommerce_framework", found "framework", "twig", "monolog", "swiftmailer", "doctrine", "sensio_framework_extra", "cmf_routing", "presta_sitemap", "scheb_two_factor", "security", "web_profiler", "debug", "pimcore_generator", "pimcore_admin", "pimcore", "output_data_config_toolkit", "pimcore_customer_management_framework", "server_side_matomo_tracking", "app", "httplug", "hwi_oauth" in /var/www/html/pimcore/src/AppBundle/Resources/config/pimcore/ecommerce/ecommerce-config.yml (which is being imported from "/var/www/html/pimcore/src/AppBundle/Resources/config/pimcore/config.yml").
