### ISSUE TITLE
component of type Image seems not recognized by data-hub

### ISSUE THREAD

**Issue by devondahon** [pimcore/data-hub#136]
It seems that the component of type `Image` is not recognized by `data-hub` in getObjectListing.

When I try with:
```
{
  getProductListing(ids: "52") {
    edges {
      node {
        id
        classname
        name
        img2 {
          id
        }
      }
    }
  }
}
```
Adding this `img2 { id }` returns the following error:
https://gist.github.com/devondahon/045a39948144432f23a45f00955f86e4

I also posted on pimcore forum about this:
https://talk.pimcore.org/t/data-hub-get-image-indirectly/2879

If don't add `id` for `img2 { }` , leaving the brackets empty, then I get this response:
```
{
  "errors": [
    {
      "message": "Syntax Error: Expected Name, found }",
      "extensions": {
        "category": "graphql"
      },
      "locations": [
        {
          "line": 10,
          "column": 9
        }
      ]
    }
  ]
}
```

**Comment by NiklasBr** [comment]
Can you do this?

```graphql
{
  getProductListing(ids: "52") {
    edges {
      node {
        id
        classname
        name
        img2 {
          ... on asset {
              /* your fields here, e.g. fullpath */
          }
        }
      }
    }
  }
}
```

**Comment by devondahon** [comment]
No, I get the same "html page" error with:
```
{
  getProductListing(ids: "52") {
    edges {
      node {
        id
        classname
        name
        img2 {
          ...on asset {
            fullpath
              # /* your fields here, e.g. fullpath */
          }
        }
      }
    }
  }
}
```

**Comment by NiklasBr** [comment]
Can you show your schema and security definitions?

**Comment by weisswurstkanone** [comment]
@NiklasBr , already investigating ...

**Comment by weisswurstkanone** [comment]
unable to reproduce.

But after reading your post at https://talk.pimcore.org/t/data-hub-get-image-indirectly/2879 ...
did you actually add it to your schema like this?

![image](https://user-images.githubusercontent.com/6142086/69432070-3f07e380-0d39-11ea-8c2c-6e3b1e0f5a0d.png)

**Comment by devondahon** [comment]
Yes, I did as you can see on the screenshot below:

<img width="960" alt="Capture d’écran 2019-11-22 à 11 13 21 PM" src="https://user-images.githubusercontent.com/612946/69437202-cd05bd80-0d7d-11ea-9c6c-f24156e4acf6.png">

**Comment by devondahon** [comment]
My problem was finally  fixed after switching **composer** mirror and upgrading **Pimcore**.
```
composer config -g repo.packagist composer https://mirrors.aliyun.com/composer/
COMPOSER_MEMORY_LIMIT=-1 composer -vvv update
```
Thanks for you help
