### ISSUE TITLE
Can't use any transformers

### ISSUE THREAD

**Issue by mrpdean** [pimcore/data-hub#138]
Hi,

As soon as I try to add any type of transformer to my query schema I receive the following error when running the query:

Attempted to load class "_**<insert class of transformer>**_" from namespace "Pimcore\\Bundle\\DataHubBundle\\GraphQL\\QueryOperatorConfigGenerator".
Did you forget a "use" statement for another namespace?

For example, if I try to add a Substring operator the error will be:

Attempted to load class "Substring" from namespace "Pimcore\\Bundle\\DataHubBundle\\GraphQL\\QueryOperatorConfigGenerator".

Or if I try to add a Thumbnail transformer the error is:

Attempted to load class "Thumbnail" from namespace "Pimcore\\Bundle\\DataHubBundle\\GraphQL\\QueryOperatorConfigGenerator".

**Comment by weisswurstkanone** [comment]
Unable to reproduce.

**Comment by NiklasBr** [comment]
@mrpdean A *transformer* need a second field in the model which it transforms. Are you dragging the field to transform onto the *transformer*?

**Comment by weisswurstkanone** [comment]
thanks @NiklasBr , @mrpdean can you provide a screenshot of your schema def?

**Comment by NiklasBr** [comment]
It should look like this:
![Skärmbild (255)](https://user-images.githubusercontent.com/279826/69873619-1e9bd400-12b9-11ea-90f1-f9d99199c14b.png)

**Comment by mrpdean** [comment]
Here is what I'm doing.

Starting with the most basic schema:

![screen-1](https://user-images.githubusercontent.com/4626255/69909020-40779100-1448-11ea-8205-dbdf1c738dcc.jpg)

This work fines:

![screen-2](https://user-images.githubusercontent.com/4626255/69909021-49686280-1448-11ea-93a5-3c65345a8dc9.jpg)

The, as soon as I add a transformer, in this case a Substring:

![screen-3](https://user-images.githubusercontent.com/4626255/69909026-584f1500-1448-11ea-8793-62e71170773b.jpg)

I get the error, even without referencing the field in the query:

![screen-4](https://user-images.githubusercontent.com/4626255/69909028-68ff8b00-1448-11ea-8692-89e122ec6ddd.jpg)

**Comment by weisswurstkanone** [comment]
Can you reproduce this on demo.pimcore.fun ?

**Comment by weisswurstkanone** [comment]
any updates ?

**Comment by mrpdean** [comment]
Yeah, I can't reproduce the error on demo.pimcore.fun.

Guess it's an issue with my install but I've got no idea what it could be.
