### ISSUE TITLE
Order of document elements in areblocks/blocks

### ISSUE THREAD

**Issue by andreas-ateles** [pimcore/data-hub#139]
When making a `getDocument` query for a `document_page`, the `elemens` are returned in a kind of "added ID/time" order, not the actual order that the elements/editables/bricks are in on the page (in an `areablock`/`block`), and there doesn't seem to be any field for the order by either. 

This makes it impossible to order the editables/bricks as it is done in the CMS.

This feature important for us. I'm thinking a simple solution right now would be to return the elements by the order that are placed on in the document. Otherwise maybe add a field for the order index of some kind?

**Comment by weisswurstkanone** [comment]
imho, this is impossible to accomplish as it depends on the current state of your document.

**Comment by andreas-ateles** [comment]
@weisswurstkanone all I'm asking for here is the order the elements/bricks are ordered in the areas/blocks. This information is obviously available (as Pimcore has it in admin). I'm in the process of making a PR with a change to return the elements order as such.

**Comment by weisswurstkanone** [comment]
great 👍
