### ISSUE TITLE
document_tagImage image field returns null

### ISSUE THREAD

**Issue by andreas-ateles** [pimcore/data-hub#140]
When making a `getDocument` query and getting the `image` field of `document_tagImage` element, it just returns `null`, and I'm unable to get the image set on the editable.

Example query:

```graphql
query {
  getDocument(path: "/test") {
    ...on document_page {
      fullpath
      elements {
        ...on document_tagImage {
          __tagName
          __tagType
          alt
          image {
            id
            fullpath
          }
        }
      }
    }
  }
}
```

Response:
```json
{
  "data": {
    "getDocument": {
      "fullpath": "/test",
      "elements": [
        {
          "__tagName": "content:3.image__image",
          "__tagType": "image",
          "alt": "",
          "image": null
        }
      ]
    }
  }
}
```

**Comment by andreas-ateles** [comment]
To get access to images had to give the GraphQL configuration read access to the assets (on the "Security Definition" tab).

**Comment by weisswurstkanone** [comment]
btw, for development read the last section here
https://github.com/pimcore/data-hub/blob/master/doc/graphl/Security.md

default is that it will silently drop the data you are not allowed to read to
