### ISSUE TITLE
gatsby develop failed when try to include data-hub with "gatsby-source-graphql"

### ISSUE THREAD

**Issue by Anne-chaG** [pimcore/data-hub#142]
Hi !
We trying to include Pimcore data-hub through Gatsby.

We use "gatsby-source-graphql" plugin and add this config into our `gatsby-config.js` 
`{
      resolve: 'gatsby-source-graphql',
      options: {
        typeName: 'api',
        fieldName: 'api',
        url:'https://URL/pimcore-graphql-webservices/APP?apikey=APIKEY',
        refetchInterval: 60,
      },
    }`

Errors appears when we try to `gatsby develop, here the log : 

=================================================
success open and validate gatsby-configs - 0.025s
success load plugins - 0.447s
success onPreInit - 0.004s
success initialize cache - 0.016s
success copy gatsby files - 0.037s
success onPreBootstrap - 3.018s
success createSchemaCustomization - 0.004s
success source and transform nodes - 1.230s
success building schema - 0.296s
success createPages - 0.002s
success createPagesStatefully - 0.081s
success onPreExtractQueries - 0.003s
success update schema - 0.026s

 ERROR 

UNHANDLED REJECTION Name "__tagName" must not begin with "__", which is reserved by GraphQL introspection.

Name "__tagType" must not begin with "__", which is reserved by GraphQL introspection.

  Error: Name "__tagName" must not begin with "__", which is reserved by GraphQL introspection.
  Name "__tagType" must not begin with "__", which is reserved by GraphQL introspection.

  - query-compiler.js:199 extractOperations
    [app]/[gatsby]/dist/query/query-compiler.js:199:20
  
  - query-compiler.js:173 processQueries
    [app]/[gatsby]/dist/query/query-compiler.js:173:7
  
  - query-compiler.js:93 compile
    [pp]/[gatsby]/dist/query/query-compiler.js:93:19
  
  - index.js:477 async module.exports
    [app]/[gatsby]/dist/bootstrap/index.js:477:3
  
  - develop.js:419 async module.exports
    [app]/[gatsby]/dist/commands/develop.js:419:7
  

not finished extract queries from components - 0.336s

=================================================

Moreover, same error occurs on our data-hub graphiQL console : 
<img width="856" alt="Capture d’écran 2019-11-28 à 16 04 20" src="https://user-images.githubusercontent.com/32160571/69816493-cb624c80-11f8-11ea-8a4b-1cbbb3e037d1.png">

**Comment by andreas-ateles** [comment]
@Anne-chaG if you can use the latest released version instead of the master branch it would probably work better as these fields were added for the documents API, which has not been released yet.

**Comment by weisswurstkanone** [comment]
Thanks for reporting. Tried to use a word which cannot clash with any other word.
Removed one underscore for now. Better ideas ?
