### ISSUE TITLE
Folder content list

### ISSUE THREAD

**Issue by devondahon** [pimcore/data-hub#144]
How to get the content of a folder ?

I currently have this:
```
{
  getObjectFolder(id: 296) {
    id
  }
}

```
returning this:
```
{
  "data": {
    "getObjectFolder": {
      "id": "296"
    }
  }
}
```

This folder contains subfolders containing objects which I also need to get.

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/data-hub/blob/master/doc/graphl/Filtering.md as an example
