### ISSUE TITLE
Data-hub tries to access getName method on a fieldCollection class 

### ISSUE THREAD

**Issue by Anne-chaG** [pimcore/data-hub#147]
Hi ! 

I'm facing this issue when I create my queries and wanna run them in GraphiQL. 

`Call to undefined method getName in class Pimcore\Model\DataObject\Fieldcollection\Definition`

Based on my error log, it seems that the exception is throwed on ObjectMetadataType.php line 47 : 
```php
public function __construct(Service $graphQlService, Data $fieldDefinition = null, $class = null, $config = [])    {
$this->setGraphQLService($graphQlService);        
$this->class = $class;        
$this->fieldDefinition = $fieldDefinition;        
$config['name'] = 'object_' . $class->getName() . '_' . $fieldDefinition->getName();        
$this->build($config);        
parent::__construct($config);    }
```

**Comment by weisswurstkanone** [comment]
Could you please describe in detail how your data model looks like, steps to reproduce, ideally on on the demo site (demo.pimcore.fun).

**Comment by romainbessugesmeusy** [comment]
Hi @weisswurstkanone, thank you for your reply. I've attached a zip containing our classes folder that you should be able to import using the `pimcore:deployment:classes-rebuild` command.

[mg-pim-master-var-classes.zip](https://github.com/pimcore/data-hub/files/3932725/mg-pim-master-var-classes.zip)

**Comment by weisswurstkanone** [comment]
what's your query ?

**Comment by romainbessugesmeusy** [comment]
Actually we're not able to write any query, as Pimcore is replying with 500 err :

<img width="1915" alt="Capture d’écran 2019-12-06 à 16 39 39" src="https://user-images.githubusercontent.com/3127404/70335146-07c02900-1847-11ea-9742-648025234c14.png">

**Comment by weisswurstkanone** [comment]
a bit of a guesswork ... :-)

**Comment by weisswurstkanone** [comment]
please give it a try

**Comment by romainbessugesmeusy** [comment]
It seems to be working just fine! Thank you very much
