### ISSUE TITLE
In mutation schema fields unable to add manytomanyobjectRelation

### ISSUE THREAD

**Issue by PriyaSahi** [pimcore/data-hub#159]
Hi,

I have installed datahub configuration and implemented query schemas which are working fine. But am facing issue with mutation schema fields in which when am trying to add any relational datatype it is showing "the datatype manytomanyobjectrelation not supported yet".

Am I missing anything? Can you please give me a solution for this.

Thank you
![mutationissue](https://user-images.githubusercontent.com/39255210/73821913-ff6e7500-481a-11ea-9edc-db7e1e839e28.png)

**Comment by weisswurstkanone** [comment]
Currently not supported.

See https://github.com/pimcore/data-hub/blob/master/doc/graphl/Mutations.md for supported mutation types.

Do you want to create a PR? Should be quite similar many-to-many-relations except that only objects are allowed.

**Comment by weisswurstkanone** [comment]
It is supported now

**Comment by PriyaSahi** [comment]
Thank you so much, it's working now. Do advancedManyToManyObjectRelation also will be supported? If not is there any other alternative to advancedManyToManyObjectRelation to use in the mutation schema field? 
Thanks in advance.

**Comment by weisswurstkanone** [comment]
There will be support for advanced relations as well but I am still not sure about the appropriate schema. Ideas are welcome ;-)

**Comment by PriyaSahi** [comment]
So advancedManyToManyObjectRelation in mutation schema fields cannot be used as of now?
If you find any alternative please let me know.
Thank you.

**Comment by weisswurstkanone** [comment]
I am saying that manyToManyObjectRelations can be used. For the advancedManyToMany types I have to find a decent idea for the graphql schema

**Comment by PriyaSahi** [comment]
ok. Thank you for your support and immediate response.
