### ISSUE TITLE
DataHub & Custom Layouts

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#163]
Currently, Custom Layouts don't seem to be supported in DataHub:

When you have an invisible field on a data object that you're setting visible for variants via Custom Layouts, this field can not be accessed in the DataHub Schema Definition => Query Schema => Query Schema Fields definition.

As a temporary workaround it's possible to uncheck the invisible checkbox on the data object itself, then add it to the Available Fields in DataHub Schema Fields definition and afterwards check the invisible checkbox again.

I see two potential solutions: In the Schema Fields definition list all fields that are available even in Custom Layouts or make Custom Layouts selectable to see their fields.

**Comment by weisswurstkanone** [comment]
Custom layouts are about layouts. Why not take every field from the class definition and make it visible  regardless of how it is classified in the definition.
Place where it get's hidden is here
https://github.com/pimcore/pimcore/blob/739957f849b8804683f71eef9be5c21493d932f5/bundles/AdminBundle/Resources/public/js/pimcore/object/helpers/classTree.js#L223

Note that this is shared code. What do you think. Could you provide a PR that makes it visible if used in the context of datahub ?

**Comment by weisswurstkanone** [comment]
@julmot what do you think?

**Comment by julmot** [comment]
@weisswurstkanone Sounds easy and I'm willing to contribute. However, I'm currently in the end of a sprint, therefore I won't have time in the next couple of days, sorry.

**Comment by weisswurstkanone** [comment]
see https://github.com/pimcore/data-hub/pull/164

requirement from core side: https://github.com/pimcore/pimcore/pull/5924

**Comment by weisswurstkanone** [comment]
Should work with 6.6.0 then.
