### ISSUE TITLE
Add support for fieldcollections mutations

### ISSUE THREAD

**Issue by snmuhein** [pimcore/data-hub#168]
Mutations on fieldcollections are not implemented yet. The "yet" in the error-diaolog suggests that there are plans to support this. Any ideas when this feature will be done?
<img width="1013" alt="Screen Shot 2020-03-05 at 10 54 05" src="https://user-images.githubusercontent.com/45623668/75969752-aeac7380-5ecf-11ea-9903-c5b9cd60d516.png">

**Comment by weisswurstkanone** [comment]
maybe an option for you:
https://github.com/pimcore/data-hub/issues/172
