### ISSUE TITLE
Feature Request: Asset path specifically for media query

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#169]
This is a follow-up from #13. To solve the purpose of media query specific images, by this PR the whole image is returned as HTML to solve media query settings on image thumbnails.

However, this has a few problems:

- You can not work with only the source of a specific media query.
- The asset is returned with a relative path. To make it work in a decoupled application where the frontend runs on a different domain I currently have to manipulate all image URLs with the host as prefix with a RegExp, which feels wrong.

Therefore, I'd like to request the possibility to load an asset and its media query sources as string, not as HTML.

So, I'd expect something like:

```gql
image: configurator_Product_Thumbnail {
  src: fullpath(thumbnail: "configurator_product_thumbnail"),
  mediaQueries
}
```

resulting in e.g.:

```json
{
  "image": {
    "src": "/...../XYZ.png",
    "mediaQueries": {
      "768px": {
        "src": "/...../XYZ__768.png",
      }
    }
  }
}
```

**Comment by NiklasBr** [comment]
> The asset is returned with a relative path. To make it work in a decoupled application where the frontend runs on a different domain I currently have to manipulate all image URLs with the host as prefix with a RegExp, which feels wrong.

You can solve this with [Asset Events](https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Event_API_and_Event_Manager.html) to add domain and such to the URL:s. That's exactly what we did.

**Comment by weisswurstkanone** [comment]
So solved for you I guess. If you still feel the need please create PR. Thanks a lot!

**Comment by weisswurstkanone** [comment]
https://github.com/pimcore/pimcore/blob/master/lib/Event/FrontendEvents.php

**Comment by julmot** [comment]
No, it's actually not solved. The above mentioned fix is just for receiving images with absolute paths. But, it's still not possible to fetch image sources per viewport.

**Comment by julmot** [comment]
Another con of the HTML solution:

for Angular applications it's rather unlikely to embed images with HTML. Because this would make it necessary to sanitize the HTML for every image, since you can't just paste HTML from outside into an Angular application.

**Comment by NiklasBr** [comment]
In Vue there is a [rawHtml attribute](https://vuejs.org/v2/guide/syntax.html#Raw-HTML), in React I know [it is possible](https://reactjs.org/docs/jsx-in-depth.html#children-in-jsx), jQuery needs nothing special to append a string into the DOM, but Angular has nothing similar?

**Comment by julmot** [comment]
Well, you can call a method to bypass HTML security on the `DomSanitizer` in Angular or build your own pipe like a [`rawHtml`/`safe`](https://medium.com/@swarnakishore/angular-safe-pipe-implementation-to-bypass-domsanitizer-stripping-out-content-c1bf0f1cc36b). However, this won't solve your problems. Because in Angular you have a default `ViewEncapsulation` that simulates shadow dom by adding attributes to the elements, similar to CSS modules or styled components in React. So you have e.g. classes like `[_nghost-byu-c22] .my-image`. From my point of view this would not work with HTML added to the DOM from the outside and injecting the custom class name into the HTML string received from DataHub. So, it would be necessary to disable `ViewEncapsulation` entirely to make classes globally available without simulated shadow DOM.

But again, this solution with receiving an HTML string isn't really a decoupled philosophy. It should be possible to fetch the image sources per viewport (and `@2x` and `@3x` versions of that source) and build your own image tag component.

Therefore, please re-open this issue.
