### ISSUE TITLE
Are fragments supported?

### ISSUE THREAD

**Issue by jeremystucki** [pimcore/data-hub#175]
# Are fragments in queries supported?

Every field that I specify in a fragment returns `null`.  
Am I the only one experiencing this issue?

## Example without fragments
Input:
```
chauffeur {
    ... on object_Person {
        id
        firstname
        lastname
    }
}
```
Output:
```json
"chauffeur": [
    {
        "id": "214",
        "firstname": "Foo",
        "lastname": "Bar"
    }
]
```

## Example with fragments
Input:
```
chauffeur {
    ... on object_Person {
        id
        firstname
        ...personDetails
    }
}

...

fragment personDetails on object_Person {
    lastname
}
```
Output:
```json
"chauffeur": [
    {
        "id": "214",
        "firstname": "Foo",
        "lastname": null
    }
]
```

**Comment by julmot** [comment]
Good question. Already switched from fragments to redundant code in January, as I also encountered issues which fragments & DataHub.

**Comment by jeremystucki** [comment]
Anyone?

Ping @dvesh3

**Comment by dvesh3** [comment]
@jeremystucki currently, it is not supported and we'll investigate it soon. thanks for reporting 👍
