### ISSUE TITLE
[Question] Progress on fieldcollections/galleries

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#18]
We would like to continue improving this bundle, but to avoid doing duplicate work, could you tell us if any work has been done on either *Structured: Field-Collections* or *Media: Image Gallery* object data components?

**Comment by fashxp** [comment]
Hi, we would love to see PRs for that. Currently there is no work going on for field collections or image gallery, so just go for it. 
Our next sprint for data-hub will start not before in two weeks.

**Comment by NiklasBr** [comment]
Good to know. :)

We have started with an attempt at adding support for `Pimcore\Model\DataObject\ClassDefinition\Data\ImageGallery`

**Comment by NiklasBr** [comment]
As I wrote in the PR, but would like to expand on here, I would love to get some quick initial feedback on the general architecture of the new feature, does it seem like I did it "the Pimcore way" with regards to file placement, code paths and so on?

**Comment by weisswurstkanone** [comment]
Added a few comments. The direction looks quite ok so far :-) Many thanks for the great progress!
