### ISSUE TITLE
[Asset] Localized Field Language Property not working

### ISSUE THREAD

**Issue by solverat** [pimcore/data-hub#187]
Script

```graphql
query getMyObject($primary: String, $secondary: String) {
  getMyObject(id: 17194) {
    
    name_primary: name(language: $primary) # (localized field) works
    name_secondary: name(language: $secondary) # (localized field) works
    asset_primary: assetField(language: $primary) { # (localized field) doesn't work
      ... on asset {
        fullpath
      }
    }
    asset_secondary: assetField(language: $secondary) { # (localized field) doesn't work
      ... on asset {
        fullpath
      }
    } 
  }
}

```
Query Variables
```graphql
{
  "primary": "en",
  "secondary": "de"
}
```

I have no exact solution for this but I tried to debug this and I'm able to report two things:

## 1. Bug (?)

The `$arguments['language']` stays empty, but `$args['language']` comes with the right value.

https://github.com/pimcore/data-hub/blob/8352fc616790d51096edf39f4da771e4ee385646/src/GraphQL/FieldHelper/AssetFieldHelper.php#L46

## Solution (?)

If I'm adding this block:

https://github.com/pimcore/data-hub/blob/8352fc616790d51096edf39f4da771e4ee385646/src/GraphQL/FieldHelper/DataObjectFieldHelper.php#L364-L379

into this block:

https://github.com/pimcore/data-hub/blob/8352fc616790d51096edf39f4da771e4ee385646/src/GraphQL/Service.php#L958-L960

while changing getter to:

```php
$result = $container->$getter($isLocalizedField ? $args['language'] : null);
```

...it works. But I don't think this is the right place to do.

**Comment by weisswurstkanone** [comment]
Hi @solverat , any news on this ?

**Comment by weisswurstkanone** [comment]
@solverat thanks for your investigations!
