### ISSUE TITLE
Tags & Snippet Management runs in GraphiQL

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#188]
Tag & Snippet Management runs even within GraphiQL:

https://XXX.YYY/pimcore-datahub-webservices/explorer/

From my point of view this doesn't make sense, since this is a Pimcore specific route like the Pimcore admin interface itself.

**Comment by weisswurstkanone** [comment]
Not sure if I can follow you :-)

**Comment by julmot** [comment]
@weisswurstkanone So I have configured a script within the Pimcore Tag & Snippet Management. I have not added any exclude RegExp. But even then, this snippet will not be added to the source code in the Pimcore admin interface. In the Pimcore GraphiQL Explorer (when opened as tab) it's added though. From my point of view tags should only be added in non-Pimcore routes.
