### ISSUE TITLE
Filter or not working as expected

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#197]
Is a Pimcore Problem in combination with DataHub

This query does not work as expected and creates and AND condition instead of a given or 

```
getProductListing( filter:"{ \"$or\": [{\"axId\": \"041 1464\"}, {\"axId\": \"041 1465\"}]}"
```

This query works:

```
getProductListing( filter:"{\"$or\": [{\"$or\": [{\"axId\": \"041 1464\"}, {\"axId\": \"041 1465\"}]}]}") {
```

I think the Problem happens here: 
https://github.com/pimcore/data-hub/blob/master/src/GraphQL/Resolver/QueryType.php#L383

The params should already be what I give DataHub in the first level of filter.

**Comment by dvesh3** [comment]
Unable to reproduce
![image](https://user-images.githubusercontent.com/5137917/79428472-7ddb5600-7fc6-11ea-9e09-3e22a0bb588e.png)
please see https://github.com/pimcore/data-hub/issues/178

**Comment by dpfaffenbauer** [comment]
Yep, I see where the problem is, I am running an outdated version. Let me update it and try again.

**Comment by dpfaffenbauer** [comment]
yep, working with 0.6.

So, this is broken than for the deprecated webservices and not graphql anymore.

Thanks @dvesh3 for your help :)

**Comment by dvesh3** [comment]
@dpfaffenbauer this was fixed in webservices only https://github.com/pimcore/pimcore/pull/6094 and then we decoupled it for data-hub https://github.com/pimcore/data-hub/issues/179 so this was fixed in both places. 😉

**Comment by dpfaffenbauer** [comment]
ok, good to know as well :)
