### ISSUE TITLE
DataHub Stable Release

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#199]
Since I've seen that the [Early Preview warning](https://github.com/pimcore/data-hub/commit/b7f37e40137ebcea30d54d2f13c96feeae51b82d) was removed and we're using DataHub even in production, as in our most recent [Vespa Shop](https://shop.vespa.ch) project – currently in a hybrid architecture, where the configurator is decoupled with DataHub, but landing pages and checkout aren't due to the lack of #113 and #156 – I'm curious, when will DataHub be finally released in its v1.0.0 :fireworks: version?

**Comment by fashxp** [comment]
we need to stabilize the documents implementation (feedback welcome) and want to integrate some parts of the ecommerce functionality. then we are ready for 1.0.0 release.

**Comment by julmot** [comment]
@fashxp Have you seen my inputs [here](https://github.com/pimcore/data-hub/issues/113)? You've closed this topic about Documents within DataHub, but as far as I can see there's still no integration for the CMS area inside Pimcore. For example there's built-in integration to author and manage bricks with only a decoupled application – without any Bricks at all. As this would mean to re-think the entire WYSIWYG possibilities.

**Comment by fashxp** [comment]
I did see your comments indeed. I'm not sure though if I can follow you. What do you mean with CMS integration? Please continue the conversation at #113

**Comment by julmot** [comment]
@fashxp [I did](https://github.com/pimcore/data-hub/issues/113#issuecomment-704555138).
