### ISSUE TITLE
Class panels should not be added to definition

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#20]
When defining the Graph QL schema it is possible to add panels to the queyable fields, this has no detrimental effect (that I can find) but they should not be able to de added to the query definition.

![Skärmbild (133)](https://user-images.githubusercontent.com/279826/57214243-ab173a00-6fe9-11e9-98c0-12f16aaf6e1c.png)

**Comment by weisswurstkanone** [comment]
Unable to reproduce. How did you accomplish this?

**Comment by NiklasBr** [comment]
By double-clicking the panel.

**Comment by weisswurstkanone** [comment]
same for the grid configuration, see https://github.com/pimcore/pimcore/issues/4329
