### ISSUE TITLE
"Internal Server Error" using Mutation "create" and mandatory translated field

### ISSUE THREAD

**Issue by ttheuerkauf** [pimcore/data-hub#203]
I have a problem when trying to create a new object by mutation "create", if this object has a mandatory field which is translated (into two languages):

![grafik](https://user-images.githubusercontent.com/48792043/79962912-f8a1e680-8488-11ea-8248-fcdb46967018.png)

If I switch the field "name" to non mandatory, the object can be created correctly.

This behaviour is in my opinion somewhat clear, because there is no way to input the field name in all languages into the create-mutation. The value for the non-default language is simply missing, therefore Pimcore throws an exception which then results in the Internal Server Error.

Is there any undocumented way to perform this mutation correctly?

**Comment by weisswurstkanone** [comment]
Currently no. Maybe we should add a flag to the create operation.
Can you create a PR please ?

Dirty workaround for now could be:
- add a listener to ExecutorEvents::PRE_EXECUTE
- in the event handler add a listener to DataObjectEvents::PRE_ADD and call $e->getObject()->setOmitMandaroryCheck(true)
