### ISSUE TITLE
Interface implementation types returned as empty objects in lists

### ISSUE THREAD

**Issue by PMarci** [pimcore/data-hub#206]
I've been trying queries with DataHub for an integration project and noticed what seems to be incorrect behavior when querying with inline fragments.
Here's a query that asks for properties on a trivial DataObject class with type `property_text`
![image](https://user-images.githubusercontent.com/22032937/80100623-7c82ce00-8570-11ea-9f1f-bed957a55694.png)
an empty object appears in the list, presumably because of the way resolvers for different property types work. Here's the `Properties` tab of the object in question:
![image](https://user-images.githubusercontent.com/22032937/80100781-bb188880-8570-11ea-90fe-1dd324efcceb.png)

Reading through the [GraphQL documentation](https://graphql.org/learn/schema/#union-types), it seems to me like this contradicts the intended behavior of GQL APIs:
>Note that name is still specified on Starship because otherwise it wouldn't show up in the results given that Starship is not a Character!

And for good reason, having rogue empty elements appear in arrays complicates processing of the returned data. Am I correct in my interpretation that this is, in fact, a bug?

**Comment by PMarci** [comment]
This is on DataHub commit `dev-master#4401634` but seen as this affects DataObjects I suspect it's much the same on `master` as well.

**Comment by PMarci** [comment]
Works the same on `0.6`.
![image](https://user-images.githubusercontent.com/22032937/80102429-00d65080-8573-11ea-8ad5-c6571e0c579d.png)
![image](https://user-images.githubusercontent.com/22032937/80102469-0c297c00-8573-11ea-9fca-19bf34a6345c.png)

**Comment by dvesh3** [comment]
@PMarci This is not a bug. Either use `keys` argument to filter properties or define all property types https://github.com/pimcore/data-hub/blob/master/doc/graphl/querysamples/Sample_ElementProperties.md#request

**Comment by PMarci** [comment]
Based on the GraphQL documentation one would think that defining the implementing type of the `ElementProperty` interface _would be the filtering_, and that the inline fragment should prevent empty objects from appearing. If one is forced to have prior knowledge of the properties defined on a particular object in order to avoid empty `ElementProperty` objects from showing up, that precludes many avenues of processing an arbitrary set of properties that a DataObject might have. Or at least without checking every object for emptiness.
The alternative of defining every type (and at least one field for each!) in the query is also sub-optimal, because one might not be interested in them, I understood the point of GraphQL as having the ability to avoid such unnecessary overheads.

**Comment by PMarci** [comment]
Scratch that, it would seem this query from the demo behaves the same way.
![image](https://user-images.githubusercontent.com/22032937/80204665-916f6800-8629-11ea-94ff-6a81567f7675.png)
So it seems we'll have to just live with this behavior.
