### ISSUE TITLE
GraphQL Mutation createAssetFolder always said "unable to resolve parent"

### ISSUE THREAD

**Issue by thomas-gravel** [pimcore/data-hub#208]
If you call the createAssetFolder with parentId and/or path, you will ever get the answer "unable to resolve parent".

I debugged this and find out, that there is a Bug or a missing Feature.
The call always search in the table objects not in the table asset.

I fixed it with the code bellow in the File "src/GraphQL/Mutation/MutationType.php" at Line 662:
if (isset($args["parentId"])) {
                if ($elementType === "asset") {
                        $parent = Folder::getById($args["parentId"]);
                } else {
                        $parent = AbstractObject::getById($args["parentId"]);
                }
            } else if (isset($args["path"])) {
                if ($elementType === "asset") {
                        $parent = Folder::getByPath($args["path"]);
                } else {
                        $parent = AbstractObject::getByPath($args["path"]);
                }
            }

**Comment by weisswurstkanone** [comment]
True, also documents are missing. Can you create a PR please ?
Documents are missing around line 685 too.

**Comment by thomas-gravel** [comment]
I think there is no call for createDocumentFolder in the file.
It think this is a new feature ....

**Comment by weisswurstkanone** [comment]
I see, should be a one-liner. Can you add that as well? Maybe it makes sense to change the title of this issue :-)

**Comment by weisswurstkanone** [comment]
fixed via https://github.com/pimcore/data-hub/commit/d1dcf622be56cbd3a7be2ec524d379751ca2c5f9
