### ISSUE TITLE
Attempt to use LocaleSwitcher Operator for createObject Mutation caused error and GraphiQL non-usable

### ISSUE THREAD

**Issue by weichee76** [pimcore/data-hub#210]
Understand that DataHub is still new. Hope this helps the team to troubleshoot.

To replicate issue, just create an LocaleSwitcher operator, drop any localizedFields element as child, save changes and try to open GraphiQL.

Error observed as follows 
`Uncaught PHP Exception Symfony\Component\DependencyInjection\Exception\ServiceNotFoundException: "Service "typegenerator_mutationoperator_localeswitcher...`

**Comment by weisswurstkanone** [comment]
thx for the hint
