### ISSUE TITLE
Enforce workspace permission checks at a central place

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/data-hub#214]
What needs to be refactored is to eliminate all duplication of the isAllowed checks. All these lines are copy/pasted everywhere.
if (!WorkspaceHelper::isAllowed($element, $context['configuration'], 'read')) {
    if (PimcoreDataHubBundle::getNotAllowedPolicy() == PimcoreDataHubBundle::NOT_ALLOWED_POLICY_EXCEPTION) {
        throw new NotAllowedException('not allowed to view document');
    } else {
        return null;
    }
}

**Comment by romainbessugesmeusy** [comment]
Hi, is it the reason we see a huge amount of queries like this:
`SELECT `read` FROM plugin_datahub_workspaces_object WHERE cid IN (1,1598,1215,1214,1213,24,20,11,10,1,1600) AND configuration = 'mg-app' AND `read`=1 ORDER BY LENGTH(cpath) DESC LIMIT 1` ?
