### ISSUE TITLE
Error: Parameter "clientname" for route "admin_pimcoredatahub_config"

### ISSUE THREAD

**Issue by julmot** [pimcore/data-hub#217]
We've just pulled the most recent DataHub changes and got the following error when clicking on the "Open in Tab" button in the schema editor:

![000257](https://user-images.githubusercontent.com/8310677/80733382-ec173100-8b0d-11ea-9a9b-0bc62f51be77.png)

![000256](https://user-images.githubusercontent.com/8310677/80733305-d144bc80-8b0d-11ea-9dc6-1d4c788bf308.png)

Maybe related to:
https://github.com/CandoImage/data-hub/commit/61bc92d6195df960a2daafd15d4e4fab0a7be84d

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo.pimcore.fun which is on dev-master.
Make sure that this is not a JS caching problem.

**Comment by yvess** [comment]
I'm having the same problem. When I revert the commit 61bc92d6195df960a2daafd15d4e4fab0a7be84d it works again

**Comment by xavier-experion** [comment]
I am also facing the same issue, @yvess  How can I resolve it?

**Comment by weisswurstkanone** [comment]
Temporarily reverted mentioned commit. Needs further investigations.

Reason for the change was that it stopped working after Pimocre\Routing\Element\Router was introduced.
https://github.com/pimcore/pimcore/commit/dff36f6c1426a772f8a445efc23fc4a9f2403a00

**Comment by julmot** [comment]
@weisswurstkanone @brusch From my point of view this is another example, why we need [semantic versioning](https://github.com/pimcore/pimcore/issues/4647) and why a [release description](https://github.com/pimcore/pimcore/pull/6085#issuecomment-620130508) would be very helpful.

**Comment by weisswurstkanone** [comment]
@julmot for reference: https://github.com/pimcore/pimcore/pull/6297#issuecomment-619981427

**Comment by dvesh3** [comment]
Hi @julmot, updating Pimcore to 6.6.2 should fix your issue.

**Comment by romainbessugesmeusy** [comment]
It is still broken when using Pimcore 6.6.4 and DataHub 0.6.1. Is there a workaround?

**Comment by yvess** [comment]
@romainbessugesmeusy the easiest workaround is to use the master version until the next release

**Comment by weisswurstkanone** [comment]
@romainbessugesmeusy https://github.com/pimcore/data-hub/releases/tag/v0.6.2
