### ISSUE TITLE
Asset List implementation

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#219]
Any plans or even ETA?

**Comment by weisswurstkanone** [comment]
No, but we can prioritize this if needed.

Anybody who wants to volunteer?

**Comment by dpfaffenbauer** [comment]
we currently use a workaround with getAssetFolder, so I think it is almost there, isn't it?

**Comment by weisswurstkanone** [comment]
Yes, almost. The rest can be taken from the object listing maybe

**Comment by weisswurstkanone** [comment]
thx @dpfaffenbauer for working this.
linked PR: https://github.com/pimcore/data-hub/pull/222

**Comment by ThaDaVos** [comment]
Sorry for commenting on this issue - but am I right in thinking that the AssetListing isn't fully implemented yet?
One can only query `__typename` and nothing more - while on the Dataobjects one can query a lot more
