### ISSUE TITLE
How to filter query in graphQL one to many relation?

### ISSUE THREAD

**Issue by saninshakya** [pimcore/data-hub#224]
I have two tables tire and brand. They have one-to-many relationship. So when I try following query

```
getTireListing (sortBy: "title") {

    edges {
      node {
        title
        description1
        description2

        brand  {
          ... on object_brand {
            brandName
          }
        }

      }
    }
    totalCount
  }
```
I am getting following result.

```
{
  "data": {
    "getTireListing": {
      "edges": [
        {
          "node": {
            "title": "Continental-ContieCocontact 5",
            "description1": "<p>test</p>\n",
            "description2": "<p>test 2</p>\n",
            "brand": {
              "brandName": "Continental"
            }
          }
        },
        {
          "node": {
            "title": "PremiumContact TM 6",
            "description1": "<p>test</p>\n",
            "description2": "<p>test</p>\n",
            "brand": {
              "brandName": "Continental"
            }
          }
        },
        {
          "node": {
            "title": "Tire name",
            "description1": "<p>fgafd</p>\n",
            "description2": "<p>asfasdf</p>\n",
            "brand": {
              "brandName": "Abc Brand"
            }
          }
        }
      ],
      "totalCount": 3
    }
  }
}
```

Now I need to filter tire with brand name, so I tried

```
getTireListing (
 sortBy: "title",
 filter: "{\"brand\" :  {\"brandName\": \"Continental\" } }"
) 
```

but I am getting error Column not found: 1054 Unknown column 'brandName' in 'where clause'

**Comment by weisswurstkanone** [comment]
List filtering based on attributes of referenced objects is not supported.

Please see https://pimcore.com/docs/6.x/Development_Documentation/Web_Services/Query_Filters.html for current features.

Do not forget
https://gitter.im/pimcore/pimcore and
https://talk.pimcore.org/

for questions and discussions ;-)

**Comment by mrpdean** [comment]
Just curious, are there any plans to support this in future?

**Comment by marcogonzalo** [comment]
Are you planning to add this functionality? We are needing to filter our products by one or more relations.

**Comment by nosovk** [comment]
related discussion https://github.com/pimcore/pimcore/discussions/10060

**Comment by nosovk** [comment]
@weisswurstkanone shouldn't we reopen that issue? Also link to docs seems to be broken (and it lacks some examples, like serach by id)

**Comment by mjnewman** [comment]
@nosovk We're currently handling this with [Calculated Values](https://pimcore.com/docs/pimcore/current/Development_Documentation/Objects/Object_Classes/Data_Types/Calculated_Value_Type.html)

In the above scenario, the TireListing class could have a Calculated Value:
- Name: BrandName
- Calculator type: Expression
- Calculator expression: object.getBrand() ? object.getBrand().getBrandName() : ''

The GraphQL filter would be:
- filter: "{\"BrandName\": \"Continental\" } "

@weisswurstkanone Would this be an appropriate solution at present? If so, does it pose a performance issue? Ideally we'll need to have 3-5 Calculated Values for some of our classes to give us the level of filtering we require.

If not, what is the best way to handle this type of filtering?
