### ISSUE TITLE
sqlObjectCondition only used for listings

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/data-hub#225]
Hi There,
this could be a bug report or a feature request, depends on what you think.

Current Situation:
After searching the code I see that the content from datahub config field "SQL Condition" is only used for getListing requests and not for ALL queries like the comment above the field says.

Would be great:
It would be great, if this sql condition would also be matched before doing mutations / deletions.  This might not be easy I know but it would make sense eg for this example:

Datahub configuration for books:
I added a SQL Condition like 'genre = fantasy' and configure this datahub so it has permissions for deletion and mutation and so on.
Then there is a request to delete a book with id 8 which has the genre = thriller.
Currently I think this will be allowed as the sql condition is not checked but the book will just be deleted.

Thank you and kind regards,
Sonja

**Comment by weisswurstkanone** [comment]
This is a feature request and there are no plans to support this.

You can either
a) get the elements first and then delete thim

or

b) add a custom endpoint which fits exactly to your needs. There is an example in the docs.

**Comment by Sonja-Schubert** [comment]
Hi,
Thank you for your answer. ok I will have a look at the custom endpoint then..
But the field description above the sqlObjectCondition field in backend should be changed through, shouldn't it?
Kind regards,
Sonja

**Comment by weisswurstkanone** [comment]
Please create a new ticket with a title that better suits the need in case you don't find anything. I'll close this one for now.

One option I can think of is to finish 
https://github.com/pimcore/data-hub/issues/214
first and add event there that allows to override the decision.
