### ISSUE TITLE
Additional event for custom permission check

### ISSUE THREAD

**Issue by Sonja-Schubert** [pimcore/data-hub#226]
Hi There,
I found the DataHub Event documentation on this page: https://github.com/pimcore/data-hub/blob/master/doc/graphl/Events.md

Situation:
I would like to use an event listener to implement a further permission check. For listings I found the solution with the event ListingEvents::PRE_LOAD liked described in documentation. But I need the same check for mutations and deletions. 
I tried to use MutationEvents::PRE_BUILD but failed to get the ID of the requested element 
 which I need to do my custom checks.

Would it be possible to have one or two further events directly before deleting or updating the dataobject? Or did I miss something to get the ID?

Kind regards,
Sonja

**Comment by weisswurstkanone** [comment]
Can you paste a sample here to better understand what you are trying to accomplish?

Did you have a look at pimcore's built-in events already
https://pimcore.com/docs/6.x/Development_Documentation/Extending_Pimcore/Event_API_and_Event_Manager.html ?

**Comment by Sonja-Schubert** [comment]
Hi,
Thank you for your fast answer. Sure I would like to do the following:
I have a restricted area on the website, where the login is done with members. In this restricted area an angular frontend shows dataobjects in a table and allows the logged in user to list, update and delete the dataobjects. I use the datahub as data provider for this angular frontend. I would like to add a further permission check to be sure the logged in user is allowed to see the dataobjects because they are related to the customer/logged in User object.
In the ListingEvent::PRE_LOAD I have something like this which works pretty good but I need the same for mutations and deletions:

> if ($listing->getClassName() === 'MyDataObjectClass') {
            $user = $this->security->getUser();
            // only allow any access to objects which are related to this logged in customer
            if(is_object($user)) {
                if(get_class($user) == 'Pimcore\Model\DataObject\Customer') {
                    $customerNo = $user->getCustomerNo();
                } else {
                    throw new Exception("You are not logged in correctly");
                }
            } else {
                throw new Exception("You are not logged in correctly");
            }
            $listing->addConditionParam('customerNo = ?', $customerNo, 'AND');
        }

Kind regards,
Sonja

**Comment by weisswurstkanone** [comment]
so DataObjectEvents::PRE_DELETE and so on

https://github.com/pimcore/pimcore/blob/6f8b0925f60cfa64a4f64689617cbb6bf65f79ac/lib/Event/DataObjectEvents.php

is not sufficient ?

**Comment by Sonja-Schubert** [comment]
Is it possible to check if the request comes from a datahub call? Because I don't want to check my custom permissions every time someone in Pimcore backend delete something...

**Comment by weisswurstkanone** [comment]
could be added as an event to  https://github.com/pimcore/data-hub/issues/214

**Comment by Sonja-Schubert** [comment]
After one night of sleep and searching the documentation... I would really appreciate an event in #214 cause this would be a central place for such checks.
