### ISSUE TITLE
Internal Server Error on createObjectFolder 

### ISSUE THREAD

**Issue by ttheuerkauf** [pimcore/data-hub#227]
When creating an object folder with
```
mutation {
  createObjectFolder(parentId:19, key: "ABC") {
    success
    message    
    id
  }
}
```
PimCore returns 
```
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 3,
          "column": 1
        }
      ],
      "path": [
        "createObjectFolder"
      ]
    }
  ],
  "data": {
    "createObjectFolder": null
  }
}
```
Error in Logfile is
`pimcore.ERROR: Class: Pimcore\Model\DataObject\Folder => call to undefined method setFilename [] []`

I think, this is caused by this line in file `src\GraphQL\Mutation\MutationType.php`:
![grafik](https://user-images.githubusercontent.com/48792043/81938890-dddd1080-95f5-11ea-8e50-c6252edfa3f9.png)

Is there anyone else with this error? This was working a few days ago.

Thank you very much!

**Comment by ttheuerkauf** [comment]
Found out that it is commit d1dcf622be56cbd3a7be2ec524d379751ca2c5f9

**Comment by weisswurstkanone** [comment]
thx!
