### ISSUE TITLE
Remove isAllowed check if not needed

### ISSUE THREAD

**Issue by romainbessugesmeusy** [pimcore/data-hub#228]
I notice a big overhead induced by `isAllowed` being called each time an object is queried. As we use data-hub and graphQL at build time with a Gatsby project, we do not need to enforce Workspace permissions, especially not every time an object or its parents are matched. 

What would you think of a flag in the `Configuration` object, that would dictate if permissions are enforced or not ?

**Comment by weisswurstkanone** [comment]
Would not add it  to the configuration but maybe as a event which gives feedback if decision already has been made (granted or denied).
Also see https://github.com/pimcore/data-hub/issues/226
What do you think?

**Comment by romainbessugesmeusy** [comment]
If my understanding is correct, your proposal implies that I would have to bind a listener to a `PRE_PERMISSION_CHECK` event and return something like `"bypassPermissionCheck" => true`. And this would skip the permission check process ? 
It's clearly doable but I feel like it's a tad overkill, don't you think?

**Comment by weisswurstkanone** [comment]
I would say that bypassing checks should be the exception, but yes, I see your point

**Comment by romainbessugesmeusy** [comment]
It depends on the community's usage of DataHub. I don't know what's the most frequent use case for Data-hub at the moment, but I wanted to share you mine. We're building  a Gatsby e-commerce front-end. This means our 70 000+ product pages are statically built by a runner in the Netlify cloud. Every second I gain on the DataHub side is a second I won't pay on the Netlify side.

That's why, for me and my use case, it doesn't make sense to have permission checks: 

- our GraphQL endpoints is privately used at build times and not by logged in users

- every bit of optimization is an improvement for our dev team and has a financial impact

**Comment by weisswurstkanone** [comment]
Correction: I was talking about #214 which has to be done first anyway. A PR covering both aspects would be nice, otherwise we should add this to the todo list.

**Comment by bramstroker** [comment]
When this permission checks are moved to a central place as suggested by me before, it would be easy enough to make the permission checks optional by introducing some configuration option for this. Than each client can decide if they need this permission validation. In our use case we have a front-end application requesting graphql through a middleware, so we are also not interested in any permission checks if this improves performance.
