### ISSUE TITLE
Increase verbosity of Field definition warning

### ISSUE THREAD

**Issue by romainbessugesmeusy** [pimcore/data-hub#229]
It would be helpful to give more context to the missing field definition warning here.

https://github.com/pimcore/data-hub/blob/f1c77f06599d40ba7187a7043ff9f2a4b503211c/src/GraphQL/FieldHelper/DataObjectFieldHelper.php#L99-L103

Here's what I would recommend: 
```php
Logger::error('could not resolve field "' . $key . '" in class ' . $class->getName());
```

**Comment by weisswurstkanone** [comment]
Hi @romainbessugesmeusy , can you submit a PR please? Thx!
