### ISSUE TITLE
Link type field trows exception

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#23]
## Summary

The `Link` type data field on Objects does not work when it has data. If the field is empty on an object it will return `null` as expected, but if there is some link content (text+url) then the server will throw an `UndefinedMethodException`.

## To reproduce

1. Create an object class.
2. Add the *Other: Link* data component.
3. Create an object of the class, but leave the link empty when saving.
4. Query for the object in GraphiQL, note the result.
5. Fill in some data in the object's link field and save it.
6. Run the query again, you should now get an error.

```
Attempted to call an undefined method named "resolveText" of class "Pimcore\Bundle\DataHubBundle\GraphQL\Resolver\Link"
```

## Question

Did [Geopoint](https://github.com/pimcore/data-hub/blob/master/src/GraphQL/Resolver/Geopoint.php) and [Link](https://github.com/pimcore/data-hub/blob/master/src/GraphQL/Resolver/Link.php) get mixed up? In that case I have [a commit here](https://github.com/pimcore/data-hub/commit/d4c5ffd8a940ef3d1c418fb2d98bd2a0add8e7ce) 😄

**Comment by weisswurstkanone** [comment]
Yeah, they got mixed up, don't know why :-)
