### ISSUE TITLE
The GraphQL schema does not return a Data Object field description

### ISSUE THREAD

**Issue by SimonBader** [pimcore/data-hub#230]
The GraphQL schema does not return a Data Object field description except of 'Calculated Value' which returns its tool-tip text (in /src/GraphQL/DataObjectQueryFieldConfigGenerator/CalculatedValue.getGraphQlFieldConfig line 43):
`'description' => $fieldDefinition->getTooltip()`

Is the any concept of what should be returned as Data Object field description in the GraphQL schema? In case it is the tool-tip I would then create a PR which extends all field descriptions by the tool-tip (there are a couple which do not provide any tooltip though like Field-Collections, 'Geographic Bounds', 'Geographic Polygon').

**Comment by weisswurstkanone** [comment]
I don't think that the tooltip (as a UI thing) is suitable for this.

**Comment by NiklasBr** [comment]
Well, the tooltip is pretty much the only thing available if you want to describe your data in Pimcore, so I would like it ;)

**Comment by weisswurstkanone** [comment]
Just one example ... for a slider: you will never use a tooltip to describe the min / max value because in the UI it is obvious to the user.

**Comment by NiklasBr** [comment]
Never claimed it was even close to the perfect field to use, just that it was the best, no it is in effect the *only* field available...

**Comment by SimonBader** [comment]
The proper solution would probably be to extend the data-hub 'Schema Definition' -> 'Query Schema / Mutation Schema' -> 'Entity' and 'Available Fields' mapping by a 'description' field. That seems like quite a bit of work to me.

**Comment by weisswurstkanone** [comment]
Not sure if we even need a description. Doing it with tooltips should be easy but I don't see a real use case.
@SimonBader what do you think? Which audience do you have in mind?

**Comment by SimonBader** [comment]
@weisswurstkanone In our case, the data objects which are exposed by the GraphQL API will not be edited manually. That means we would simply use the tooltip field for the API description: the only audience would be the developers consuming our GraphQL API.

**Comment by weisswurstkanone** [comment]
ok, then please go ahead 👍

**Comment by weisswurstkanone** [comment]
@SimonBader any progress ?

**Comment by SimonBader** [comment]
@weisswurstkanone No. This task is in our backlog but has not yet been given top priority.

**Comment by weisswurstkanone** [comment]
@SimonBader 🏓

**Comment by SimonBader** [comment]
Sorry @weisswurstkanone to not have answered before. I am no longer in the Pimcore business and therefore I am probably not the right person to implement that issue.

**Comment by weisswurstkanone** [comment]
@SimonBader Thanks a lot for your valuable discussion & input! I will close this for now but please reopen it at any time 👍
