### ISSUE TITLE
WYSIWYG data type returns NULL

### ISSUE THREAD

**Issue by romainbessugesmeusy** [pimcore/data-hub#234]
Hey,
Do you know how we can retrieve some html content from a WYSIWYG field? It seems to be returning null in our latest installation of Pimcore and Data-Hub. Thanks

**Comment by dvesh3** [comment]
works on demo..please share your exact versions!
![image](https://user-images.githubusercontent.com/5137917/83268063-61395d00-a1c5-11ea-878e-4dda59012c39.png)

**Comment by romainbessugesmeusy** [comment]
Sorry I didn't notice my field was under a LocalizedFields... So I needed to ask
 { review(language: "en") }
