### ISSUE TITLE
Uncaught TypeError When Accessing Datahub Config

### ISSUE THREAD

**Issue by AustinKobayashi** [pimcore/data-hub#241]
I receive the error "Uncaught TypeError: Cannot read property 'metaData' of null" when trying to access the Datahub Config window on a newly installed Databub Bundle running on the Pimcore skeleton project.

![image](https://user-images.githubusercontent.com/14931192/85794542-aa5cce00-b6eb-11ea-99a8-bba8ec363567.png)

The Datahub Config window is then stuck with the "Loading" icon and is not interactive 

![image](https://user-images.githubusercontent.com/14931192/85806455-ebf97300-b703-11ea-802f-208790c900f4.png)

I installed the bundle using the command:

`composer require pimcore/data-hub:dev-master`

Then enabled it, installed it, and clicked "Clear cache and reload" in the "Manage Extensions" tab.
 

Here is my composer.json

```
{
  "name": "pimcore/skeleton",
  "type": "project",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "require": {
    "php": ">=7.2",
    "pimcore/data-hub": "dev-master",
    "pimcore/pimcore": "~6.6.0",
    "wikimedia/composer-merge-plugin": "^1.4"
  },
  "require-dev": {
    "cache/integration-tests": "^0.16.0",
    "codeception/codeception": "~2.4.5"
  },
  "autoload": {
    "psr-4": {
      "": ["src/"],
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib"
    },
    "classmap": [
      "app/AppKernel.php"
    ]
  },
  "scripts": {
    "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
    "post-install-cmd": [
      "Pimcore\\Composer::postInstall",
      "@pimcore-scripts"
    ],
    "post-update-cmd": [
      "Pimcore\\Composer::postUpdate",
      "@pimcore-scripts",
      "Pimcore\\Composer::executeMigrationsUp",
      "@pimcore-scripts"
    ],
    "pimcore-scripts": [
      "Pimcore\\Composer::clearCache",
      "Pimcore\\Composer::installAssets"
    ]
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "merge-plugin": {
      "include": [
        "composer.local.json"
      ],
      "recurse": true,
      "replace": true,
      "merge-dev": true,
      "merge-extra": false,
      "merge-extra-deep": false,
      "merge-scripts": false
    }
  }
}

```

Has anyone else run into this?

**Comment by weisswurstkanone** [comment]
Anything special in the network panel ?

**Comment by AustinKobayashi** [comment]
Hey weisswurstkanone, thanks for getting back to me! I don't see the network panel as a tab in Pimcore, is it marked under a different name? For additional information, I'm running this on an ec2 T2.micro instance, although I'm not sure if that will make a difference.

**Comment by weisswurstkanone** [comment]
Screenshot is from the developer console, right? So there must be a network tab as well.

**Comment by AustinKobayashi** [comment]
Developer console network tab, my bad. Doesn't appear to be anything interesting

![image](https://user-images.githubusercontent.com/14931192/85843514-1d9b2a00-b756-11ea-9538-dfb758a6d10e.png)

**Comment by weisswurstkanone** [comment]
Everything fine in the response ?

**Comment by AustinKobayashi** [comment]
Response returns null, that is something interesting

![image](https://user-images.githubusercontent.com/14931192/85843708-66eb7980-b756-11ea-9d95-c735172043d0.png)

**Comment by weisswurstkanone** [comment]
I was able to reproduce it by deleting all configurations and then reentering ...

**Comment by AustinKobayashi** [comment]
I was wondering if another package may be a dependency, but from the readme I'm guessing not. Please let me know if I can provide any other information!

**Comment by weisswurstkanone** [comment]
fixed in 0.6.3

**Comment by AustinKobayashi** [comment]
Sorry, I'm relatively new to the Pimcore stack. Is there a command or way to update to 6.3?

**Comment by weisswurstkanone** [comment]
I am referring to the data-hub 0.6.3 release

https://github.com/pimcore/data-hub/releases/tag/v0.6.3

**Comment by AustinKobayashi** [comment]
I really appreciate the help @weisswurstkanone! I'm not super familiar with composer, could I update it with this command for example?

`composer require pimcore/data-hub:0.6.3`

**Comment by weisswurstkanone** [comment]
"composer update" should do it

**Comment by AustinKobayashi** [comment]
Great, I appreciate the help!
