### ISSUE TITLE
Create Data Object Variant

### ISSUE THREAD

**Issue by kobs123** [pimcore/data-hub#242]
Does Datahub have the functionality to create a data object variant with a mutation? I couldn't find anything about it in the documentation or the Documentation Explorer tab

**Comment by julmot** [comment]
Have you seen this?

https://github.com/pimcore/data-hub/blob/master/doc/graphl/Mutations.md#create-object

**Comment by weisswurstkanone** [comment]
I believe that there is currently no way to differentiate between regular object and variant as the o_type is not exposed in the column configurator (which I wouldn't do).

However, we could add this is as a argument somewhere around
https://github.com/pimcore/data-hub/blob/75c82dbcebe109c2f3437e46cd1e8bb5df59b5ec/src/GraphQL/Mutation/MutationType.php#L190

Can you create a PR for that please ?

**Comment by weisswurstkanone** [comment]
Already made the change

**Comment by kobs123** [comment]
Thanks!
