### ISSUE TITLE
Support sending apikey via headers in addition to sending it via query param

### ISSUE THREAD

**Issue by Iblis** [pimcore/data-hub#243]
We would like to send the apikey via header, using either 'X-API-Key' or 'apikey' as the header key.
I can provide a PR for that if the feature is accepted.

**Comment by weisswurstkanone** [comment]
I guess both ways should be supported.

**Comment by Iblis** [comment]
Yes, I wrote this in a confusing way and will correct it: Not instead, but in addition to query param

**Comment by fashxp** [comment]
but headers should be the preferred way (mentioned in docs etc)

**Comment by weisswurstkanone** [comment]
@Iblis can you add a note please

**Comment by weisswurstkanone** [comment]
@Iblis ping

**Comment by Iblis** [comment]
Hi there! Sorry, got swamped the last days. I am still eager to work on this, but won't happen the next days. @weisswurstkanone should I add/prepare something here already?

**Comment by weisswurstkanone** [comment]
Take your time! Thx :-)

**Comment by weisswurstkanone** [comment]
implemented in #252
