### ISSUE TITLE
Which directory do I run this in "composer require pimcore/data-hub:dev-master"

### ISSUE THREAD

**Issue by hellosmriti** [pimcore/data-hub#246]
I'm not able to understand where exactly this command should be executed?
**composer require pimcore/data-hub:dev-master**

Location is "C:\xampp\htdocs\pimcore" where pimcore is my project's name.

**Comment by weisswurstkanone** [comment]
Please consult the community forums for general questions:

https://gitter.im/pimcore/pimcore
https://talk.pimcore.org/
