### ISSUE TITLE
PimcoreDataHunBundle enabled but still not visible in /admin --> Settings 

### ISSUE THREAD

**Issue by hellosmriti** [pimcore/data-hub#247]
PimcoreDataHunBundle enabled under /admin --> Tools --> Bundles 

![image](https://user-images.githubusercontent.com/54179597/88041586-41d90380-cb68-11ea-86df-2e704d335f0b.png)

![image](https://user-images.githubusercontent.com/54179597/88040864-2b7e7800-cb67-11ea-9af7-21da56af6fea.png)

But it is still not visible under /admin --> Settings

<img width="239" alt="Untitled" src="https://user-images.githubusercontent.com/54179597/88041497-1f46ea80-cb68-11ea-8e85-b81f52ec4b41.png">

**Comment by dvesh3** [comment]
Probably discuss this topic in our forums https://talk.pimcore.org/ thanks!

**Comment by hellosmriti** [comment]
> Please discuss this topic in our forums https://talk.pimcore.org/ thanks!

I'm not able to raise it there.
