### ISSUE TITLE
Update- & Delete-Mutations (and references in relationships): allow path as an alternative to id for identifying object

### ISSUE THREAD

**Issue by Iblis** [pimcore/data-hub#248]
In our setup we have mutliple environments (test, perf, staging...) which have the same hierachy in regards to DataObjects, but have different internal pimcore Ids. 
We rather would like to use parent-path+key, as provided with the Create-Mutation to reference our objects through graphql (in addition to being able to use the id, of course).
This would of course also be true for references inside of the DataObject. e.g. in a many-to-many relation ship, being able to not only specify type and id, but also path.

Is this something desirable, or is there a reason that you only can use the objects id at the moment?

**Comment by julmot** [comment]
Would also be cool for documents, to be able to read documents based on path, when you don't know the ID (stage specific).

**Comment by Iblis** [comment]
I did a draft for the implementation here: https://github.com/Iblis/data-hub/tree/allow_object_path_for_update_and_delete
This does not include documents. Just wanted to see if I am on the right track here

**Comment by Iblis** [comment]
@weisswurstkanone any thought on that?

**Comment by weisswurstkanone** [comment]
We would have to discuss this internally. Could you please create a draft PR so we get an idea of your approach?
The ID has to stay the primary lookup approach. But I can think of a way to do the lookup via the fullpath if the pimcore id is not provided.

**Comment by weisswurstkanone** [comment]
To be consistent this should be possible also for all query types.

**Comment by Iblis** [comment]
I will create a PR and try to find the changes needed for all query types. Might need support there. 
My current implementation does exactly that: it checks for the fullpath if the id is not provided. maybe I should call it fullpath in the graphql schema to be consistent...

**Comment by weisswurstkanone** [comment]
Thanks a lot!
