### ISSUE TITLE
Cannot query Block field

### ISSUE THREAD

**Issue by SecretPocketCat** [pimcore/data-hub#253]
Saving a config that includes a block fields and then trying to query results in a 500

The config looks like this
![2020-07-31 16_17_37-pimcore westeurope cloudapp azure com __ Pimcore - Vivaldi](https://user-images.githubusercontent.com/17273703/89044184-ea961880-d349-11ea-98e9-76348a4ce273.png)  

Although after saving it's reduced to this (can no longer add subfields to the Block field)  
![2020-07-31 16_19_12-pimcore westeurope cloudapp azure com __ Pimcore - Vivaldi](https://user-images.githubusercontent.com/17273703/89044282-06012380-d34a-11ea-82fc-f41e4ccb37e7.png)  

Then switching to GraphiQL throws a 500 (the full response is in the attached zip)
![2020-07-31 16_22_42-Reporty - Outlook](https://user-images.githubusercontent.com/17273703/89044455-4660a180-d34a-11ea-88f6-e1eedc6637da.png)

[datahub_block_graphiql_500.zip](https://github.com/pimcore/data-hub/files/5007516/datahub_block_graphiql_500.zip)

**Comment by weisswurstkanone** [comment]
@dpfaffenbauer since you are the creator of this ... could you have a look please ?

**Comment by weisswurstkanone** [comment]
@SecretPocketCat , I think you should not add subfields to the block. You can only add the entire block to the schema.
I know this is possible but there is currently no way to prevent this in the UI as this is code borrowed from the core. This needs to be improved.
I think we could at least this catch this on the server side (on save) for now.

Related discussion: https://github.com/pimcore/data-hub/pull/232#issuecomment-641351072

**Comment by SecretPocketCat** [comment]
@weisswurstkanone Thanks, I've tried that, but I'm currently getting just a non-specific 500 when there's block (either the invalid way as in the OP or just adding the block as you've suggested). (If I remove the block from the definition, graphiql loads correctly).

The only thing I found in the dev.log was
`[2020-08-04 08:35:32] php.INFO: User Deprecated: Referencing controllers with PimcoreDataHubBundle:GraphQLExplorer:explorer is deprecated since Symfony 4.1, use "Pimcore\Bundle\DataHubBundle\Controller\GraphQLExplorerController::explorerAction" instead. {"exception":"[object] (ErrorException(code: 0): User Deprecated: Referencing controllers with PimcoreDataHubBundle:GraphQLExplorer:explorer is deprecated since Symfony 4.1, use \"Pimcore\\Bundle\\DataHubBundle\\Controller\\GraphQLExplorerController::explorerAction\" instead. at /var/pimcore/vendor/symfony/symfony/src/Symfony/Bundle/FrameworkBundle/Routing/DelegatingLoader.php:108)"} []`

Should I be looking for something specific in the logs (We're on PIM 6.6.10)?

**Comment by weisswurstkanone** [comment]
Thanks for the log, we will put it on our list :-)

**Comment by weisswurstkanone** [comment]
Unable to reproduce on pimcore.demo.fun

![image](https://user-images.githubusercontent.com/6142086/89400650-7a561100-d714-11ea-8168-da5f05e80eec.png)

![image](https://user-images.githubusercontent.com/6142086/89400682-87730000-d714-11ea-9b35-bbbce8f2e444.png)

![image](https://user-images.githubusercontent.com/6142086/89400759-9f4a8400-d714-11ea-9422-40eec0b29a9c.png)

![image](https://user-images.githubusercontent.com/6142086/89400802-affafa00-d714-11ea-9536-722850bf3ede.png)

**Comment by SecretPocketCat** [comment]
We've tried removing datahub from deps, running composer, then adding it back and rerunning it, but we're still getting a non-specific 500 when we open graphiql with a configuration that contains a Block field (a request to _/pimcore-graphql-webservices/data-test-contest?apikey=xyz_).  

Any pointers where should we look to drill down the 500?

**Comment by SecretPocketCat** [comment]
@weisswurstkanone @dpfaffenbauer 

I went through the logs once again and it seems like it breaks when fields are nested in layout components within the block. I could repro that on the demo instance. Removing the layout component resolved the issue.  
_(I wanted to attach a screenshot and mess around a bit more, but the test instance is currently returning a 500, I assume it's getting updated)._

Here are the stacks for the unhandled exceptions (initial request I mentioned and also trying to run a query):  
> [2020-08-13 15:20:35] php.CRITICAL: Uncaught Error: Argument 1 passed to Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper::supportsGraphQL() must be an instance of Pimcore\Model\DataObject\ClassDefinition\Data, instance of Pimcore\Model\DataObject\ClassDefinition\Layout\Panel given, called in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php on line 109 {"exception":"[object] (TypeError(code: 0): Argument 1 passed to Pimcore\\Bundle\\DataHubBundle\\GraphQL\\FieldHelper\\DataObjectFieldHelper::supportsGraphQL() must be an instance of Pimcore\\Model\\DataObject\\ClassDefinition\\Data, instance of Pimcore\\Model\\DataObject\\ClassDefinition\\Layout\\Panel given, called in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php on line 109 at /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php:200)"} []
> [2020-08-13 15:20:35] request.CRITICAL: Uncaught PHP Exception TypeError: "Argument 1 passed to Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper::supportsGraphQL() must be an instance of Pimcore\Model\DataObject\ClassDefinition\Data, instance of Pimcore\Model\DataObject\ClassDefinition\Layout\Panel given, called in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php on line 109" at /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php line 200 {"exception":"[object] (Symfony\\Component\\Debug\\Exception\\FatalThrowableError(code: 0): Argument 1 passed to Pimcore\\Bundle\\DataHubBundle\\GraphQL\\FieldHelper\\DataObjectFieldHelper::supportsGraphQL() must be an instance of Pimcore\\Model\\DataObject\\ClassDefinition\\Data, instance of Pimcore\\Model\\DataObject\\ClassDefinition\\Layout\\Panel given, called in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php on line 109 at /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php:200)"} []
> [2020-08-13 15:20:35] app.ERROR: Symfony\Component\Debug\Exception\FatalThrowableError: Argument 1 passed to Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper::supportsGraphQL() must be an instance of Pimcore\Model\DataObject\ClassDefinition\Data, instance of Pimcore\Model\DataObject\ClassDefinition\Layout\Panel given, called in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php on line 109 in /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php:200 Stack trace: #0 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php(109): Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper->supportsGraphQL(Object(Pimcore\Model\DataObject\ClassDefinition\Layout\Panel), 'query') #1 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/BlockEntryType.php(62): Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\BlockEntryType->build(Array) #2 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectQueryFieldConfigGenerator/Block.php(58): Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\BlockEntryType->__construct(Object(Pimcore\Bundle\DataHubBundle\GraphQL\Service), Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), Object(Pimcore\Model\DataObject\ClassDefinition), Array) #3 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectQueryFieldConfigGenerator/Block.php(44): Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectQueryFieldConfigGenerator\Block->getFieldType(Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), Object(Pimcore\Model\DataObject\ClassDefinition), NULL) #4 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/Service.php(230): Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectQueryFieldConfigGenerator\Block->getGraphQlFieldConfig('Prizes', Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), Object(Pimcore\Model\DataObject\ClassDefinition), NULL) #5 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php(225): Pimcore\Bundle\DataHubBundle\GraphQL\Service->buildDataObjectQueryDataConfig('Prizes', 'block', Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), Object(Pimcore\Model\DataObject\ClassDefinition), NULL) #6 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/FieldHelper/DataObjectFieldHelper.php(113): Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper->getGraphQlQueryFieldConfig('Prizes', Object(Pimcore\Model\DataObject\ClassDefinition\Data\Block), Object(Pimcore\Model\DataObject\ClassDefinition), NULL) #7 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/DataObjectType/PimcoreObjectType.php(158): Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper->getQueryFieldConfigFromConfig(Array, Object(Pimcore\Model\DataObject\ClassDefinition)) #8 /var/pimcore/vendor/pimcore/data-hub/src/GraphQL/ClassTypeDefinitions.php(54): Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectType\PimcoreObjectType->build(Array) #9 /var/pimcore/vendor/pimcore/data-hub/src/Controller/WebserviceController.php(96): Pimcore\Bundle\DataHubBundle\GraphQL\ClassTypeDefinitions::build(Object(Pimcore\Bundle\DataHubBundle\GraphQL\Service), Array) #10 /var/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(158): Pimcore\Bundle\DataHubBundle\Controller\WebserviceController->webonyxAction(Object(Pimcore\Bundle\DataHubBundle\GraphQL\Service), Object(Pimcore\Localization\LocaleService), Object(Pimcore\Model\Factory), Object(Symfony\Component\HttpFoundation\Request)) #11 /var/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/HttpKernel.php(80): Symfony\Component\HttpKernel\HttpKernel->handleRaw(Object(Symfony\Component\HttpFoundation\Request), 1) #12 /var/pimcore/vendor/symfony/symfony/src/Symfony/Component/HttpKernel/Kernel.php(201): Symfony\Component\HttpKernel\HttpKernel->handle(Object(Symfony\Component\HttpFoundation\Request), 1, true) #13 /var/pimcore/web/app.php(36): Symfony\Component\HttpKernel\Kernel->handle(Object(Symfony\Component\HttpFoundation\Request)) #14 {main} [] []
