### ISSUE TITLE
GraphQL return cannot resolve parent when creating asset

### ISSUE THREAD

**Issue by MeowNekko** [pimcore/data-hub#255]
`mutation CreateAsset($filename: String!, $parentId: Int, $type: String!, $input: AssetInput) {
  createAsset(filename: $filename, parentId: $parentId, type: $type, input: $input) {
    success
    message
  }
}
`

Query variables:

`{
    "filename": "file_name2.jpg",
    "parentId": 409,
    "type": "image",
    "input": {
        "filename": "file_name2.jpg",
        "parentId": 409,
        "data": "iVBORw0KGgoAAAANSUhEUgAAABIAAAAUCAYAAACAl21KAAAABHNCSVQICAgIfAhkiAAAABl0RVh0U29mdHdhcmUAZ25vbWUtc2NyZWVuc2hvdO8Dvz4AAAAuaVRYdENyZWF0aW9uIFRpbWUAAAAAANCf0YIgMDMg0LjRjtC7IDIwMjAgMTE6MDQ6NDfn56P4AAAAjUlEQVQ4je3PIQ7CQBRF0cuHkC4HRNkDuNlCdfGEdaARtV1KTSUCOymaNgRIOh/XBcx8R98CTt5dqKoChM4zFA4demImANo/eZ3LaGSCPnXFeL9FIwASOs+3rpIQAHlfL0lJEzS2TTICIOHhbSATZYb+HlpuchtovXdG0MFh8UoAsqK0gVbbHdnxlAT9AMZiK9uEjP2GAAAAAElFTkSuQmCC"
    }
}`

Error on 502 line in file \Pimcore\Bundle\DataHubBundle\GraphQL\Mutation\MutationType::buildCreateAssetMutation

To solve this problem you need to do the following

Replace it:
`if (isset($args["parentId"])) {
    $parent = AbstractObject::getById($args["parentId"]);
} else if (isset($args["path"])) {
    $parent = AbstractObject::getByPath($args["path"]);
}`

On this: 
`if (isset($args["parentId"])) {
    $parent = Asset::getById($args["parentId"]);
} else if (isset($args["path"])) {
    $parent = Asset::getByPath($args["path"]);
}`

**Comment by weisswurstkanone** [comment]
thx!
