### ISSUE TITLE
Support output cache in GraphQL API

### ISSUE THREAD

**Issue by nagarciah** [pimcore/data-hub#272]
We would like to improve performance on recurring GraphQL queries by caching responses in a similar fashion to the [full page cache](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Cache/Full_Page_Cache.html) used by the UI (only for GET requests), following this [example](https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Cache/index.html#page_Using-the-Cache-for-your-Application).

A first attempt to do it can be found [here](https://github.com/Verivox/data-hub/compare/release...Verivox:provide_response_cache#diff-710eda3bd131def4ad5d8ab1f1cfc3d5)

**Comment by julmot** [comment]
Duplicate of #273

**Comment by nagarciah** [comment]
Duplicate of #273
