### ISSUE TITLE
GraphQL translation of multiselects

### ISSUE THREAD

**Issue by moritzdingerheraeus** [pimcore/data-hub#276]
## Expected behavior

When adding a multi-select within a "Translate value" Transformator in the GraphQL schema definition each selected value should be translated individually and concatenated with a comma again.

## Actual behavior

The interface / Transformator returns the value "Array" for all selections. This term can be translated but this isn't useful.

## Test

1. Create a class with a multi-select
2. Add the multi-select field to a GraphQL schema definition within a "Translate value" Transformator.
3. Query the interface.

**Comment by weisswurstkanone** [comment]
Note that you will still have to wrap the translate operator into a concatenator because the translate operator.

![image](https://user-images.githubusercontent.com/6142086/96587425-99f7e100-12e2-11eb-902c-b225555e6534.png)

**Comment by moritzdingerheraeus** [comment]
Huge thanks for the quick fix @weisswurstkanone
