### ISSUE TITLE
How to disallow request on unpublished Objects

### ISSUE THREAD

**Issue by mugge6** [pimcore/data-hub#285]
If you're requesting objects via GraphQL from a Frontend Application via the `get<ObjectName>(id: 4)` then the Object will be returned independent from the published status of the object. With a little programmer knowledge every one is able to request unpublished object data based on the request data visible in the browser console, with guessing the the object IDs.

For example: With this approach everyone can request new unpublished products from a product detail page as soon as he has at least one GraphQL request.

What is the best approach to avoid this sort of reverse engineering from a data dataset?

**Comment by julmot** [comment]
One thing to note here: The `published` option that is available in listing queries is also defined client-side, which makes manipulable  to fetch data that is not intended to be public.

For the mentioned `get<ObjectName>(id: 4)` there's not even a way to specifiy a `published` filter client-side.

**Comment by weisswurstkanone** [comment]
Would https://github.com/pimcore/data-hub/issues/226 be an option? The one view on this is about manipulating data and the other thing is fetch and render stuff. We have to combine both worlds :-) And probably in real life you need both.

**Comment by weisswurstkanone** [comment]
@mugge6 ping

**Comment by weisswurstkanone** [comment]
closed due to inactivity
