### ISSUE TITLE
Provide complete steps to configure new datatype to old version

### ISSUE THREAD

**Issue by rajesh17692** [pimcore/data-hub#286]
Hi please mention steps here so that we can use the new data type with the existing version of pimcore graphql 

I tried to use the new fieldcollection datatype but facing an issue in configuring in old please provide all the steps here like

Where in our bundle we can add fieldcollection file 
Where all the configuration needs to be added  

My steps:-

1 added below file in my Bundle

namespace MyBundle\GraphQL;

use GraphQL\Type\Definition\InputObjectType;
use GraphQL\Type\Definition\Type;
use Pimcore\Bundle\DataHubBundle\GraphQL\FieldHelper\DataObjectFieldHelper;
use Pimcore\Model\Asset\MetaData\ClassDefinition\Data\Data;
use Pimcore\Model\DataObject\ClassDefinition\Data\Localizedfields;
use Pimcore\Model\DataObject\Fieldcollection\Definition;

class Fieldcollections extends Base
{
}

2 Added below lines in my service.yml file but not worked

pimcore.datahub.graphql.dataobjectquerytypegenerator_datatype_fieldcollections:
        class: Pimcore\Bundle\DataHubBundle\GraphQL\DataObjectQueryFieldConfigGenerator\Base
        tags:
            - { name: pimcore.datahub.graphql.dataobjectquerytypegenerator, id: typegenerator_dataobjectquerydatatype_fieldcollections }

    pimcore.datahub.graphql.dataobjectmutationtypegenerator_datatype_fieldcollections:
        class: MyBundle\GraphQL\Fieldcollections
        tags:
            - { name: pimcore.datahub.graphql.dataobjectmutationtypegenerator, id: typegenerator_dataobjectmutationdatatype_fieldcollections }

but not worked for me please guide what I am missing.

**Comment by rajesh17692** [comment]
Please help in this issue

**Comment by brusch** [comment]
Please be patient, we'll care about your issue report as soon as we can.

**Comment by weisswurstkanone** [comment]
Not sure if I can follow you. Why not just update the bundle? See #168

**Comment by rajesh17692** [comment]
Facing issue while upgrading bundle See #287

**Comment by rajesh17692** [comment]
> Not sure if I can follow you. Why not just update the bundle? See #168

Facing issue while upgrading bundle See #287

**Comment by weisswurstkanone** [comment]
Hi @rajesh17692, minimum requirements have been changed to "pimcore/pimcore": "^6.8".
Please update your dependencies accordingly.

See https://github.com/pimcore/data-hub/blob/bb30fde641b28e0474f5e44dcf9d650a28b1a743/composer.json#L18

Thanks a lot!
