### ISSUE TITLE
Pimcore breaks after update

### ISSUE THREAD

**Issue by rajesh17692** [pimcore/data-hub#287]
I run the below command in my pimcore 6.4
COMPOSER_MEMORY_LIMIT=-1 composer update pimcore/data-hub
after executing the above command I am getting below error and PIM stopped working
![image](https://user-images.githubusercontent.com/32155962/98443392-fc4d4000-2130-11eb-837d-031860496283.png)
![image](https://user-images.githubusercontent.com/32155962/98442969-54cf0e00-212e-11eb-9807-e1f17db5d50b.png)
![image](https://user-images.githubusercontent.com/32155962/98442978-644e5700-212e-11eb-973b-f378de5b3e20.png)

**Comment by brusch** [comment]
Do not use `dev-master` with Pimcore v6 as this is already for v7.

**Comment by rajesh17692** [comment]
Then which version I can use

**Comment by brusch** [comment]
Maybe one of the officially tagged releases?

**Comment by rajesh17692** [comment]
Will you please provide details on Issue #286 what I am missing as the complete process is not available so I tried in My way but failing to achieve cutomeType

**Comment by brusch** [comment]
https://talk.pimcore.org/
https://gitter.im/pimcore/pimcore

**Comment by rajesh17692** [comment]
Answers are not available there if you can just check issue #286  and reply over there what I am missing that will be good enough

**Comment by rajesh17692** [comment]
> Maybe one of the officially tagged releases?

will you provide actually it's showing 0.6.3 and 5.8 which one is correct?
![image](https://user-images.githubusercontent.com/32155962/98556953-9ea02b80-22c9-11eb-874f-ad2def79ed4f.png)

**Comment by brusch** [comment]
Stable versions are not suffixed by `-dev`.
