### ISSUE TITLE
Support ObjectBricks in filters

### ISSUE THREAD

**Issue by AntonBauer** [pimcore/data-hub#294]
Hello,

I have objects that consists out of ObjectBricks and I want to filter them by properties, defined in these bricks. But I get an error like "Column not found: unknown column in where clause". I double checked property names and filter clause, the same filter works fine if property is defined direct in Object.
Or maybe there is a way to do it (even dirty hacks are welcome), then I would appreciate if someone shares a link to it.

Thanks in advance,
Anton

**Comment by weisswurstkanone** [comment]
Hi @AntonBauer , can you provide a sample query. Steps to reproduce on the demo.pimcore.fun instance would be perfect!

**Comment by AntonBauer** [comment]
Hi @weisswurstkanone, thanks for reply. In demo.pimcore.fun I added datahub config "issue_294", it is minimal infrastructure to reproduce issue. There is query to reproduce:
`{
  getCarListing(filter: "{\"numberOfDoors\": 2}") {
    totalCount,
    edges {
      node {
        id,
        name,
        numberOfDoors
      }
    }
  }
}`

Field _name_ is defined in **Car** class and field _numberOfDoors_ is defined in **BodyworkColumns** brick. I can filter cars by _name_, but filter by _numberOfDoors_ throws an error.

![BrickProp](https://user-images.githubusercontent.com/31994812/100755203-376b2800-33ec-11eb-8574-783189165226.jpg)
![Config](https://user-images.githubusercontent.com/31994812/100755206-389c5500-33ec-11eb-819c-f34bdf9aded1.jpg)
![NoFilter](https://user-images.githubusercontent.com/31994812/100755211-39cd8200-33ec-11eb-8819-1beb48aaed24.jpg)
![OwnProp](https://user-images.githubusercontent.com/31994812/100755216-3a661880-33ec-11eb-8fbd-a7b4bd4fbebc.jpg)
![Schema](https://user-images.githubusercontent.com/31994812/100755218-3afeaf00-33ec-11eb-9fc7-dcafca6e3dfd.jpg)

**Comment by weisswurstkanone** [comment]
@AntonBauer could you please double check the latest change. Thanks a lot!

**Comment by AntonBauer** [comment]
@weisswurstkanone Many thanks for rapid fix!
How can I check this? Should I install fresh version of DataHub in my environment or will this fix be available soon in demo.pimcore.fun?

**Comment by AntonBauer** [comment]
@weisswurstkanone Many thanks for rapid fix!
How can I check this? Should I install fresh version of DataHub in my environment or will this fix be available soon in demo.pimcore.fun?

**Comment by weisswurstkanone** [comment]
You can test it on demo.pimcore.fun already.

**Comment by AntonBauer** [comment]
@weisswurstkanone Yep, it works as expected, thanks a lot!
