### ISSUE TITLE
GraphQl (DataHub) Elasticseach(advenced-object-search) integration

### ISSUE THREAD

**Issue by not4fame** [pimcore/data-hub#296]
Feature Request

I would like to ask about the possible integration of Your graphQl solution (DataHub) with Elasticsearch (advanced object search). Some time ago I joined Your discussion regarding graphQl topic, and even came out with my own solution, the reason that I stoped, was that in my opinion (and also clients for which I propose this solution) it does not make too much sense to do it on top of mysql. When someone wants to use graphQl, it's usually because of the performance issues, and (at least in my approach) first solution for that is elasticsearch integration. Please, if You can, share Your thoughts on this topic. Are You considering integrating DataHub with  advanced object search ?

**Comment by fashxp** [comment]
there is something similar with https://pimcore.com/docs/platform/Datahub_Simple_Rest/
