### ISSUE TITLE
[Config] Add workspace config to php-file too + add command to rebuild database workspace entries

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#3]

**Comment by weisswurstkanone** [comment]
Part 1 is done.
How do you want to handle the import?
- overwrite all workspace settings?
- only specific ones ?
- merge them maybe ?

**Comment by fashxp** [comment]
I would say, config file is master and only source of workspaces. db tables are just more like a search index. 
therefore command should overwrite all workspace settings.
