### ISSUE TITLE
PIMCore v6.8.6 GraphQl query not accepting variables

### ISSUE THREAD

**Issue by Dinesh2703** [pimcore/data-hub#304]
I passed culture = "hi" variable in graphql query in PIMCore v6.7.1 and I got the data in "hi" culture. as shown in image below.

![pimv6 7 1](https://user-images.githubusercontent.com/41935464/103901141-c4597d80-511e-11eb-9037-acccb7b45b77.png)

In PIMCore v6.8.6 I did the same but did not get data in "hi" culture as shown in image below.
![pimv6 8 6](https://user-images.githubusercontent.com/41935464/103901261-e9e68700-511e-11eb-9421-282ac13a3f14.jpg)

You can aslo check the the video.

https://user-images.githubusercontent.com/41935464/103901325-02ef3800-511f-11eb-98ec-60a017ed105f.mp4

Please point out any mistake i did or any settings I could have missed. Or this might be a Bug in PIMCore v6.8.6.

Thanks

**Comment by weisswurstkanone** [comment]
This is a regression of https://github.com/pimcore/data-hub/pull/297. Partly reverted it.
@juckerf could you please double-check your change. $variableValues seems to be null after the event but was correctly set before.

**Comment by weisswurstkanone** [comment]
@juckerf 🏓

**Comment by juckerf** [comment]
sounds strange, i'll have a look at it

**Comment by juckerf** [comment]
unfortunately I'm not able to reproduce the issue (pimcore: 6.8.6, symfony: v4.4.16)
