### ISSUE TITLE
Link data type advanced attributes support for DataObjects

### ISSUE THREAD

**Issue by do-web** [pimcore/data-hub#305]
I cannot access advanced attributes in graphql for data objects.

**Comment by weisswurstkanone** [comment]
can you give a detailed example?

**Comment by do-web** [comment]
Its the same as #275 but for DataObjects

**Comment by weisswurstkanone** [comment]
I see, could you provide a PR please? Starting point would be https://github.com/pimcore/data-hub/blob/c41a1f0e294d1ae972a335c2fba00d51945fc266/src/GraphQL/DataObjectType/LinkType.php#L28

**Comment by weisswurstkanone** [comment]
@do-web 🏓 a PR would we very nice

**Comment by weisswurstkanone** [comment]
@do-web ping 🏓

**Comment by weisswurstkanone** [comment]
@do-web closed due to inactivity for now
