### ISSUE TITLE
Blocks in Blocks not working in GraphQL

### ISSUE THREAD

**Issue by do-web** [pimcore/data-hub#307]
Subitems not returned in the graphql result:

![Bildschirmfoto 2021-01-13 um 14 23 12](https://user-images.githubusercontent.com/862783/104458041-1b41d580-55ab-11eb-84cd-fc4fd70a7c12.jpg)
![Bildschirmfoto 2021-01-13 um 14 22 18](https://user-images.githubusercontent.com/862783/104458044-1d0b9900-55ab-11eb-9598-cdde9e1a454f.jpg)

**Comment by weisswurstkanone** [comment]
This is currently not supported in general. See https://github.com/pimcore/pimcore/issues/6319#issuecomment-621645271 for more infos. Because of that I will close this thread for now. Please continue the discussion at https://github.com/pimcore/pimcore/issues/6319
