### ISSUE TITLE
Access denied when Open Iframe of Datahub

### ISSUE THREAD

**Issue by SamuelHafner** [pimcore/data-hub#310]
I get an Access denied when I want to access to Iframe in Datahub für GraphQL

**Comment by weisswurstkanone** [comment]
Sorry, unable to reproduce on our official demo. Mut be specific to your instance.

![image](https://user-images.githubusercontent.com/6142086/106777079-f3431080-6644-11eb-8d82-553c161643ae.png)

**Comment by weisswurstkanone** [comment]
Please consult the forum instead
https://gitter.im/pimcore/pimcore
