### ISSUE TITLE
Can´t access assetData in createAsset mutation

### ISSUE THREAD

**Issue by Macaruja** [pimcore/data-hub#327]
Hello, I have the following problem on pimcore demo and self hosted.
I cannot access AssetData in the createAsset mutation. AssetData in Reponse is null.

**Request**
```graphql
mutation {
  createAsset(
    filename: "test.png", 
    input: {data: "", filename: "test.png", parentId: 410}, 
    parentId: 410, type: "Image") {
    assetData {
      id
      creationDate
    }
    message
    success
  }
}
```

**Response**
```graphql
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 6,
          "column": 5
        }
      ],
      "path": [
        "createAsset",
        "assetData"
      ]
    }
  ],
  "data": {
    "createAsset": {
      "assetData": null,
      "message": "asset created: 415",
      "success": true
    }
  }
}
```

Asset and Asset Folder are in the configuration with Create Read Update and Delete.
![image](https://user-images.githubusercontent.com/40568748/110441781-6ca5a700-80ba-11eb-984f-403ace0b1f59.png)

The asset folder is located in the Datahub Configuration with Create Read Update and Delete.
![image](https://user-images.githubusercontent.com/40568748/110441341-f608a980-80b9-11eb-8a7b-97046925c2bc.png)

Thanks in advance! Have a nice day

**Comment by weisswurstkanone** [comment]
Unable to reproduce on demo.pimcore.fun

My query: had to change the parent to 1 since 410 does not exist on demo.

![image](https://user-images.githubusercontent.com/6142086/110456075-71be2280-80c9-11eb-95ab-e08f731c81e3.png)

**Comment by Macaruja** [comment]
I have reproduced the error on demo.pimcore.com

On demo.pimcore.fun I do not have permission to allow create asset, in the assets configuration.
![image](https://user-images.githubusercontent.com/40568748/110469722-47289580-80da-11eb-84b4-a6875ea1f9a6.png)

**Comment by Dirndorfer** [comment]
Did you click the Save button, or do you have the asterisk next to configuration name? 
You have the small red corner for create Asset in your screenshot, which indicates it has just changed, I think.

**Comment by Macaruja** [comment]
@Dirndorfer 
Yes I have saved the configuration.
Creating the asset worked, it took the changes in the configuration.
However, assetData remains null.

**Comment by Macaruja** [comment]
Tried it again with a pimcore/skeleton + datahub and it worked.
But I can not explain why the error occurred with the pimcore/demo.
![image](https://user-images.githubusercontent.com/40568748/111326634-ff22e900-866c-11eb-9383-b0b0a73707dc.png)
