### ISSUE TITLE
Re: Support ObjectBricks in filters

### ISSUE THREAD

**Issue by CallLenka** [pimcore/data-hub#329]
Hello,

Some time ago you've fixed the issue - #294 
But seems like it's back again, we're not able to filter Data Objects by fields from ObjectBricks.
Could you please take a look at this one more time?

In order to reproduce the issue please use demo site and "products" Datahub Config with 2 following queries:
1. Working query with filter by simple Data Object field (not from ObjectBricks)
```
{
  getCarListing(filter: "{\"name\": \"E-Type\"}") {
    edges {
      node {
        name,
        numberOfDoors
      }
    }
  }
}

```
![image](https://user-images.githubusercontent.com/11856888/111302627-5076ac80-865c-11eb-84fb-9212859915cd.png)

2. Not working query with filter by field from ObjectBricks 
```
{
  getCarListing(filter: "{\"numberOfDoors\": 2}") {
    edges {
      node {
        name,
        numberOfDoors
      }
    }
  }
}
```

![image](https://user-images.githubusercontent.com/11856888/111302728-6b492100-865c-11eb-8248-d3ef2fead736.png)

**Comment by weisswurstkanone** [comment]
works perfectly fine

![image](https://user-images.githubusercontent.com/6142086/111304366-eeb34400-8655-11eb-9ea5-5029e97ecff5.png)

**Comment by CallLenka** [comment]
Ah, my bad, now i noticed that we're checking different demo sites. The issue I've described is from demo.pimcore.com.

Sorry for this, I'm closing the issue
