### ISSUE TITLE
Implementation of advancedManyToManyObjectRelation mutation

### ISSUE THREAD

**Issue by brainsbucket** [pimcore/data-hub#343]
Hi,

My customer need the advancedManyToManyObjectRelation mutation.

Please, can you tell me when this feature will be implemented ?

Thanks

**Comment by weisswurstkanone** [comment]
why do you think it is not supported ?

**Comment by weisswurstkanone** [comment]
@brainsbucket 🏓

**Comment by HeicoSindel** [comment]
@weisswurstkanone - so... is it supported? does it works in the same way as non-advanced? just as an array with id and type (object, asset, document)?

**Comment by HeicoSindel** [comment]
![image](https://user-images.githubusercontent.com/74646710/132030505-b825be73-e7c5-437f-8b51-f1c9321d5409.png)

**Comment by dvesh3** [comment]
Hi @HeicoSindel, this is not supported yet. We are happy to receive a PR for this feature 😉 https://github.com/pimcore/data-hub/issues/160
