### ISSUE TITLE
Unable to query on ReverseObjectRelation fields

### ISSUE THREAD

**Issue by MarcoGuiducci** [pimcore/data-hub#348]
After having updated my Pimcore project to the 6.9 version, I'm not able to query on ReverseObjectRelation fields anymore.

### Expected behavior

Expected to query a ReverseObjectRelation field like in the previous versions of Pimcore.

### Actual behavior

When I try to add a ReverseObjectRelation field in the schema definition, I've got the following error
![DataHub ReverseObjectRelation](https://user-images.githubusercontent.com/36894331/117001901-31eb7400-ace3-11eb-9dfe-c0fc5675b48b.png)

### Steps to reproduce
- Open the "products" configuration of the Pimcore demo DataHub.
- In the Schema Definition, open the settings of the "Category" class
- Double click on the "cars" field to add to the exportable fields
- you should get the previously described error

I've noted that changing the "fieldtype" variable of the "Pimcore\Model\DataObject\ClassDefinition\Data\ReverseObjectRelation" to "reverseManyToManyObjectRelation" solves the issue, but obviously it's not the correct way to act.

**Comment by weisswurstkanone** [comment]
due to https://github.com/pimcore/pimcore/pull/8037
Since we have to support both 6.9 and 10 a PR will follow

**Comment by weisswurstkanone** [comment]
@MarcoGuiducci could you please confirm that https://github.com/pimcore/data-hub/pull/349 works for you? Thx!

**Comment by MarcoGuiducci** [comment]
@weisswurstkanone it seems to work as expected!

**Comment by weisswurstkanone** [comment]
Thanks for testing!
