### ISSUE TITLE
Image.php denormalize

### ISSUE THREAD

**Issue by dominikager** [pimcore/data-hub#354]
Hi,

the denormalize function in the Image.php Class gets as value "null".

This only happens when i upload a new Image or clear the pimcore cache

![image](https://user-images.githubusercontent.com/23102887/117832979-3fba6f80-b276-11eb-9313-5ea24c64f77a.png)

**Comment by weisswurstkanone** [comment]
@dominikager may I ask you for a sample for the request (the left side), not the response. thx a lot!

**Comment by dominikager** [comment]
@weisswurstkanone this comes directly when you open GraphiQL from the Datahub
There is no GraphiQL request with some query.

**Comment by weisswurstkanone** [comment]
sorry, not able to reproduce on demo.pimcore.fun
