### ISSUE TITLE
DataHub ignores translation parameter when querying for classification store

### ISSUE THREAD

**Issue by AlekMosingiewicz** [pimcore/data-hub#355]
When querying for classification store data, our endpoint completely ignored the "language" parameter. Is it a bug in the module itself or was something wrong with the configuration?

**Comment by weisswurstkanone** [comment]
Sounds like a bug. Can investigate this further please.

**Comment by weisswurstkanone** [comment]
Unable to reproduce.

Query looks like

```
{
  getCstest(id: 1128, defaultLanguage: "en") {
    id
    csfield(language:"de") {
      name
      features {
        __typename
        ... on csFeatureInput {
          name
          text
        }
      }
    }
  }
}
```

Result is:
```
{
  "data": {
    "getCstest": {
      "id": "1128",
      "csfield": [
        {
          "name": "group1",
          "features": [
            {
              "__typename": "csFeatureInput",
              "name": "key1",
              "text": "de"
            }
          ]
        }
      ]
    }
  }
}
```

Data looks like:

![image](https://user-images.githubusercontent.com/6142086/118820711-cf839d80-b8b6-11eb-934b-075ed70c8887.png)

**Comment by weisswurstkanone** [comment]
@AlekMosingiewicz 🏓

**Comment by weisswurstkanone** [comment]
closed due to inactivity

**Comment by AlekMosingiewicz** [comment]
Seems the problem is somewhere with the configuration of our environment, I think we can close it for now.
