### ISSUE TITLE
Proposal: support retrieving an older version of an object

### ISSUE THREAD

**Issue by fhulleman** [pimcore/data-hub#360]
Hi guys,

A customer of mine has an interesting use case: another external application knows which previous versions exist for a certain product (Pimcore object class), and when a customer order is placed, there is a relation between that order and a specific version of the product. The reason why, is because when a customer has a question about this order, they can look up the product content when the customer purchased that product.

We do this by exposing the object version ID from Pimcore to this external application. 

So now, we need to be able to retrieve the content of that older version, using graphql. 

So why not support something like:
`{
  getProduct(id: 1105, versionId: 103) {
    title
  }
}`

In case this will not be included in the Datahub, what would be a good generic approach to solve this for this specific project, without having to build a full custom query.

**Comment by weisswurstkanone** [comment]
Sounds like a nice addition. Could you provide a PR (for all element types, not just objects)

**Comment by weisswurstkanone** [comment]
@fhulleman 🏓

**Comment by weisswurstkanone** [comment]
@fhulleman 🏓 excited about your feedback. thx!

**Comment by weisswurstkanone** [comment]
Closed due to inactivity.
