### ISSUE TITLE
document_editableBlock :- getting _editableType and _editableName value null

### ISSUE THREAD

**Issue by archana-multi-concept** [pimcore/data-hub#364]
Hello Team,

When I run getDocument query, it return all value of all editable except **document_editableBlock** _editableType and _editableName.

**Input Query**
...on document_editableBlock{
          _editableName
          _editableType
          indices
        }

**Output**
{
"__typename": "document_editableBlock",
  "_editableName": null,
  "_editableType": null,
  "indices": [
    1
  ]
},

Please find gist attachment for reference.
[https://gist.github.com/archana-multi-concept/9fee182102909ab3f47fe0c309777bcf](https://gist.github.com/archana-multi-concept/9ded434f397ff354292dfd726ab2bc87)
[https://gist.github.com/archana-multi-concept/9ded434f397ff354292dfd726ab2bc87#file-getdocumentqueryoutput](https://gist.github.com/archana-multi-concept/9ded434f397ff354292dfd726ab2bc87#file-getdocumentqueryoutput)

**Comment by archana-multi-concept** [comment]
issue found in file /var/www/html/lealta/vendor/pimcore/data-hub/src/GraphQL/DocumentElementType/BlockType.php
When I remove condition of **instanceof Checkbox**. bold in code ,from the code, it return value in iframe.

    public static function getInstance()
    {
        if (!self::$instance) {
            $config =
                [
                    'name' => 'document_editableBlock',
                    'fields' => [
                        '_editableName' => [
                            'type' => Type::string(),
                            'resolve' => static function ($value = null, $args = [], $context = [], ResolveInfo $resolveInfo = null) {
                                if ($value instanceof Checkbox ) {
                                    return $value->getName();
                                }
                            }
                        ],
                        '_editableType' => [
                            'type' => Type::string(),
                            'resolve' => static function ($value = null, $args = [], $context = [], ResolveInfo $resolveInfo = null) {
                                if ($value instanceof Checkbox) {
                                    return $value->getType();
                                }
                            }
                        ],
                        'indices' => [
                            'type' => Type::listOf(Type::int()),
                            'resolve' => static function ($value = null, $args = [], $context = [], ResolveInfo $resolveInfo = null) {
                                if ($value instanceof Block) {
                                    return $value->getData();
                                }
                            }
                        ]
                    ],
                ];
            self::$instance = new static($config);
        }

        return self::$instance;
    }

**Comment by weisswurstkanone** [comment]
resolved via https://github.com/pimcore/data-hub/pull/366
