### ISSUE TITLE
empty graphql preview screen

### ISSUE THREAD

**Issue by pspierce** [pimcore/data-hub#37]
Using 

> pimcore/pimcore                     v5.7.3  
> pimcore/data-hub                    dev-master 0d578c1 Pimcore Data Hub - Early Preview
, no matter how simple my configuration, the graphQL window opens without any content, just the commented out window.
![image](https://user-images.githubusercontent.com/456876/57972630-566daa80-796b-11e9-958e-c5c0ebac810c.png)
![image](https://user-images.githubusercontent.com/456876/57972634-66858a00-796b-11e9-96ab-d607f48a61c6.png)

![image](https://user-images.githubusercontent.com/456876/57972692-f9262900-796b-11e9-93b3-fef078de7bc1.png)

**Comment by NiklasBr** [comment]
What happens if you expand the schema to the right on the GraphiQL screen?

It does not look like you are trying to run a query. If you write a query sort of like this and run it:

```graphql
{
  getProductListing {
    edges {
      node {
        number
      }
    }
  }
}
```
Do you get a different error?

**Comment by weisswurstkanone** [comment]
@pspierce , any updates ?

**Comment by weisswurstkanone** [comment]
closed due to inactivity
