### ISSUE TITLE
 "message": "Warning: Undefined array key \"type\""

### ISSUE THREAD

**Issue by ismetsener** [pimcore/data-hub#371]
Hi,

I am experimenting pimcore data hub, it works fine  but when I use the next command:

__________________________________________________________________________________________________________________________________
mutation  {createCompany (
key: "Company_003"
parentId: 32
published: true
input: {active: true, search_key: "NL100000212",name: "Company_003" } )  
{ 
success
message
output 
{ 
search_key
name
fullpath
}
} 
}
________________________________________________________________________________________________________________________________

I get a error:

{
  "errors": [
    {
      "message": "Warning: Undefined array key \"type\""
    }
  ]
}

this error dissapears when I add:
### **type: "some text"**
problem solved, but the question is why I ahve to add "type" ?

kind regards,
Ismet

**Comment by weisswurstkanone** [comment]
Hello @ismetsener , can you provide a sample which I can try on demo.pimcore.fun? Or provide the line number which triggers the warning. Thx!

**Comment by ismetsener** [comment]
very strange, I just made 2 cars on the demo.pimcore.fun:
CAR_007    (without type:"text")
CAR_008    (with type:"text")
both with out problems 

```
mutation {createCar (
key: "CAR_008"
parentId: 2
type: "some text"
published: true
input: {name: "CAR_008" } )
{
success
message
output
{
name
}
}
}
```


what is the function of  'type"  ?


if I look at the documentation:
```
createCar(
key: String!
path: String
parentId: Int
published: Boolean
omitMandatoryCheck: Boolean
type: String
input: UpdateCarInput
): CreateCarResult
```

**Comment by ismetsener** [comment]
> Or provide the line number which triggers the warning. Thx!

what do you mean by this?

**Comment by weisswurstkanone** [comment]
Probably the error reporting level is a bit more restrictive on your instance.

My gut feeling is that we are talking about this line.
https://github.com/pimcore/data-hub/blob/ec5e1bd1ee89e8461a223dc69c05596fca28164b/src/GraphQL/Mutation/MutationType.php#L581

It is used to distinguish between object and variant type.

Could you please double check?

I would say that the parenthesis are wrong.

So it should be 

```
                        if (isset($args['type']) && ($args['type'] == 'object' || $args['type'] == 'variant')) {
                            $newInstance->setType($args['type']);
                        }
```

instead :-)

**Comment by ismetsener** [comment]
Dear Sir,

Many thanks, problem solved :)

with kind regards,
Ismet

**Comment by weisswurstkanone** [comment]
👍  fixed via https://github.com/pimcore/data-hub/commit/b2017e264abe4331eca6263da08c991b2ff878de

**Comment by Rosso2050** [comment]
In /vendor/dompdf/dompdf/I18N/Arabic/Glyphs.php
Change block line 218 to 223 to :

if ($prevChar && mb_strpos($this->_vowel, $prevChar) !== false) {
   $prevChar = isset($chars[$i - 2])?$chars[$i - 2]:'';
   if ($prevChar && mb_strpos($this->_vowel, $prevChar) !== false) {
       $prevChar = $chars[$i - 3];
   }
}
