### ISSUE TITLE
DataObject resolveIndex always results in NULL

### ISSUE THREAD

**Issue by Laggertron** [pimcore/data-hub#375]
Hi
currently it is impossible to get the `o_index` field of any object. 
This is because of the `resolveIndex` method in `src/GraphQL/Resolver/DataObject.php` line 72. The issue is that the Class `DataObject` extend the abstract class `AbstractObject` and all Pimcore classes in the namespace `Pimcore\Model\DataObject` extend from this abstract class as well and are simply never an instance of `\Pimcore\Model\DataObject` but rather of `Pimcore\Model\DataObject\AbstractObject`. As a result the index field will always return `NULL` if queried in datahub.

**Comment by weisswurstkanone** [comment]
Hi @Laggertron , can you provide a sample query which can be reproduced on demo.pimcore.fun. Thx!

**Comment by weisswurstkanone** [comment]
should be resolved via https://github.com/pimcore/data-hub/pull/376
