### ISSUE TITLE
Update outdated link to Pimcore filtering docs

### ISSUE THREAD

**Issue by slri** [pimcore/data-hub#381]
Affected page: https://pimcore.com/docs/data-hub/current/GraphQL/Query/Filtering.html
Incorrect URL: https://pimcore.com/docs/6.x/Development_Documentation/Web_Services/Query_Filters.html (yields 404)

Correct URL: https://pimcore.com/docs/pimcore/6.9/Development_Documentation/Web_Services/Query_Filters.html

This is definitely primarily a fault of the official Pimcore docs for redirecting `6.x` to `current`, but it's better to update them here than to get Pimcore to change docs redirect rules.

**Comment by mcop1** [comment]
Fixed by PR #414
