### ISSUE TITLE
Call to undefined method getParent in class Pimcore\Model\DataObject\Fieldcollection\Data\...

### ISSUE THREAD

**Issue by janschikorr-nx** [pimcore/data-hub#386]
This Bug occured after fixing this preceding Bug: https://github.com/pimcore/data-hub/issues/385

### How to reproduce:
Create a Class with a Fieldcollection defined. The Fieldcollection has at least a `Many-To-Many Object Relation`. Add the Fieldcollection to the Object Query Schema. Then query the Object with the Fieldcollection.

### Result of the Query:
`{
  "errors": [
    {
      "message": "Call to undefined method getParent in class Pimcore\\Model\\DataObject\\Fieldcollection\\Data\\Lieferantenzuordnung"
    }
  ]
}`
For example requesting a Attribute of Type `Checkbox` for from the Fieldcollection works as expected.

### Expected Behaviour:
The DataHub delivers the requested Object with the Fieldcollection and all defined `Many-To-Many Object Relations`.

### Tested on Versions:
Pimcore 6.9.2
Pimcore DataHub 1.0.3

**Comment by weisswurstkanone** [comment]
can you provide a sample request please ?
BTW, I would be nice if you could provide the full stack trace if possible for future issues.

**Comment by weisswurstkanone** [comment]
Tried something like that where manytomany is many-to-many-object relation and everything went fine. So please provide exact steps on how to reproduce on demo.pimcore.fun

![image](https://user-images.githubusercontent.com/6142086/124546361-d0529d80-de2a-11eb-913b-c917bee42ca1.png)

**Comment by janschikorr-nx** [comment]
We were able to fix the error. The Problem was actually that the referenced Fieldcollection and the `Many-To-Many Object Relation` had exact the same name.

**Comment by weisswurstkanone** [comment]
thx for your feedback
