### ISSUE TITLE
Video thumbnail returns null

### ISSUE THREAD

**Issue by Dirndorfer** [pimcore/data-hub#392]
Queries on video thumbs return null.

Tested local and on demo.pimcore.com

With this query:
```graphql
query {
  getAsset(id:353){
	fullpath,
    	thumb: fullpath(thumbnail:"featurerette")

  }
}
```

I get this return:
```json
{
  "errors": [
    {
      "message": "Internal server error",
      "extensions": {
        "category": "internal"
      },
      "locations": [
        {
          "line": 31,
          "column": 6
        }
      ],
      "path": [
        "getAsset",
        "thumb"
      ]
    }
  ],
  "data": {
    "getAsset": {
      "fullpath": "/Sample%20Content/Videos/Volkswagen-Van.mp4",
      "thumb": null
    }
  }
}
```

**Comment by weisswurstkanone** [comment]
@Dirndorfer I created a temporary bugfix which simply returns the first format encountered which is mp4 in this example. In the real world there could be more so I would say there should be an optional "format" argument. Wdyt ?
Do you want to volunteer ? 😄

**Comment by danielerne** [comment]
@weisswurstkanone After this change fullpath is now null. For others who doesn't use video thumbnails. ;)
But an enhancement would be great if it supports getImageThumbnail() for the video Asset too. Otherwhise it's not possible to show a preview image for the video.

**Comment by weisswurstkanone** [comment]
Hello @danielerne , could you please provide a PR? Thanks a lot!
