### ISSUE TITLE
Support Import Transformation Pipeline for Data Component "Date" and "Time"

### ISSUE THREAD

**Issue by shaselboeck** [pimcore/data-hub#396]
Data Component of the type Datetime can be transformed during the import, but a transformer for Data Component "Date" and "Time" is missing.

**Comment by fashxp** [comment]
can you not use the date transformer for these data types? at least `date` should be possible?

**Comment by shaselboeck** [comment]
I've adjusted my class (data object) so that it only works with Date (DateTime). However, if you have a date and several associated time fields in the class, there is currently no solution for an import. I hope the customer accepts my customization.

**Comment by weisswurstkanone** [comment]
@shaselboeck any updates on this ?

**Comment by shaselboeck** [comment]
@weisswurstkanone As mentioned, I chose a different solution for the project.

**Comment by weisswurstkanone** [comment]
ok thx, then I will close this for now. Please feel free to reopen this at any time and contribute your findings 👍
