### ISSUE TITLE
Don't place \Pimcore::getContainer calls into the boot function of the Bundle

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#4]
When running tests, it might be possible that this doesn't work since the Kernel will be set later during the init of the test suite. 

Move those EventHandlers to services directly.

https://github.com/pimcore/data-hub/blob/master/src/Pimcore/Bundle/DataHubBundle/PimcoreDataHubBundle.php#L40

**Comment by weisswurstkanone** [comment]
see >https://github.com/pimcore/data-hub/issues/7
