### ISSUE TITLE
Calling GraphQL Mutations lead to 500 error in DataHub

### ISSUE THREAD

**Issue by Iblis** [pimcore/data-hub#403]
### How to reproduce:
Configure a Migration Schema for a class in a Datahub Schema Definition, enableing 'Create' for the mutation.
Make sure the Security Definition has a path it can create items in.
Call the Create-Mutation via its defined GraphQL endpoint (eg via GraphiQL)
eg having a class 'TestObject' with an input-property 'SomeField':
`mutation {createTestObject(key:"someObject", path: "/",  input: {SomeField: "huhu" })  {success message }}`

### Actual Behavior:
DataHub / DataHub-Explorer returns a 500:
Cannot instantiate abstract class Pimcore\\Model\\DataObject\\AbstractObject
"file": "/var/www/html/vendor/pimcore/pimcore/models/DataObject/AbstractObject.php","line": 383,

### Expected Behaviour:
The object is created and a success message is returned

### Hints
Looks like using AbstractObject::getByPath/getById (https://github.com/pimcore/data-hub/blob/1.x/src/GraphQL/Mutation/MutationType.php#L581) is not working anymore since the class is abstract now. Would Pimcore\Model\DataObject be a good substitute?

### Tested on Versions:

Pimcore 10.1
Pimcore DataHub 1.0.6

**Comment by Iblis** [comment]
Just tested it locally, using DataObject::getByPath/getById instead of AbstractObject fixes the issue. There are multiple places where AbstractObject::get... is used. But looking at the issue more closely, it looks like the issue only appears when calling ::getByPath? If my assumption is correct, is https://github.com/pimcore/data-hub/blob/1.x/src/GraphQL/Mutation/MutationType.php#L581 the only place that needs fixing?

**Comment by weisswurstkanone** [comment]
Can you provide a PR please? If this pops at other places we will fix it as soon as we face it. Thx!

**Comment by Iblis** [comment]
https://github.com/pimcore/data-hub/pull/406

**Comment by weisswurstkanone** [comment]
fixed via #407
