### ISSUE TITLE
[Bug]: GraphQL API keys should not be exposed in VCS

### ISSUE THREAD

**Issue by mortenhartvig** [pimcore/data-hub#410]
### Expected behavior

API keys should not be part of version control systems.
There is no official .gitignore in the default installation, that prevents this by default. 

The /var/config/datahub-configurations.php should either be .gitignored (probably a bad option), or the keys should be placed elsewhere. 

### Actual behavior

![image](https://user-images.githubusercontent.com/17026838/130868167-5039278d-420f-4824-b936-ded78ff76495.png)

### Steps to reproduce

- Install skeleton project
- Install data-hub
- Create a sample GraphQL coniguration
- Congratulations: Git is now suggesting the API key is added to VCS.

**Comment by fashxp** [comment]
can be solved now: 
- for deployed configuration via using symfony yml configuration files and environment variables
- for on production system changed configurations using settings store as storage location.

see also https://pimcore.com/docs/data-hub/current/Deployment.html#page_Configuration-Storage
