### ISSUE TITLE
Mutation datatype 'quantityValue' not supported yet

### ISSUE THREAD

**Issue by philippjost** [pimcore/data-hub#411]
### Expected behavior

1. Open Datahub Configuration/create new Datahub Configuration
2. Add mutation schema for an object (with quantityValue fields) and go to settings
3. Add field of type quantityValue 
4. Save configuration
4. Set quantityValue in datahub mutation request

### Actual behavior

1. Open Datahub Configuration/create new Datahub Configuration
2. Add mutation schema for an object (with quantityValue fields) and go to settings
3. Add field of type quantityValue 
4. Get ERROR "Mutation datatype 'quantityValue' not supported yet

### Steps to reproduce

1. Open Datahub Configuration/create new Datahub Configuration
2. Add mutation schema for an object (with quantityValue fields) and go to settings
3. Add field of type quantityValue 
4. Get ERROR "Mutation datatype 'quantityValue' not supported yet

**Comment by weisswurstkanone** [comment]
Well, as the message says it is simply not supported yet 😉 Please feel free to provide a PR.
