### ISSUE TITLE
[Bug]: No Package available

### ISSUE THREAD

**Issue by jerem-eng** [pimcore/data-hub#422]
### Expected behavior

Hello guys, 

i try to set up, Data Hub ci-Hub, bundle for pimcore X 

the documentation said to make a  composer require pimcore/data-hub-simple-rest and composer require pimcore/data-hub-ci-hub.

and the package will be installed

### Actual behavior

the documentation said to make a  composer require pimcore/data-hub-simple-rest and composer require pimcore/data-hub-ci-hub.

but i get 
   Your requirements could not be resolved to an installable set of packages.
    - Root composer.json requires pimcore/data-hub-simple-rest, it could not be found in any version, there may be a typo in the package name.

i try with the minimum-stability: dev but i get the same error

and i check on https://packagist.org/  and i can't find these packages. 

### Steps to reproduce

composer require pimcore/data-hub-simple-rest
or
composer require pimcore/data-hub-ci-hub.

**Comment by fashxp** [comment]
Hi, these (simple rest and ci-hub) are enterprise bundles and are not available at packagist. you need to buy an enterprise subscription to be able to use them. details see https://pimcore.com/en/platform/subscription
