### ISSUE TITLE
[Improvement]:  data-hub document : example > query data from postman

### ISSUE THREAD

**Issue by sys4cad** [pimcore/data-hub#423]
### Improvement description

In order to execute GraphiQL query via Postman

1.  set URL 
   http://<your_server>/**pimcore-graphql-webservices**/products
          * product: end point name
![image](https://user-images.githubusercontent.com/9436271/138233520-56d37876-0d1a-435b-9b98-57c3321f6a72.png)

2.  set Header
  KEY: apiKey  VALUE: Datahub API Key of endpoint
![image](https://user-images.githubusercontent.com/9436271/138234576-71a58e24-b23d-47ea-a02b-d91bd43f1826.png)

3.  set Body
   string presentation of graphiQL 
![image](https://user-images.githubusercontent.com/9436271/138234673-8a0b2b29-b59e-4f2a-8ce9-d9d475661898.png)

4.  good to send request! here is the response 
![image](https://user-images.githubusercontent.com/9436271/138233924-b12fb99a-f14f-4860-866c-841c27a3123b.png)

**Comment by sys4cad** [comment]
spent 1 hour to feagure this out. hope this will help a bit.

**Comment by dvesh3** [comment]
@sys4cad Hi, thanks for your efforts and sharing it with the community. However, this is too specific for Data Hub documentation, so i would keep this in discussions here  https://github.com/pimcore/pimcore/discussions/categories/general.

Please create a discussion here https://github.com/pimcore/pimcore/discussions/new thanks!
