### ISSUE TITLE
Create the basis for mutations

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/data-hub#43]
* create objects
* update objects (support a few datatypes and operators)
* delete objects

* create/read/update/delete assets (at least data + filename)
* create/read/update/delete asset & object folders

**Comment by NiklasBr** [comment]
If there are no Mutations configured then `GraphQL/Mutation/MutationType.php` method `build()` will throw because: *Warning: ksort() expects parameter 1 to be array, null given*

I'm making a PR.
