### ISSUE TITLE
[Bug]: Undefined property: Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentType::$customTypes

### ISSUE THREAD

**Issue by robertkrippgans** [pimcore/data-hub#430]
### Expected behavior

Data-Hub API was working until update to current release 1.0.10

### Actual behavior

On every request I got an exception:

`Warning: Undefined property: Pimcore\Bundle\DataHubBundle\GraphQL\DocumentType\DocumentType::$customTypes`

### Steps to reproduce

call a random endpoint, that worked before ... it will throw this exception. 

### Update

downgrading to release 10.0.8 is "solving" this issue

**Comment by weisswurstkanone** [comment]
Hello @robertkrippgans , is the full stack trace available. Or steps to reproduce? Many thanks!

**Comment by dvesh3** [comment]
Seems regression of https://github.com/pimcore/data-hub/pull/427

**Comment by ITspirit** [comment]
Would say the tag 1.0.10 is set wrong.

**Comment by dvesh3** [comment]
> Would say the tag 1.0.10 is set wrong.

@ITspirit true! However changes were cherry picked on 1.0 branch https://github.com/pimcore/data-hub/pull/427#issuecomment-952883213

**Comment by ITspirit** [comment]
Well branch 1.0 is the same as tag 1.0.10,  also buggy. Will use 1.x-dev instead - because live installation is broken now :-(

**Comment by dvesh3** [comment]
OK, I understood the problem now. Cherry picking on 1.0 was a wrong decision as initial changes https://github.com/pimcore/data-hub/pull/419 only exist on 1.x.

**Comment by dvesh3** [comment]
@robertkrippgans @ITspirit Sorry for the trouble! Reverted the wrong commit on 1.0 branch https://github.com/pimcore/data-hub/commit/6b5b2259f3d2c68bd281110d508ceb6747ad0c88 which should fix this issue.

Bugfix release 1.0.11 will be tagged tomorrow.
