### ISSUE TITLE
[Bug]: imported data converted by HTML char 

### ISSUE THREAD

**Issue by sys4cad** [pimcore/data-hub#439]
### Expected behavior

' " should be maintain as it is.

 

### Actual behavior

some characters are converted HTML char format as following

![image](https://user-images.githubusercontent.com/9436271/142374247-85f3ee03-dfd0-49e6-a522-bac27118a3d2.png)

single quote char(') is converted  by & # 3 9 ;

### Steps to reproduce

import data by datahub graphql service.

**Comment by brusch** [comment]
Moved to data-hub repo

**Comment by sys4cad** [comment]
any work around or fix will be highly appreciated.

**Comment by brusch** [comment]
Debugging this issue shouldn't be too hard, can you give it a try and provide us a PR? Thanks in advance!

**Comment by sys4cad** [comment]
I've noticed that delivered data via graphql palette of node red enforced the html encoding.
Thus I applied html_entity_decode for reverting it back.

Could you kindly let me know which source generating php sources for DataHub mutation?

 

 
        $data = $this->category;

        if ($data instanceof \Pimcore\Model\DataObject\Data\EncryptedField) {
                        return $data->getPlain();
        }

        // return $data
        return html_entity_decode($data);
}

**Comment by mcop1** [comment]
@sys4cad is this problem still relevant? Because with the current data-hub version, I wasn´t able to reproduce the problem.

**Comment by sys4cad** [comment]
If you call graphql  via https://flows.nodered.org/node/node-red-contrib-graphql 

this component sending  data with html_entity_encode api result.

IMO, this issue is not related with Pimcore data hub itself. you can close this issue.

Thanks.
