### ISSUE TITLE
[Improvement]: Compatibility with pimcore/pimcore 

### ISSUE THREAD

**Issue by sigere** [pimcore/data-hub#442]
### Improvement description

In `installation`, requirements say: `Pimcore >= 5.7`
witch is not true at all, we cannot upgrade to 1.1 with pimcore/pimcore 10.0.4, becouse classes are missing (e.g. `Attempted to load class "PimcoreLocationAwareConfigDao" from namespace "Pimcore\Model\Dao"`).
Please, at least update `requirements` not to confuse people.

**Comment by dvesh3** [comment]
@sigere Hi, sorry for the confusion. I have fixed the docs https://github.com/pimcore/data-hub/commit/93274618f0887e6704432fcb657d3caa7b2280da

**Comment by sigere** [comment]
thanks for fixing!
