### ISSUE TITLE
[Improvement]: Update Deployment docs

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#445]
### Improvement description

see https://pimcore.com/docs/data-hub/1.1/Deployment.html#page_Configuration-Deployment

not up-to-date anymore ... at least the start with The configuration is saved in `var/config/datahub-configurations.php`

Also add a note that `symfony-config` is not writeable in production environments anymore ... see also https://github.com/pimcore/pimcore/discussions/10940

**Comment by dvesh3** [comment]
Fixed by  #448
