### ISSUE TITLE
Query on fields coming from a related object result in NULL

### ISSUE THREAD

**Issue by khenow1978** [pimcore/data-hub#447]
### Expected behavior

When using GraphQL to access a class object which references a different object within Pimcore it's supposed to provide me the information from the referenced object. 

### Actual behavior

When write the query like you see in the screenshot I get a NULL value instead:

![grafik](https://user-images.githubusercontent.com/92732594/145415751-5ff2037b-7230-4f2a-b641-15d04c7d4750.png)

This is the same for all relational objects which refer to another class. I'm not sure if this is a bug or a syntax error. I've tried to compare my GraphQL Settings with the pimcore demo but I can't find any obvious issue.

I tried it with "listing" and without but the effect is the same. I also use the same Datahub version as the demo.

### Steps to reproduce

Create a class that contains a relational field (many-to-one or many-to-many). Assign an object to that field.
Create a graphql job and reference to both classes in the Query schema.

Try to pull data from the referenced object.

**Comment by jerem-eng** [comment]
I have the same problem, 3 relational fields  works, but one dosen't work, i don't know why

the most strange is my queries work fine in my dev environnement but not in my production environment.

the field who dosn't work was added recently, instead of 3 first. so maybe is du to an update, but i dont't uderstand why i have difference between my environment.

**Comment by khenow1978** [comment]
Hi.. one thing I recognized: You have to set up the security permissions properly. So if the relational field is assigned to a different object class in a different folder you have to give appropriate permissions in the "workspaces" part. That fixed most of it for me. HOWEVER I still can't use a thumbnail generator in the GraphQL API. Every picture results in NULL although there is an image. If I use a different syntax (accessing the image directly and force a certain resolution & thumbnail) I get access to the thumbnails.

**Comment by jerem-eng** [comment]
i have set up the permissions on my local thats works perferctly, but in my production workspace are not recognized i think.
for the picture i just get the fullpath and the name, i don't try to get thumbnails

**Comment by fashxp** [comment]
did you run `datahub:graphql:rebuild-definitions` after deployment? see also https://pimcore.com/docs/data-hub/current/Deployment.html

**Comment by weisswurstkanone** [comment]
Unable to reproduce on the official demo instance demo.pimcore.fun

- Open the products and configuration
- Open the playground
- Execute the following query
- You will see that it returns the name of the linked manufacturer (a href) and the manufacturer's logo.

![image](https://user-images.githubusercontent.com/6142086/150781375-789a6b1d-6859-4b93-9e59-a58fe2cac711.png)

Query as plain text

```
{
  getCarListing(fullpaths: "/Product Data/Cars/ac cars/Cobra 427") {
    edges {
      node {
        id
        name
        manufacturer {
          __typename
          ... on object_Manufacturer {            
            id
            name
            logo {
              fullpath
              dimensions {
                width
                height
              }
            }
          }
        }
      }
    }
  }
}
```

**Comment by khenow1978** [comment]
In my comment from 21st December you'll notice that I found the reason why it resulted in NULL. You can't reference to a different object or class if you haven't granted appropriate permissions to that object.
