### ISSUE TITLE
Fields not set when using create mutation

### ISSUE THREAD

**Issue by AlekMosingiewicz** [pimcore/data-hub#452]
### Expected behavior

When I create an object using a "create" mutation and provide parameters in the "input" section, I expect those parameters to be set when object is created.

### Actual behavior

The object is created with expected parent and key, but the values in the "input" section are ignored.

### Steps to reproduce

Create a simple object class ("testClass") with one text field, let's call it "testField". Then use the following GraphQL mutation:

`createTestClass (
    key: "testObject",
    parentId: 1,
    input: { testField: "testValue" }
) {
     message
}`

The object will be created, but with empty "testField".

**Comment by weisswurstkanone** [comment]
Fixed via #460 . Please don't forget that you also need "Update" rights. Next minor release will be tomorrow.
