### ISSUE TITLE
Querying on inputQuantityValue from Classificationstore returns null values (always)

### ISSUE THREAD

**Issue by and-ratajski** [pimcore/data-hub#454]
### Expected behavior

After defining class attribute as a Classificationstore field (that can store i.e. "**select**", "**boolean**" and "**inputQuantiyValue**" types), a user should be able to obtain those fields using DataHub GraphQL API ( the _... on csFeature[type]_ methods). As Data Hub automatically generates GraphQL endpoints (and their documentation) to send queries against it is expected to fully consume them.

### Actual behavior

Unfortunately, whereas it is possible to execute queries against a  Classificationstore field of types "select" and "boolean", it is impossible to execute them against a  Classificationstore field of type "**inputQuantiyValue**" (other types haven't been thoroughly checked). The problem is that no matter their value (or unit) GraphQL query keeps returning **_null_** , see screen shot:
![data_hub_issue_result](https://user-images.githubusercontent.com/88457474/148219089-1338b375-77a9-4a48-aea9-76989c35469c.png)
Object (product data sheet) and it's values:
![data_hub_issue_definition](https://user-images.githubusercontent.com/88457474/148219174-0fa111e1-ce29-461b-a930-76ba0bc8dbd4.png)

### Steps to reproduce

1. Create a Classificationstore than contains a group with relation to 
* boolean type
* select type
* **inputQuantityValue** type
![data_hub_issue_calssstore](https://user-images.githubusercontent.com/88457474/148219982-40574b40-68f5-4c9b-9965-88841ae3c178.png)

2. Make sure it's **inputQuantityValue** type
![data_hub_issue_detail](https://user-images.githubusercontent.com/88457474/148220042-90a3c30a-fd68-44c2-8633-5738b43fd0b8.png)

3. Create a Class that contains an attribute with the Classificationstore you have created,
4. Create an instance of this Class (object, product data sheet) and fill it with some values,
5. Create GraphQL endpoint (Configuration) in Data Hub so your'e allowed to query against Classificationstore attribute,
6. Execute a query in iFrame (Data Hub) against object Classificationstore features, as in _Actual behavior_ - example:
[query....]   
features {
        ... on csFeatureBooleanSelect {
          type,
          name,
          description,
          checked
        }
        ... on csFeatureSelect {
          type,
          name,
          description,
          selection
        }
        ... on csFeatureInputQuantityValue {
        type,
        name,
        description,
        inputquantityvalue {
          value,
          unit {
            longname,
            abbreviation
          }
          toString
         }
        }
        ... on csFeatureInput {
          type,
          name,
          description,
          text
        }
      }

7.  You should see all values except those for **inpuQuantityValue** field

**Comment by and-ratajski** [comment]
Update: There's a workaround with **quantityValue** (numeric):
![quantityValue](https://user-images.githubusercontent.com/88457474/148971181-725d576f-4b24-4778-9353-c657a1d71c6b.png)

**Comment by weisswurstkanone** [comment]
fixed via https://github.com/pimcore/data-hub/pull/459
