### ISSUE TITLE
[Bug]: Datahub throwing error in Pimcore 6.7

### ISSUE THREAD

**Issue by rohitrajv5** [pimcore/data-hub#455]
### Expected behavior

Pimcore composer install is not working in with Pimcore 6.7. It should install all the packages.

Below is my composer.json. 

{
  "name": "pimcore/demo-ecommerce",
  "type": "project",
  "description": "E-Commerce Demo Application for Pimcore 5",
  "license": "GPL-3.0-or-later",
  "config": {
    "optimize-autoloader": true,
    "sort-packages": true
  },
  "require": {
    "php": ">=7.2",
    "elasticsearch/elasticsearch": "^7.9",
    "pimcore/customer-management-framework-bundle": "^1.9",
    "pimcore/data-hub": "^0.6.3",
    "pimcore/pimcore": "~6.7.0",
    "pimcore/server-side-matomo-tracking": "~0.2",
    "pimcore/web2print-tools-bundle": "^2.4",
    "wikimedia/composer-merge-plugin": "^1.4",
    "hellosign/hellosign-php-sdk": "^3.0"
  },
  "require-dev": {
    "cache/integration-tests": "^0.16.0",
    "codeception/codeception": "~2.4.5"
  },
  "autoload": {
    "psr-4": {
      "": ["src/"],
      "Pimcore\\Model\\DataObject\\": "var/classes/DataObject",
      "Pimcore\\Model\\Object\\": "var/classes/Object",
      "Website\\": "legacy/website/lib"
    },
    "classmap": [
      "app/AppKernel.php"
    ]
  },
  "scripts": {
    "post-create-project-cmd": "Pimcore\\Composer::postCreateProject",
    "post-install-cmd": [
      "Pimcore\\Composer::postInstall",
      "@pimcore-scripts"
    ],
    "post-update-cmd": [
      "Pimcore\\Composer::postUpdate",
      "@pimcore-scripts",
      "Pimcore\\Composer::executeMigrationsUp",
      "@pimcore-scripts"
    ],
    "pimcore-scripts": [
      "Pimcore\\Composer::clearCache",
      "Pimcore\\Composer::installAssets"
    ]
  },
  "extra": {
    "symfony-app-dir": "app",
    "symfony-bin-dir": "bin",
    "symfony-var-dir": "var",
    "symfony-web-dir": "web",
    "symfony-tests-dir": "tests",
    "symfony-assets-install": "relative",
    "merge-plugin": {
      "include": [
        "composer.local.json"
      ],
      "recurse": true,
      "replace": true,
      "merge-dev": true,
      "merge-extra": false,
      "merge-extra-deep": false,
      "merge-scripts": false
    }
  }
}

### Actual behavior

Throwing following error 

![image](https://user-images.githubusercontent.com/4353796/148659187-0947d8b9-77be-40ae-a746-51756c908ff4.png)

### Steps to reproduce

Execute 

copy page json and execute following command

`composer install `

It will throw error.

**Comment by fashxp** [comment]
Pimcore 6 is not supported anymore.
