### ISSUE TITLE
Wrong Tag v1.1.6

### ISSUE THREAD

**Issue by blankse** [pimcore/data-hub#457]
### Expected behavior

This Tag should be 1.2.0, because it have commits from 1.2.0 milestone

### Actual behavior

This Tag should be 1.2.0, because it have commits from 1.2.0 milestone

### Steps to reproduce

See https://github.com/pimcore/data-hub/releases/tag/v1.1.6

**Comment by weisswurstkanone** [comment]
done

**Comment by blankse** [comment]
@weisswurstkanone Its still available in packagist: https://packagist.org/packages/pimcore/data-hub#v1.1.6

**Comment by weisswurstkanone** [comment]
Also done :-)
