### ISSUE TITLE
[Bug]: Query with fragments in arrays not working for Strings 

### ISSUE THREAD

**Issue by snmuhein** [pimcore/data-hub#466]
### Expected behavior

The usage of fragments should get the same results as a querying all fields inline. 

Query with fragments:
```
query GetCarFragments {
  getCar(id: 308) {
    name
    categories {
      ... on object_Category {
        ...CategoryFields
      }
    }
  }
}

fragment CategoryFields on object_Category {
  id
  name
}
```

Inline query:
```
query GetCarFragments {
  getCar(id: 308) {
    name
    categories {
      ... on object_Category {
        id
        name
      }
    }
  }
}
```

**Expected result for both queries**:
```
{
  "data": {
    "getCar": {
      "name": "600",
      "categories": [
        {
          "id": "561",
          "name": "Economy Cars"
        }
      ]
    }
  }
}
```

### Actual behavior

The query with fragments gets null for the fields of type **String**. (e.g. CategoryFields name)
```
query GetCarFragments {
  getCar(id: 308) {
    name
    categories {
      ... on object_Category {
        ...CategoryFields
      }
    }
  }
}

fragment CategoryFields on object_Category {
  id
  name
}
```

Query result, all strings of the fragment have value null which is wrong:
```
{
  "data": {
    "getCar": {
      "name": "600",
      "categories": [
        {
          "id": "561",
          "name": null
        }
      ]
    }
  }
}

```

### Steps to reproduce

The error can be reproduced [here](https://dam.broekhuis.online/pimcore-datahub-webservices/explorer/products?apikey=6332aa5e6d3d6c0be31da2a8b3442113&query=%7B%0A%20%20getCar(id%3A%20308)%20%7B%0A%20%20%20%20name%0A%20%20%20%20categories%20%7B%0A%20%20%20%20%20%20...%20on%20object_Category%20%7B%0A%20%20%20%20%20%20%20%20...CategoryFields%0A%20%20%20%20%20%20%7D%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20CategoryFields%20on%20object_Category%20%7B%0A%20%20id%0A%20%20name%0A%7D%0A).

![image](https://user-images.githubusercontent.com/45623668/151415696-4f99c040-4dab-4399-a268-661c74720f0c.png)

**Comment by weisswurstkanone** [comment]
@snmuhein , the bundle looks a bit outdated. There is GraphiQl anymore. The playground should look this

![image](https://user-images.githubusercontent.com/6142086/151496734-57a7a637-7dcd-40e6-b518-2e7594e7cc15.png)

Please check your version.

Many thanks! :-)

**Comment by snmuhein** [comment]
Thanks for the fast response. I just realized that the described scenario above is **not a bug** of the data-hub, but shows my incorrect usage of fragments. 

Here is a short explanation what I did wrong. Maybe it helps someone else as well:
The above query uses an [Inline Fragment](https://graphql.org/learn/queries/#inline-fragments) with a nested [Fragment](https://graphql.org/learn/queries/#fragments) for the same underlying type (e.g. `object_Category`). The inline fragment is not necessary and can just be omitted.

**Correct query:**
```
{
  getCar(id: 308) {
    name
    categories {
      ...CategoryFields
    }
  }
}

fragment CategoryFields on object_Category {
  id
  name
}
```

Using this query returns the [expected result](https://dam.broekhuis.online/pimcore-datahub-webservices/explorer/products?apikey=6332aa5e6d3d6c0be31da2a8b3442113&query=%7B%0A%20%20getCar(id%3A%20308)%20%7B%0A%20%20%20%20name%0A%20%20%20%20categories%20%7B%0A%20%20%20%20%20%20...CategoryFields%0A%20%20%20%20%7D%0A%20%20%7D%0A%7D%0A%0Afragment%20CategoryFields%20on%20object_Category%20%7B%0A%20%20id%0A%20%20name%0A%7D%0A).

**Comment by mcop1** [comment]
This issue seems to be resolved, so I am going to close it.
@snmuhein if you have any further questions feel free to open another issue.

Thanks and best regards
