### ISSUE TITLE
[Bug]: Bugfix FAILURE on Issue #454 - inputQuantityValue from Classificationstore returns null

### ISSUE THREAD

**Issue by and-ratajski** [pimcore/data-hub#471]
### Expected behavior

From Issue [#454](https://github.com/pimcore/data-hub/issues/454):
After defining class attribute as a Classificationstore field (that can store i.e. "select", "boolean" and "inputQuantiyValue" types), a user should be able to obtain those fields using DataHub GraphQL API ( the ... on csFeature[type] methods). As Data Hub automatically generates GraphQL endpoints (and their documentation) to send queries against it is expected to fully consume them.

### Actual behavior

It seems that fix for the Issue [#454](https://github.com/pimcore/data-hub/issues/454) was only partly resolved as it returns now the _**value**_ of **_inputQuantityValue_** leaving the _**unit**_ object fileds null:
![2022-02-07_11-16](https://user-images.githubusercontent.com/88457474/152771498-1441f04b-4dc6-4ca9-acde-c16a60ee1204.png)

Moreover, taking a one-eye-look at the PR [#459](https://github.com/pimcore/data-hub/pull/459/files) files I cannot see any **_unit_** changes... 

### Steps to reproduce

The same as in the Issue [#454](https://github.com/pimcore/data-hub/issues/454):

Looking forward to heaving this feature ready as it super helpful!
B.R.
Andrzej

**Comment by blankse** [comment]
@andrat-creo I created an PR for this: https://github.com/pimcore/data-hub/pull/472
