### ISSUE TITLE
[Improvement]: disable introspection by default for production environment

### ISSUE THREAD

**Issue by RuudvdvNB** [pimcore/data-hub#473]
### Improvement description

By default introspection for GraphQL is enabled, this applies to all environments. Because of the ease of setting up a GraphQL endpoint human errors can occur by accidentally adding sensitive data.

When this happens in production environments it is very easy to introspect the entire GraphQL endpoint and find out about this kind of data.

I think it would be a great improvement when introspection is disabled by default on production environments. Introspection could be enabled when you're logged into the Pimcore admin on a production environment and when you have the right permissions.

**Comment by fashxp** [comment]
TODO: 
- add additional configuration option for disabling
- make disabled as default
- add migration for existing configurations and activate introspection for them (so no change of existing configurations)
