### ISSUE TITLE
[Bug]: syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

### ISSUE THREAD

**Issue by lchhieu** [pimcore/data-hub#481]
### Expected behavior

Can work as normal

### Actual behavior

syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)

### Steps to reproduce

I used php 8.1.16 and got the issue "syntax error, unexpected ')', expecting '|' or variable (T_VARIABLE)"
Dont update anyting

**Comment by fashxp** [comment]
can you provide a bit more information. when do you get that error?

**Comment by lchhieu** [comment]
@fashxp
