### ISSUE TITLE
[Improvement]: inconvenient namespace for datahub:graphql:rebuild-definitions command

### ISSUE THREAD

**Issue by jeykodev** [pimcore/data-hub#489]
### Improvement description

After changing my `PIMCORE_WRITE_TARGET_DATA_HUB` from `symfony-config` to `settings-store` (see [Docs](https://pimcore.com/docs/data-hub/current/Deployment.html)) I looked for a possibility to rebuild the definitions, so the configuration will be initial saved in the database instead of config files. 

I've found the metioned command but it has the namespace `graphql` and since I'm using the [Data Importer](https://github.com/pimcore/data-importer), I thought this will be not an option. 

After that, I looked into the [command](https://github.com/pimcore/data-hub/blob/1.x/src/Command/GraphQL/RebuildDefinitionsCommand.php) and found out, that no additional checks for the specific configuration type `graphql` are implemented. At the end the command does rebuild every configuration type, not only `graphql`. 

So I would suggest to remove the `graphql` namespace from the command and adapt the description and documentation. 

If you guys agree, I can make a PR.

**Comment by kingjia90** [comment]
@jeykodev Thank you for reporting, we would glad to see a PR about the change. 
I have also got a tip that this change may need a BC Layer/Alias to avoid any BC Break, hope this would help you as well when making the PR.

**Comment by mcop1** [comment]
Deprecation is already there https://github.com/pimcore/data-hub/blob/7652b48a906f466cba4c2aa1d6e44d5cf4d59e7b/src/Command/GraphQL/RebuildDefinitionsCommand.php#L47 + https://github.com/pimcore/data-hub/blob/44a4c3bd0e602f46ae05851d3126b249ccd45dfe/doc/20_Deployment.md#L26, the command just needs to be removed with the next major version.

Therefore no need to change the old command, just use the new one.

**Comment by fashxp** [comment]
see also https://github.com/pimcore/data-hub/pull/480
