### ISSUE TITLE
[Bug]: GraphQL not ble to handle big Asset uploads

### ISSUE THREAD

**Issue by cutec-chris** [pimcore/data-hub#492]
### Expected behavior

Iam not 100% sure if thats really an issue. Maybe iam holding it wrong :)

But its nearly impossible to upload big Files through GraphQL since the web servers disallow with 413 Request Entity Too Large.
Even when configured to max its not enougth to upload images or videos.

Or is it even possible to use graphql with another method ? My lib (python graphqlclient) does it with get per default.

### Actual behavior

Get request fails with 413 Request Entity Too Large

### Steps to reproduce

Upload an File > configured body size of your reverse proxy.

**Comment by mcop1** [comment]
@cutec-chris 
I tried to upload an asset with updateAsset mutation shown here:
https://pimcore.com/docs/data-hub/current/GraphQL/Mutation/Asset_Mutations.html 

Adding the data as base64 string worked for me.

**Comment by cutec-chris** [comment]
have you tried with an ~250mb asset

**Comment by mcop1** [comment]
@cutec-chris I tried to upload a > 200mb video file using a GET request. Tested it with the integrated GraphiQL ui ("open in iframe") and with postman. Still working for me. But I have to admin I am working on a local test environment. 
Could pleaes test the upload with the GraphiQL ui? 

![image](https://user-images.githubusercontent.com/89011527/161059574-120e0fc9-ee7e-4fd5-bddb-ba35978ec231.png)

**Comment by mcop1** [comment]
@cutec-chris is this still relevant for you?

**Comment by cutec-chris** [comment]
yes, but i dont have the time to re-test and confirm at time would be nice if this issue can stay open an while (iam unsure if its easy possible for me to reopen, when this is the case you can also close it and i reopen)

**Comment by mcop1** [comment]
@cutec-chris I will close it for now, take your time. You can reopen the issue or create a new issue referencing this one. No problem at all.
