### ISSUE TITLE
[Bug]: GraphQL Updates partially dont give Error Messages

### ISSUE THREAD

**Issue by cutec-chris** [pimcore/data-hub#496]
### Expected behavior

All Errors have an Error message

### Actual behavior

not all Errors have an error Message

### Steps to reproduce

i dont know @ example whats wrong here, maybe pimcore dont understands the iso date format:

        mutation {
          updateProduct(id: 2340,input: {USWEIGHTGROSS: 1.6660000000000001,PREISKNZ: 201.0,WARENNR: "85176920.0",FLAGS_2: 1.0,DATETAB: 5.0,VON1: "2021-01-01T00:00:00",VON2: "2021-04-01T00:00:00",VON3: "2021-10-01T00:00:00",VON4: "2022-04-01T00:00:00",BIS1: "2021-03-31T23:59:59",BIS2: "2021-09-30T23:59:59",BIS3: "2022-03-31T23:59:59",BIS4: "2022-12-31T23:59:59"},defaultLanguage: "de") {
            success
            message
          }
        }

{'errors': [{'message': ''}]}

**Comment by mcop1** [comment]
@cutec-chris 
Sorry, I am not able to reproduce the problem on my end. I tried using a simple graphql mutation and one of your datetime values 

`  mutation {
      updateProduct(id: 1189,input: {
        DateTimeInput: "2021-01-01T00:00:00"},defaultLanguage: "de") {
        success
        message
      }
    }`
    
And it is working as expected.
Could you please try to recreate the problem in our demo environment?

Best regards

**Comment by cutec-chris** [comment]
Your right, it wasnt the date format but the FLAGS_2 value was an string and is send as json float i think (have to reproduce it) the general thing is that ive seen more than once that the graphql dont gives an error message
but your right i should provide an example that is reproduceable with the demo
Edit: the datahub seems to be not useable tith the demo

**Comment by cutec-chris** [comment]
![image](https://user-images.githubusercontent.com/5136391/159681939-192c925d-aae7-41eb-8f24-6635b053c597.png)

**Comment by cutec-chris** [comment]
```
mutation {
      updateProduct(id: 2340,input: {FLAGS_2: 1.0}) {
        success
        message
      }
    }
```
i get this:
```
{
  "errors": [
    {
      "message": ""
    }
  ]
}
```

That should be the minimal mutation to reproduce the issue

**Comment by mcop1** [comment]
DataHub with GraphQL is available at demo.pimcore.fun/admin, you can find the exact url and credentials in the "ReadMe" section of https://github.com/pimcore/pimcore.

Could you please check if your environment is in debug mode? Because without debug mode I get the expected error message:

`{
    "errors": [
        {
            "message": "Field \"updateProduct\" argument \"input\" requires type String, found 1.0.",
            "extensions": {
                "category": "graphql"
            },
            "locations": [
                {
                    "line": 2,
                    "column": 47
                }
            ]
        }
    ]
}`

It should still display a useful error message in debug mode of course.

**Comment by cutec-chris** [comment]
![image](https://user-images.githubusercontent.com/5136391/159856859-5f2d55d5-cb90-4aa0-96e7-70b33bd6faf5.png)

seems that your right, but how to exit it we use the standard pimcore/pimcore:PHP8.1-fpm docker image without an debug setting ever made (at least without knowledge)

**Comment by mcop1** [comment]
The APP_ENV environment variable is set to DEV by default, please check your `.env` file. For more information see
https://pimcore.com/docs/pimcore/current/Development_Documentation/Development_Tools_and_Details/Debugging.html 

Regarding the missing error messages, we will take a look and update the issue.

**Comment by cutec-chris** [comment]
for more Information ... i can only read how to enable debugging there not how to disable.
Also in [https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/index.html](https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/index.html) all getting Started sections i dont find an hint that debugging should be disabled. Maybe its an good idea to add an section there.

OT: An colegue of mine followed the installation guide and tried to reach his webserver according to the installation guide before it was setup (next installation steps) has nothing to do with this issue but wanted to mention it

**Comment by cutec-chris** [comment]
done. with 
APP_ENV=prod
APP_DEBUG=0

debug mode is off thanks.

**Comment by mcop1** [comment]
> for more Information ... i can only read how to enable debugging there not how to disable. Also in https://pimcore.com/docs/pimcore/current/Development_Documentation/Getting_Started/index.html all getting Started sections i dont find an hint that debugging should be disabled. Maybe its an good idea to add an section there.
> 
> OT: An colegue of mine followed the installation guide and tried to reach his webserver according to the installation guide before it was setup (next installation steps) has nothing to do with this issue but wanted to mention it

The documentation in the "Debug Mode" section refers to the symfony docs as Pimcore is based on symfony and we are not doing anything different in that regard.

But it seems like you solved this problem already on your own :)
