### ISSUE TITLE
Make Query Operators injectable to the container and load them from the container

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#5]
The intention should be quite clear: It should be possible to inject whatever I want to those operators.

https://github.com/pimcore/data-hub/tree/37f79ad6b027a83d26521290fa3b96c56288dd6a/src/Pimcore/Bundle/DataHubBundle/GraphQL/Query/Operator

**Comment by weisswurstkanone** [comment]
isn't that already the case ?

**Comment by dpfaffenbauer** [comment]
where do they get injected?

**Comment by weisswurstkanone** [comment]
maybe a misunderstanding. please provide a short example describing what you want to achieve.

**Comment by dpfaffenbauer** [comment]
having the possibility to add new Query Operators and inject them using DI

**Comment by weisswurstkanone** [comment]
adding new operators is possible.

approach is the same as for the grid config dialog.

**Comment by dpfaffenbauer** [comment]
how? can you describe more detailed?

**Comment by weisswurstkanone** [comment]
as described in the docs mentioned above
