### ISSUE TITLE
[Bug]: PublicUrl in Asset object. Querying for unpublished objects.

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-hub#502]
### Expected behavior

According to docs and previous behaviour:

1) asset fullpath should not be absolute (not be publicUrl) - https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html

2) it was not possible to query for unpublished objects

### Actual behavior

After I did pimcore and data-hub upgrade I noticed that:
1) it is now possible to query for unpublished object
2) on asset object, fullpath returns absolute url (publicUrl) instead of relative url that is still an example in most recet docs

Both of these changes are welcome, but since they are not explicitly documented I worry if they are bugs that will get reverted.

### Steps to reproduce

Query for an unpublished object. Query for fullpath field of Asset object.

**Comment by mcop1** [comment]
@rjankiew sorry, I can´t reproduce the issue on my side. 

1.  When I try to query for an unpublished object

    `{getProduct(id: 4806) {id, Name}}`
    
    I get the following error
    
    `{
      "errors": [
        {
          "message": "object with id:'4806' not found"
        }
      ]
    }`

2. When I query for the fullpath property
    
    `{getAsset(id: 4 ) {filename, fullpath}}`
    
    I get
    
    `{
      "data": {
        "getAsset": {
          "filename": "auto-automobile-automotive-192499.jpg",
          "fullpath": "/Car%20Images/jaguar/auto-automobile-automotive-192499.jpg"
        }
      }
    }`
    
    as a result. Just like it is documented. 
    
Could you please share your GraphQL query / reproduce the issue in the pimcore demo?

**Comment by rjankiew** [comment]
@mcop1 wow, that is unexpected, I thought that these were some undocumented changes. For context, pimcore version is 10.3.2 and datahub version is 1.2.3. I'll try to reproduce on demo tomorrow, and if I fail, I'll try to provide some screenshots and additional info. But that is the behaviour not only on single local env, but on (I think) 4 environments in total.

**Comment by mcop1** [comment]
@rjankiew did you have the chance to take a look?

**Comment by mcop1** [comment]
@rjankiew Issue closed for the moment. Feel free to reopen / open another issue, if you are still having troubles.
