### ISSUE TITLE
[Improvement]: Update docs

### ISSUE THREAD

**Issue by mcop1** [pimcore/data-hub#503]
### Improvement description

Update datahub / graphql documentation

- [x] Update screenshots
   - [x] replace screenshots with old graphiQL ui
      e.g. add mutation
  - [x] replace screenshots with old pimcore ui
      e.g. configuration

- [x] Check all sections marked with "ToDo"
  - [x] 04 Asset Mutations
  - [x] 22 Sample Advanced ManyToMany Object Relation
  - [x] 23 Sample Advanced ManyTomany Relation Metadata
  - [x] 20 DataObject Mutations

- [x] Make existing content more detailed
  - [x] add operators, transformers, others that are missing (e.g. merge)
  - [x] Update security settings page
  - [x] Add information about workspaces (no workspace selected -> no access)

**Comment by ghost** [comment]
Most of the code snippets in the documentation are dark grey text on black background which makes them unreadable. (Only by selecting them)

![Docs](https://user-images.githubusercontent.com/33122456/163400125-f416176a-c688-4c65-8414-c542cea7b239.png)

**Comment by dvesh3** [comment]
@KatrinAckermannEk we are reviewing a PR to fix those issues https://github.com/pimcore/pimcore-docs/pull/19 😉
