### ISSUE TITLE
[Bug]: Return value must be of type GraphQL\Type\Definition\Type, null returned

### ISSUE THREAD

**Issue by Xantios** [pimcore/data-hub#506]
### Expected behavior

Expect to get introspection data

### Actual behavior

500 Error 

```GraphQL\Type\Introspection::GraphQL\Type\{closure}(): Return value must be of type GraphQL\Type\Definition\Type, null returned```

In: vendor/webonyx/graphql-php/src/Type/Introspection.php (line 816)

### Steps to reproduce

Install Pimcore X & Datahub and use query:

```
 query NAME {
   __type(name: "getProduct") {
     name
   }
}
```

Im trying to get all available fields for my product through introspection, which as far as i could tell should work in Pimcore. however i keep getting 500's.

**Comment by mcop1** [comment]
@Xantios you need to pass the type name, which is object_Product

` query NAME {
   __type(name: "object_Product") {
     name
   }
}`

You can get all types by using introspection as well:
`query NAME {
  __schema {  
    types {
      name
    }    
  }
}
`
