### ISSUE TITLE
[Bug]: Same fieldname in fieldcollection as in object itsself doesn't work

### ISSUE THREAD

**Issue by MosiiAUT** [pimcore/data-hub#508]
### Expected behavior

- Class with a gallery named "gallery"
- Fieldcollection with a gallery also named "gallery"
- Fieldcollection is used in the class

```
{
  getTestGalleryObjekt(id: 1234) {
    fieldcollectionField {
      ... on fieldcollection_TestGallery {
        gallery {
          ... on hotspotimage {
            image {
              id
            }
          }
        }
      }
    }
  }
}
```
this should return the gallery value of the fieldcolletion

### Actual behavior

Return the gallery directly of the objects class, not the gallery of the fieldcollection

### Steps to reproduce

- Create class with gallery and name it e.g. "testGallery"
- Create a fieldcollection and add a gallery with the same name "testGallery"
- Create a object of the class and add the fieldcollection
- fill both galleries with images 
- create a graphql-query as described above

Pimcore 10.2.4
Data-Hub 1.2.5

**Comment by aryaantony92** [comment]
Fixed by #521
