### ISSUE TITLE
[Bug][DataObject] Advanced Many-to-many relation only returns DataObjects

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#513]
### Expected behavior

relation returns all elements that are assigned to the field

### Actual behavior

returns only data objects, documents and assets are omitted. 

### Steps to reproduce

- create a data object class with an advanced many-to-many relation field
- assign a data object, an asset and a document
- create graphql endpoint and retrieve data 

also check that for many-to-many relation.

**Comment by mcop1** [comment]
e.g. using this query on such a relation would return dataobjects only:
`{
  getProduct(id: 4813) {
    Name
    ManyToMany {
    ... on element {id}      
    }
  }
}`

Maybe adding `$config['interfaces'] = [Element::getInstance()];` in AssetType & DocumentType is enough

**Comment by fashxp** [comment]
also make sure just querying on metadata works and returns all assigned elements.

**Comment by mcop1** [comment]
> also make sure just querying on metadata works and returns all assigned elements.

Can be done with a query like this: 
`{ 
  getProduct(id: 4851) 
	{ 
  	Name 
    Advanced {  
      element {
        ... on element {
          __typename
        }
      }
       metadata {
        name
        value
      }
		} 
	} 
}`
