### ISSUE TITLE
[Bug]: some uploaded data object via mutation having white representation.

### ISSUE THREAD

**Issue by sys4cad** [pimcore/data-hub#523]
### Expected behavior

data objects in grid view should be displayed properly.

### Actual behavior

red boxed data has no data presentation.

![image](https://user-images.githubusercontent.com/9436271/165693843-4a2b6b54-5400-49bd-8372-526baa0d87ab.png)

However, I can see the its detail via versions.

![image](https://user-images.githubusercontent.com/9436271/165694236-6537bc94-9fc6-4755-a4df-3bc853fd4585.png)

If I tried just "publish" as following
![image](https://user-images.githubusercontent.com/9436271/165694362-8acb01b6-ec60-4c8e-bc41-483b5431519f.png)

ID(2735) got the right presentation of the data
![image](https://user-images.githubusercontent.com/9436271/165694511-96b62a86-a27a-4285-ba73-3ebd78162e84.png)

### Steps to reproduce

version 10.2

uploading object via graphql ( mutation )

**Comment by sys4cad** [comment]
I tested with 7 records those havnig error before.

![image](https://user-images.githubusercontent.com/9436271/165718808-394011df-edcc-4172-8489-21e1a013be98.png)

noticed that this time only 1 record having previous probem. (id: 2883)

As I check the backend table of pimcore, noticed that object_store_7 doesn't have id(2883)'s record

![image](https://user-images.githubusercontent.com/9436271/165719234-e2edff07-d662-4fcd-ac08-91716a109cd1.png)

other tables are having 7 rows.
![image](https://user-images.githubusercontent.com/9436271/165719392-ac9aeb37-c512-431a-9516-94d3d12eff7a.png)
![image](https://user-images.githubusercontent.com/9436271/165719476-20f9b72b-0f21-479e-a9cb-e56fe62b9a4a.png)

Is there any fix or work around for this symptom??

Any comment and advise will be highly appreciated.
Regards,
YS

**Comment by sys4cad** [comment]
I'd like to share my work around 
after digging UI packet via wireshark, I've noticed that saving with the latest version solved this symptom.
Thus I wrote one Action code as following

![image](https://user-images.githubusercontent.com/9436271/165891043-0799a216-a37e-4992-9df6-35d6d545ee5e.png)

**Comment by sys4cad** [comment]
eventually,  I've noticed the root cause of this symptom is unique constraint violation of the data.
since mutation api doesn't report this error, data is loaded in the correspondant tables. ( except object_store_{id} table )

IMO, mutation API should give a error message instead of success return.

**Comment by mcop1** [comment]
@sys4cad thanks for investigating the problem. Would it be possible for you to upload a small excel, csv, ... file for us to reproduce the issue? Would be appreciated!

Best regards

**Comment by sys4cad** [comment]
reprocing the issue is simple.
define sample class with unique constaint such as SSN.  ( sample class w/ name & SSN (unique check) )

load sample class via mutation.
{  Key: 111, David, 1111 } and { key: 112 , Michael, 1111 }

then both David and Michael is loaded via mutation as they are having unique key. ( bug )
[result] grid view having white row ( Michael )  
            object_store_{class} havnig 1 row  since unique constratint of SSN is violated.

[recommend]  Michael shouldn't be loaded via mutation.
   mutation API should return unique violation error of SSN rather than success message with object id.
