### ISSUE TITLE
[Documents] Support for fetching linked translations

### ISSUE THREAD

**Issue by dvesh3** [pimcore/data-hub#528]
### Improvement description

Add support for fetching linked translations from document:
![image](https://user-images.githubusercontent.com/5137917/166651722-8366a337-1dcb-4ab0-a2c6-422b4a153541.png)

**Comment by neusta-diaspero** [comment]
Hey @dvesh3. Thank you so far for the improvement. Do you see the possibility of returning only the desired language variant by considering the `defaultLanguage` parameter instead of the list of all translations?

**Comment by dvesh3** [comment]
> Hey @dvesh3. Thank you so far for the improvement. Do you see the possibility of returning only the desired language variant by considering the `defaultLanguage` parameter instead of the list of all translations?
 
Good point. I incorporated the changes in the PR to request a language variant. https://github.com/pimcore/data-hub/pull/529/commits/b34c65801459d1d0df6c9dcc886329ca86793c26

**Comment by neusta-diaspero** [comment]
Fits perfectly. Thank you @dvesh3.

**Comment by pimcoreneusta** [comment]
Hey @dvesh3 ,
Hello @mcop1 ,

it seems like the related/translated document does not allow fetching content via fields **elements** and **editables** by **target** any more …

![image](https://user-images.githubusercontent.com/99489645/178522863-13d8bb53-9373-4aa5-bdf3-506e450b4ed8.png)

I simply copied and pasted a new language variant of a existing headless document and allowed access to documents on existing GraphQL Endpoint in current Pimcore Demo. 

Could you please double check?
