### ISSUE TITLE
Support Fieldcollection queries

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/data-hub#53]

**Comment by NiklasBr** [comment]
@weisswurstkanone 
I have a stupid question, but how is this supposed to work? Do you have any examples?

**Comment by weisswurstkanone** [comment]
Basically just as for relations. Note that currently you cannot restrict access to specific fieldcollection attributes.

Example:
{
  getFctest(id: 99) {
    id
    fcfield {
      ... on fieldcollection_fctype {
        fcinputfield
      }
    }
  }
}


where fctype is the key of the fieldcollection and fcinputfield an input field inside your field collection.

Result:
{
  "data": {
    "getFctest": {
      "id": "99",
      "fcfield": [
        {
          "fcinputfield": "123"
        },
        {
          "fcinputfield": "456"
        }
      ]
    }
  }
}

**Comment by NiklasBr** [comment]
So, on the data object class `fcinputfield` is the name in the dataObject class or the name in the fieldCollection? Note that the Schema does not expose this information. A bug?

**Comment by weisswurstkanone** [comment]
fcinputfield is in the fieldcollection

![image](https://user-images.githubusercontent.com/6142086/62869084-68b37680-bd17-11e9-8b60-1bff3b21ad0f.png)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/62869123-7a951980-bd17-11e9-84d3-cedfd1d210fa.png)

**Comment by weisswurstkanone** [comment]
![image](https://user-images.githubusercontent.com/6142086/62869141-841e8180-bd17-11e9-8e99-0d668188639e.png)

**Comment by NiklasBr** [comment]
Oh, I think I get it now. I'll try to add some docs. Thanks!

**Comment by weisswurstkanone** [comment]
I guess it would make sense to provide a sample configuration file for the new pimcore demo once it is available.
