### ISSUE TITLE
[Feature]: Allow to save Defintions with APP_DEBUG=false

### ISSUE THREAD

**Issue by ThomasGravel** [pimcore/data-hub#531]
### Feature description

We need to save the data-hub config with APP_DEBUG=false, because the workflow engine sends emails to the user only if the APP_DEBUG=false.

We now overwrite the isWriteable function in the Configuration.php, but I think this is not the solution.

**Comment by mcop1** [comment]
Please take a look here, section "Configuration Storage Locations & Fallbacks"
https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html

Does this solve your problem?

**Comment by mcop1** [comment]
Closed due to inactivity, feel free to reopen the issue if needed.

**Comment by ThomasGravel** [comment]
This does not solve our problems. We want to save and edit the data-hub on the production system with APP_DEBUG=false. We need APP_DEBUG=false, because the workflow engine does not send emails if we set APP_DEBUG=true. We have some editor users, that must have the possibility to change the settings of the data-hub.

**Comment by mcop1** [comment]
Did you try to set 

`PIMCORE_WRITE_TARGET_DATA_HUB=settings-store` 

in your env file? 
This should make the configs writeable without APP_DEBUG=true, just like it is described in the documentation.

**Comment by mcop1** [comment]
Maybe you can take a look here too
https://github.com/pimcore/data-hub/issues/543#issuecomment-1150950075

**Comment by mcop1** [comment]
@ThomasGravel have you been able to solve your problem?

**Comment by betterapp** [comment]
> Did you try to set
> 
> `PIMCORE_WRITE_TARGET_DATA_HUB=settings-store`
> 
> in your env file? This should make the configs writeable without APP_DEBUG=true, just like it is described in the documentation.

this does not work for me in PIM 11

**Comment by maxihaindl** [comment]
> Did you try to set
> 
> PIMCORE_WRITE_TARGET_DATA_HUB=settings-store
> 
> in your env file? This should make the configs writeable without APP_DEBUG=true, just like it is described in the documentation.

Does not work for me either on Pimcore version 11.2.6

**Comment by seybsen** [comment]
```
pimcore_data_hub:
    config_location:
        data_hub:
            write_target:
                type: settings-store
```

works for Pimcore 11, but still doesn't allow to create new configurations without `APP_DEBUG=1`

**Comment by marko91** [comment]
@mcop1 the `PIMCORE_WRITE_TARGET_DATA_HUB=settings-store` doesnt work anymore on the newer Pimcore versions, is there any alternative to be able to save data-importer configurations on production env while having APP_DEBUG=false

I have found that setting the below in config.yaml does enable the "Add configuration" button on the DataHub, but the existing data-importer configs cannot be saved 

```
pimcore_data_hub:
    config_location: 
        data_hub:
            write_target:
                type: 'settings-store'
```

**Comment by mcop1** [comment]
Hello @marko91,
as far as I can see everything should be documented [here](https://pimcore.com/docs/platform/Datahub/Deployment) and also [here](https://pimcore.com/docs/platform/Pimcore/Deployment/Configuration_Environments/#page_Configuration-Storage-Locations-Fallbacks). 

The reason for your problem could be that some configurations are stored as yaml configuration and some are stored in the settings store. If you set the `write_target` to the settings store, then you are not able to save configurations stored in yaml configuration files.

**Comment by ziggurad** [comment]
Hi,

I have a similar problem and despite reading the documentation I don't know how to solve it.

Locally everything works fine. In the production environment I can't delete or edit (save) the configuration.

What should the configuration be to be able to edit the endpoint on prod?
