### ISSUE TITLE
[Bug]: Query filters not working with logical operators and object bricks attributes

### ISSUE THREAD

**Issue by niklavskatlaps** [pimcore/data-hub#532]
### Expected behavior

We should be able to use logical operators in filter conditions to filter objects by attributes defined in object bricks.

### Actual behavior

We get an error when using logical operators in filter conditions to filter objects by attributes defined in object bricks:

```
"An exception occurred while executing 'SELECT object_8.o_id as o_id, object_8.o_type as o_type FROM object_8 WHERE ( (\n            (\n                SELECT `read` from `plugin_datahub_workspaces_object`\n                WHERE `plugin_datahub_workspaces_object`.configuration = 'products'\n                AND LOCATE(CONCAT(`object_8`.o_path,`object_8`.o_key),`plugin_datahub_workspaces_object`.cpath)=1\n                ORDER BY LENGTH(`plugin_datahub_workspaces_object`.cpath) DESC\n                LIMIT 1\n            )=1\n            OR\n            (\n                SELECT `read` from `plugin_datahub_workspaces_object`\n                WHERE `plugin_datahub_workspaces_object`.configuration = 'products'\n                AND LOCATE(`plugin_datahub_workspaces_object`.cpath,CONCAT(`object_8`.o_path,`object_8`.o_key))=1\n                ORDER BY LENGTH(`plugin_datahub_workspaces_object`.cpath) DESC\n                LIMIT 1\n            )=1\n        ) AND  ( ((`price` = '111') )  OR  ((`price` = '999') )  )  AND  object_8.o_type IN ('object','folder','variant')) AND object_8.o_published = 1':\n\nSQLSTATE[42S22]: Column not found: 1054 Unknown column 'price' in 'where clause'"
```
![image](https://user-images.githubusercontent.com/22444018/168093405-fb9691e1-355f-4c12-962a-4ea2d275aeed.png)

The same query works just fine if we use any of the object attributes instead:

![image](https://user-images.githubusercontent.com/22444018/168093113-17eca5c1-145c-4b30-997f-a290815c0b40.png)

It also works if we don't use logical operators and use an attribute from object bricks:

![image](https://user-images.githubusercontent.com/22444018/168093581-5f87632e-ba0f-4b58-a9fd-9ed83a5d6725.png)

### Steps to reproduce

1) Create 2 test products with in total 3 properties each - 2 regular object attributes `name` and `sku`, and 1 object bricks attribute `price`:

    ![image](https://user-images.githubusercontent.com/22444018/168091414-c303d8a3-784c-4479-a84f-0548540f9b7b.png)
    ![image](https://user-images.githubusercontent.com/22444018/168091739-7cde6f26-0c99-4646-b6cb-c84eb1717534.png)
    ![image](https://user-images.githubusercontent.com/22444018/168091897-28e4433a-9582-4b75-b71c-457236735081.png)
    ![image](https://user-images.githubusercontent.com/22444018/168091977-29f1cd02-d522-4005-8d5d-0ec3d637848d.png)

2) Define a DataHub query schema with all the fields:

    ![image](https://user-images.githubusercontent.com/22444018/168095205-0bf01883-c7e7-46ad-8a77-5d23df320e0a.png)

3) Use this query to retrieve a filtered car listing: 

    ```
    query getCarListing {
      getCarListing(filter: "{\"$or\": [{\"price\": 111}, {\"price\": 999}]}") {
        edges {
          node {
            name
            sku
            price
          }
        }
        totalCount
      }
    }
    ```
    ![image](https://user-images.githubusercontent.com/22444018/168093405-fb9691e1-355f-4c12-962a-4ea2d275aeed.png)

4) Observe that the same query with the following filter conditions works as expected:

      - Filter that uses an object brick attribute without logical operators: `filter: "{\"price\": 111}"`
      - Filter that uses a regular object attribute with logical operators: `filter: "{\"$or\": [{\"sku\": \"test-car-1\"}, {\"sku\": \"test-car-2\"}]}"`
      

Please let me know if any other information is needed and/or there is anything I can do to speed up the process of resolving this issue.

**Comment by mcop1** [comment]
@niklavskatlaps thanks, I can reproduce the problem at my end, seems there is an issue with adding the joins somewhere around here
https://github.com/pimcore/data-hub/blob/e755682ca84dc0209b9f5b5a32e174b7f68bdc89/src/GraphQL/Helper.php#L37 
We will take a look into it
