### ISSUE TITLE
[Bug]: Fetching asset in format WebP doesn't work 

### ISSUE THREAD

**Issue by neusta-diaspero** [pimcore/data-hub#541]
### Expected behavior

Hey,

following the documentation of Pimcore Data Hub as followed ...
https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Request

... I'm **expecting Data Hub to return assets in format WebP**, see: https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Response

![Screenshot from 2022-06-03 11-36-29](https://user-images.githubusercontent.com/36693399/171829828-37b1f50b-040f-483b-8e27-0f55d8aca254.png)

### Actual behavior

Instead the Data Hub Endpoint **returns assets in format JPEG only** ...

![Screenshot from 2022-06-03 11-37-07](https://user-images.githubusercontent.com/36693399/171829873-5d521824-679a-46e0-bb72-4c3837291339.png)

### Steps to reproduce

Use documented request as followed ...
https://pimcore.com/docs/data-hub/current/GraphQL/Query/Query_Samples/Sample_GetAsset.html#page_Request

... and send it via GraphQL Playground to this endpoint:
https://demo.pimcore.com/pimcore-datahub-webservices/explorer/products?apikey=6332aa5e6d3d6c0be31da2a8b3442113 

Any ideas or hints welcome.

**Comment by neusta-diaspero** [comment]
Hey @mcop1 ,

any update or hints for a workaround on that?

Kind Regards,
Claudio.

**Comment by mcop1** [comment]
Hello @neusta-diaspero , 
at the moment pimcore is returning the thumbnails in jpeg format by intent, please see the discussion/comment here:
https://github.com/pimcore/pimcore/discussions/10430#discussioncomment-1396465 

But, I think it would make sense to offer a method that returns the thumbnail in a specific format. That needs to be implemented in pimcore/pimcore and after that we can add it as queryoption for GraphQL. I created an issue accordingly: https://github.com/pimcore/pimcore/issues/12484


The documentation needs to be updated, there is already an issue for that (https://github.com/pimcore/data-hub/issues/503).
