### ISSUE TITLE
[Bug]: Mutation - cannot use wysiwyg field inside Local Collector

### ISSUE THREAD

**Issue by JohnFromPrague** [pimcore/data-hub#542]
### Expected behavior

I can drag&drop wysiwyg field into LocaleCollector

### Actual behavior
When I drag&drop wysiwyg field into Local Collector it's not allowed (for other field types it works).
![image](https://user-images.githubusercontent.com/18370349/172150465-dc750698-3d41-4eea-bf05-1a340db83861.png)

**Comment by mcop1** [comment]
@JohnFromPrague for me it is working. Could you try to double click the WYSISWYG field on the left side of the schema configuration dialog?
![image](https://user-images.githubusercontent.com/89011527/173812785-2578e73b-30a8-4c14-a5d7-5e9b8a34a926.png)

Example query
![image](https://user-images.githubusercontent.com/89011527/173812890-1f48b167-759c-44f9-9b09-8d4469f17fee.png)

**Comment by JohnFromPrague** [comment]
Hi @mcop1 , based on your screenshot you do not use Locale Collector for wysiwyg (you do not use localized wysiwyg at all).

So how I said in first comment, the problem is when you wanna use wysiwyg inside Locale Collector. I am attaching one more screenshot to have better overview what is the problem.

![image](https://user-images.githubusercontent.com/18370349/174154946-5583aa77-c38d-45b4-afae-80f85ac7577a.png)

You can find Locale Collector under Other section
![image](https://user-images.githubusercontent.com/18370349/174155269-505919e0-34b6-4390-a161-bc74eec3e4ec.png)

**Comment by mcop1** [comment]
@JohnFromPrague sorry, my fault. There is definitely something wrong, we will have a look.

**Comment by mcop1** [comment]
@JohnFromPrague Hello, 
I linked as small bugfix for that, do you want to give it a try? Then we could even include it in the patch tomorrow. Would be appreciated.
