### ISSUE TITLE
[Bug]:  DataHub "add configuration" is disabled...

### ISSUE THREAD

**Issue by sys4cad** [pimcore/data-hub#543]
### Expected behavior

add configuration should be enabled

### Actual behavior

![image](https://user-images.githubusercontent.com/9436271/172795625-0f44c9ad-8e91-44c2-bc21-0fc5f4ccfd66.png)

### Steps to reproduce

any hint for this symptom?

- I've restarted the apache but it doesn't help :(

**Comment by NiklasBr** [comment]
It's a new thing, since a while ago settings in Production environments are disabled by default, [see documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html#page_Production-environment-with).

**Comment by sys4cad** [comment]
> It's a new thing, since a while ago settings in Production environments are disabled by default, [see documentation](https://pimcore.com/docs/pimcore/current/Development_Documentation/Deployment/Configuration_Environments.html#page_Production-environment-with).

I've added PIMCORE_WRITE_TARGET_CUSTOM_REPORTS=settings-store in .env  
and restarted the apache2 . symptom is the same :(


Any hint??

**Comment by NiklasBr** [comment]
`PIMCORE_WRITE_TARGET_CUSTOM_REPORTS` is for Custom Reports, for Data Hub you need `PIMCORE_WRITE_TARGET_DATA_HUB`.

Also, no need to restart Apache, clear the Symfony cache instead.

**Comment by sys4cad** [comment]
Thanks for your great help.  
I would like to recommend adding PIMCORE_WRITE_DATA_HUB to Available environment variables. 
Please close this issue.

**Comment by mcop1** [comment]
@NiklasBr Thanks for helping
