### ISSUE TITLE
[Improvement] Support for multiple API keys per endpoint

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#545]
### Improvement description

In certain cases, it makes sense to have multiple API keys per endpoint, e.g. when providing the same data to several consumers, but you'd like to have the possibility to control the access individually per consumer.

As a simple solution I'd propose a multi-line field for the API key, where you can add a key per line.

**Comment by mcop1** [comment]
- Use multiline or maybe tag field for multiple api keys
- The "generate api key" button should add a key to the list
- Check all references of api-key, e.g.
https://github.com/pimcore/data-hub/blob/f57cbedb752b80a4b7027c5f65b82abfda9d8849/src/Service/CheckConsumerPermissionsService.php#L43
- check unit tests
