### ISSUE TITLE
[Bug]: Missing filter in new version - Internal Server Error

### ISSUE THREAD

**Issue by danielerne** [pimcore/data-hub#564]
### Expected behavior

Filter like {"filter": "[{\"o_id\": \"5588\"}]"} get a result

### Actual behavior

A message for internal server error

### Steps to reproduce

Add a query filter like this: {"filter": "[{\"o_id\": \"5588\"}]"}

We have an app in production outside and uses this functionality to get some specific items. Currently we can't update.
It worked on datahub version 1.2.4.

Maybe someone can guide us to the changed line on datahub code?

**Comment by danielerne** [comment]
I did a workaround by adding this code on line 36 in Helper.php Class:

`
if(is_array($filter)) {
     $filter = $filter[0];
}
`

**Comment by robertSt7** [comment]
@danielerne  I also tested it with version 1.2.4 and it does not work for me. But if I remove the [ ] then it works fine, could you please try that too? Thanks

**Comment by danielerne** [comment]
@robertSt7 Yes, when removing the brackets it works. But we have a productive live application on the AppStores with this filter. So I needed to change it in the helper class directly on server side.

**Comment by robertSt7** [comment]
@danielerne Could you please send me your error message? Thank you

**Comment by robertSt7** [comment]
We are closing the ticket due to inactivity. But you can always reply and we will take a look at it again.
