### ISSUE TITLE
[Bug]: Two fields with same name can not be provided by Datahub API

### ISSUE THREAD

**Issue by mmodmmod** [pimcore/data-hub#568]
### Expected behavior

I want to configure a DataHub API and make a field of the ClassDefinition or two different Object Bricks available to fetch via this API. Therefore, they should have different names in the DataHub-Schema-Definition, but they have not, since their names are the same. 

### Actual behavior

There is a problem with DataHub when there are fields that have the same name either one on the side of the ClassDefinition  and on in a linked Object Brick or in two different Object Bricks for example. GraphQL is only able send one of them. GraphQL seems to pick them rather "randomly" (I suspect it gives preference to the ClassDefinition and otherwise to the order added to the schema). 

![image](https://user-images.githubusercontent.com/92800450/178744254-8bd56a5b-c75a-412d-a964-80de078a8136.png)

![image](https://user-images.githubusercontent.com/92800450/178744420-32c8dc77-564a-4ea1-b968-151e99116622.png)

As a work-around, would it be possible to enable the previous feature that you can add the whole object brick to the Schema definition (as it used to be)? Otherwise, I am not familiar with a different solution, since the option "[NameOfObjectBrick].[NameOfField]" would (to my knowledge) not be supported by GraphQL itself. 

### Steps to reproduce

Configure a classdefinition with a name, an (or two) object bricks which has a field with the same name and try to add them to the schema of a DataHub configuration.

**Comment by longwave** [comment]
You can work around this by using the alias feature and adding a unique alias for each duplicated field name, but it's very tedious to set up and maintain when you have a large number of fields.

**Comment by mmodmmod** [comment]
Thank you for this advice, it is a solution for my problem! 

For anybody else reading this issue, it works via the aliasing on the DataHub side not the GraphQL one. 


![image](https://user-images.githubusercontent.com/92800450/179466386-3df1c5d2-0354-439a-b67e-c64a885f4552.png)


![image](https://user-images.githubusercontent.com/92800450/179466841-a47566a5-7ac1-4264-b266-af8f0bdefec0.png)

**Comment by mcop1** [comment]
@mircomalik Adding an alias is the right approach for now, thanks for adding an example. 
I created an improvement ticket, maybe we can support GraphQL aliases in the future: https://github.com/pimcore/data-hub/issues/571

**Comment by mmodmmod** [comment]
> @mircomalik Adding an alias is the right approach for now, thanks for adding an example. I created an improvement ticket, maybe we can support GraphQL aliases in the future: #571

My pleasure! Yeah, I guess that would be good!
