### ISSUE TITLE
[Bug]: Can't fetch data of editables for documents with inheritance

### ISSUE THREAD

**Issue by neusta-diaspero** [pimcore/data-hub#570]
### Expected behavior

I expect editables and their content on documents or headless documents that have been pasted via inheritance (with Content-Master Document) to be exposed via GraphQL.

![image](https://user-images.githubusercontent.com/36693399/179167682-f16fd9c1-7cc3-4fad-b126-8a3862cd4ec3.png)

### Actual behavior

**Documents or headless documents that have been copied and pasted using inheritance (setting a Content-Master Document) do not expose their content and editables via GraphQL.** 

Picture below is showing query and response for:
1.  "original" document and its editables, 
2. pasted document not using inheritance (see "paste") showing same editables and 
3. pasted document using inheritance (see "paste_inheritance") showing empty field editables

![image](https://user-images.githubusercontent.com/36693399/179166863-e62192e8-09c0-4504-b50e-81bf3bfe1e40.png)

Remark: Content and editables are getting exposed only when they are overwritten in copied document with inheritance.

### Steps to reproduce

In Pimcore Demo …

- Copy a document e.g. "Data Quality" (ID: 193)
- Paste this document using inheritance (of structure and content)
- Try to query for pasted document and its editables via GraphQL
- Field **editables is empty**

**Comment by mcop1** [comment]
@neusta-diaspero Again, that´s something we need to support in the pimcore repository first. I created a corresponding issue for that:
https://github.com/pimcore/pimcore/issues/12762
