### ISSUE TITLE
[Bug]: GraphQL Query For Multilingual Classification Store Field Is Not Working !

### ISSUE THREAD

**Issue by kumar2112** [pimcore/data-hub#583]
### Expected behavior

Query should return specified language data.As we are writing query 
{
  getTestClass(id: 10439) {
    Name
    key
    Dictionaries(language: "ja_JP") {
      id
      name
      description
      features {
        __typename
        ... on csFeatureInput {
          type
          id
          name
          description
          text
        }
        ... on csFeatureSelect {
          type
          id
          name
          description
          selection
        }
        ... on csFeatureDate {
          type
          id
          name
          description
          date
        }
        ... on csFeatureBooleanSelect {
          type
          id
          name
          checked
          description
        }
        ... on csFeatureTime {
          id
          name
          description
          type
          time
        }
        ... on csFeatureMultiselect {
          id
          name
          description
          type
          selections
        }
      }
    }
  }
}

As you can see in query we have sent the language ja_JP as language param. It should return all the classification store data of requested language but its returning data of default language always.

### Actual behavior

Its not returning the speicified language data .

### Steps to reproduce

1. Create an object with localized  classification store.
2. Set up a graphQL for that class.
3. Query the classification data as give in below screen shot
{
  getTestClass(id: 10439) {
    Name
    key
    Dictionaries(language: "ja_JP") {
      id
      name
      description
      features {
        __typename
        ... on csFeatureInput {
          type
          id
          name
          description
          text
        }
        ... on csFeatureSelect {
          type
          id
          name
          description
          selection
        }
        ... on csFeatureDate {
          type
          id
          name
          description
          date
        }
        ... on csFeatureBooleanSelect {
          type
          id
          name
          checked
          description
        }
        ... on csFeatureTime {
          id
          name
          description
          type
          time
        }
        ... on csFeatureMultiselect {
          id
          name
          description
          type
          selections
        }
      }
    }
  }
}

**Comment by deepakkumarhm7** [comment]
@dvesh3 Can u please look on this, we are also facing same issue?

**Comment by dvesh3** [comment]
Moved to correct repository. We'll take a look.

**Comment by kumar2112** [comment]
We are facing this issue in 6.9.*

**Comment by dvesh3** [comment]
Pimcore 6 is not supported anymore, only LTS. please see https://github.com/pimcore/pimcore#supported-versions
