### ISSUE TITLE
[Bug]: Adding class with Update or Create to mutation schema

### ISSUE THREAD

**Issue by robertSt7** [pimcore/data-hub#586]
### Expected behavior

Get an error when check Create or Update
![image](https://user-images.githubusercontent.com/104770750/183858716-0104777b-afc5-4724-8997-bebd13c6d182.png)

### Actual behavior

Get no error

### Steps to reproduce

- create a GraphQL config
- add a class to the mutation schema
- check Update or Create
- open iExplorer (playground)

**Comment by mcop1** [comment]
Was a problem with a custom event subscriber, couldn´t reproduce anymore.
