### ISSUE TITLE
[Bug]: Docs site unavailable

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#594]
### Expected behavior

Opening the Data Hub docs from https://pimcore.com/docs/pimcore/current/ should be possible

### Actual behavior

![image](https://user-images.githubusercontent.com/279826/185605483-dc4980fa-43ab-45fe-9329-32c78ed38285.png)

### Steps to reproduce

See above

**Comment by brusch** [comment]
Thanks for reporting - fixed 😊
