### ISSUE TITLE
Make Resolvers injectable to the container and load them from the container

### ISSUE THREAD

**Issue by dpfaffenbauer** [pimcore/data-hub#6]
The intention should be quite clear: It should be possible to inject whatever I want to those resolvers.

https://github.com/pimcore/data-hub/tree/db4379af8ac087b9f063437d3b388c86c4ba2442/src/Pimcore/Bundle/DataHubBundle/GraphQL/Resolver

**Comment by weisswurstkanone** [comment]
Note that a resolver belongs to your own implementation of your own custom datatype. How you implement it is up to you. Will add some documentation on how to support a custom datatype, though.

The only reason for that kind of approach is to make the query schema serialable (remove all closures in preparation of https://github.com/pimcore/data-hub/issues/14, also see https://github.com/pimcore/data-hub/commit/db4379af8ac087b9f063437d3b388c86c4ba2442).
