### ISSUE TITLE
[Feature]: Being able to filter by tags

### ISSUE THREAD

**Issue by Iblis** [pimcore/data-hub#611]
### Feature description

Right now data-hub allows filtering on queries using Pimcore's webservice filter logic.
I was not able to find a way to use this to filter for tags.
Looking at https://pimcore.com/docs/pimcore/current/Development_Documentation/Best_Practice/Using_Tags_for_Filtering.html it seems to be straightforward to implement explicit tag-filters for queries.
Not sure though how to allow configuration for options like "considerChildTags" true/false

**Comment by mazorg** [comment]
Hey @mcop1 any estimation on when will this feature will be available on the main version?

**Comment by mcop1** [comment]
Hello @mazorg ,
sorry, I can´t tell you a date right now. Currently we are working on Pimcore 11 and it should be released soon. Right after that we will release the compatible versions of our bundles, including data-hub.
