### ISSUE TITLE
Rethink naming conventions

### ISSUE THREAD

**Issue by weisswurstkanone** [pimcore/data-hub#63]

**Comment by fashxp** [comment]
maybe a good source: https://graphqlmastery.com/blog/graphql-best-practices-for-graphql-schema-design 

> It is common good practice to use camelCase for your fields and pascalCase for the names of types. I find also useful to name for example input types like this:
`<action><type>Input`
`<action>` is Create, Update or Delete and <type> is the name of the type or entity, which is being updated.

**Comment by fashxp** [comment]
another thing: 
It seems to be best practise that mutations should only ever have one input argument. That argument should be named input and should have a non-null unique input object type. 

see also:
https://blog.apollographql.com/designing-graphql-mutations-e09de826ed97
https://medium.com/graphql-mastery/json-as-an-argument-for-graphql-mutations-and-queries-3cd06d252a04
