### ISSUE TITLE
Support Calculated values datatype

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#66]
@weisswurstkanone Do you have any internal progress on this? We are considering starting on this feature because we have a use case for it.

**Comment by weisswurstkanone** [comment]
Currently not top priority. Please go ahead!
What is your plan regarding the schema query type?

**Comment by NiklasBr** [comment]
Thanks!

No plans regarding schema queries

**Comment by weisswurstkanone** [comment]
Maybe a scenario for a custom operator ?
