### ISSUE TITLE
[Bug]: Use t() method for operator text

### ISSUE THREAD

**Issue by mcop1** [pimcore/data-hub#674]
### Improvement description

Right now we apply the default text directly, therefore it can´t be translated, e.g. https://github.com/pimcore/data-hub/blob/ec5e1bd1ee89e8461a223dc69c05596fca28164b/src/Resources/public/js/queryoperator/Merge.js#L24 
Use the t() method instead and make sure to add translations to `admin.en.yaml`.

**Comment by lukmzig** [comment]
Translations for texts are generated but the merge operator label was changed in the wrong place
