### ISSUE TITLE
[Bug] Make sure tests run through

### ISSUE THREAD

**Issue by fashxp** [pimcore/data-hub#705]
### Expected behavior

https://github.com/pimcore/data-hub/actions/runs/4339566434/jobs/7577283786

### Actual behavior

.

### Steps to reproduce

.

**Comment by mcop1** [comment]
Tests fail because of a bc break, mentioned here https://github.com/pimcore/data-hub/pull/702#issuecomment-1449588997 - there is a draft pr (https://github.com/pimcore/pimcore/pull/14486) for that, already keeping my eye on it

**Comment by mcop1** [comment]
BC break was fixed in the current Alpha version of 11, tests are working again.
