### ISSUE TITLE
[Bug]: Using PIMCORE_CONFIG_STORAGE_DIR_DATA_HUB leads to an error

### ISSUE THREAD

**Issue by robertSt7** [pimcore/data-hub#740]
### Expected behavior

The config will be created
see https://github.com/pimcore/data-hub/pull/738

### Actual behavior

An error is thrown

### Steps to reproduce

- Add `PIMCORE_CONFIG_STORAGE_DIR_DATA_HUB=/var/www/html/var/config/datahub` to the Environment-file
- Try to create a data-hub config

Possible solutions:
- add the functionality

**Comment by dvesh3** [comment]
Fixed by  #784
