### ISSUE TITLE
[Bug]: Cannot configure permissions

### ISSUE THREAD

**Issue by rjankiew** [pimcore/data-hub#753]
### Expected behavior

All permissions can be set up in roles and users tabs, like so:
![obraz](https://github.com/pimcore/data-hub/assets/89988908/61ce1079-4021-4abe-bfa5-0aaf13b9d4ec)

### Actual behavior

On some environments, one of permissions is not visible:
![obraz](https://github.com/pimcore/data-hub/assets/89988908/04c94d9d-f072-4a25-b3e7-d70bfa0fb1df)

This results in users without admin privileges not being able to be set up in a way, that allows them to see the data-hub menu entry. Clearing app/pimcore cache, reinstalling assets does not help.

### Steps to reproduce

Open up the roles or users configuration, open the datahub permissions dropdown. I'm not sure what causes the difference between various installations.

**Comment by toddb02** [comment]
@rjankiew We encountered this as well and just adding the missing record to the `users_permission_definitions` database table fixed it for us.

```
INSERT INTO `users_permission_definitions` (`key`, `category`) VALUES
('plugin_datahub_config', 'Datahub');
```

**Comment by dvesh3** [comment]
@toddb02 please make sure migration [`Version20211108160248`](https://github.com/pimcore/data-hub/blob/2261b177814d1756c6082b415c7dcd52c52e4a0a/src/Migrations/PimcoreX/Version20211108160248.php#L56) executed successfully. It updates the category for the existing permissions to show up in the bundle permissions section.

**Comment by dvesh3** [comment]
@toddb02 any new findings?

**Comment by toddb02** [comment]
@dvesh3 The migration you referenced ran successfully in each environment and added the record mentioned in this thread (`plugin_datahub_config`) on local environments. It just didn't add that one record in dev or production application env's. The other 3 permission areas were added in all environments.

**Comment by dvesh3** [comment]
Thanks for confirmation!! then I don't see a problem in migration as https://github.com/pimcore/data-hub/blob/2261b177814d1756c6082b415c7dcd52c52e4a0a/src/Migrations/PimcoreX/Version20211108160248.php#L60 adds category to `plugin_datahub_config`
