### ISSUE TITLE
Access-Control-Allow-Origin

### ISSUE THREAD

**Issue by brainsbucket** [pimcore/data-hub#76]
First, thanks for this bundle it will be a great feature for pimcore !

Is it possible to add Access-Control-Allow-Origin in order to test on local frontend dev ?

**Comment by brainsbucket** [comment]
I have fix this by extending Pimcore\Bundle\DataHubBundle\Controller\WebserviceController and add
```
header('Access-Control-Allow-Origin: *');
header('Access-Control-Allow-Methods: GET, POST, PATCH, PUT, DELETE, OPTIONS');
header('Access-Control-Allow-Headers: Origin, Content-Type, X-Auth-Token');
```
to the webonyxAction

**Comment by julmot** [comment]
I would suggest to reopen this ticket and solve this in data hub itself. This is nothing very specific, it's a common approach to host decoupled frontend applications on different domains. On DEV and on PROD.

For example my decoupled frontend applications always run on localhost in DEV, the backends on XXX.local. Even on PROD we can either have pimcore.XXX.com and XXX.com serving as frontend or a different TLD or port.

I never had an approach where CORS requests wasn't needed.

**Comment by weisswurstkanone** [comment]
@julmot , can you create a PR ?

**Comment by julmot** [comment]
@weisswurstkanone Please see https://github.com/pimcore/data-hub/pull/148
