### ISSUE TITLE
[Bug]: Mutation of an advanced relation within a brick doesn't store metadata correctly

### ISSUE THREAD

**Issue by youwe-petervanderwal** [pimcore/data-hub#761]
### Expected behavior

Mutating an AdvancedManyToMany Relation data via GraphQL would update the relations as well as the metadata

### Actual behavior

The relations are updated, but all metadata fields are left blank. Debugging the database would show that the `fieldname` column of the `object_metadata_CAR` table contains `"TestBrick-testRelation"` instead of the expected `"testRelation"`.

### Steps to reproduce

- Create a DataObject definition and add a Objectbricks field (used `Car` in my example GraphQL)
- Create a Brick definition and add an Advanced ManyToManyObjectRelation (or ManyToManyRelation) (used `testRelation` as field name in my example GraphQL)
- Add a metadata column to this AdvancedManyToMany relation field (used `testColumn` in my example GrahpQL)
- Update the DataHub GraphQL schema to allow updating this brick field
- Run the following GraphQL mutation

```
mutation {
  updateCar(
    id: 81,
    input: {
      testRelation: [
        {
          type: "object",
          id: 267,
          metadata: [
            {
              name: "testColumn",
              value: "HelloWorld"
            }
          ]
        }
      ]
    }
  ) {
    success
    message
  }
}

```

**Comment by dvesh3** [comment]
Fixed by #762
