### ISSUE TITLE
[Bug]: Swagger not working for Datahub Simple Rest API

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/data-hub#769]
### Expected behavior

Hi,

I have followed the instructions here to install Datahub Simple Rest API

https://pimcore.com/docs/platform/Datahub_Simple_Rest/Installation/

Swagger should work as normal. For example in local development:

http://localhost/pimcore-datahub-webservices/simplerest/swagger

Should show me the swagger page.

 

### Actual behavior

However I get the following:

```
Failed to load API definition.
Fetch error: Internal Server Error /pimcore-datahub-webservices/simplerest/swagger-config
```

Here is the error from the network tab in chrome for:

http://localhost/pimcore-datahub-webservices/simplerest/swagger-config

`
{
    "type": "https:\/\/tools.ietf.org\/html\/rfc2616#section-10",
    "title": "An error occurred",
    "status": 500,
    "detail": "User Warning: $ref \"#\/components\/schemas\/\" not found for @OA\\Schema() in \\Pimcore\\Bundle\\DataHubSimpleRestBundle\\Controller\\EndpointController->treeItemsAction() in \/var\/www\/html\/vendor\/pimcore\/data-hub-simple-rest\/src\/Controller\/EndpointController.php on line 182",
    "class": "ErrorException",
    .....
`

### Steps to reproduce

Installed the following:

    "pimcore/data-hub": "^1.6",
    "pimcore/data-hub-simple-rest": "^2.0",
    "pimcore/pimcore": "^11.0",

Create a Simple Rest API

**Comment by fashxp** [comment]
thx for you report. it is a already known issue and will be fixed with next data-hub-simple-rest release. 
moved the issue to the correct repository.
