### ISSUE TITLE
[Bug]: Creating a new GraphQl fails but then Save

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/data-hub#770]
### Expected behavior

The GraphQl query should be created as normal.

### Actual behavior

The following error occurs:

```
Timestamp: Tue Jul 18 2023 18:12:10 GMT+0100 (British Summer Time)
Status: 0 | communication failure
URL: /admin/pimcoredatahub/config/list?_dc=1689700300219
Method: GET
Message: 
undefined
```

It seems like http://localhost/admin/pimcoredatahub/config/list?_dc=1689700300219&node=0 takes ages to load and then gets cancelled.

![image](https://github.com/pimcore/data-hub/assets/46787382/f8fec917-81f2-47c9-b6ea-c6acc1807aee)

However, in a separate page it loads after a while:

 
![image](https://github.com/pimcore/data-hub/assets/46787382/7fe94623-70d7-480d-abf8-04779c35bd3e)

So it actually saves. But I get that error every time I create a new request or save and existing one.

### Steps to reproduce

1. This is the version i'm using:

    "pimcore/data-hub": "^1.6",
    "pimcore/pimcore": "^11.0",

2. Set Configuration Storage to symfony-config:

https://pimcore.com/docs/platform/Datahub/Deployment#configuration-storage

3. Create a new GraphQl.

**Comment by dvesh3** [comment]
Seems to be an issue when Symfony container is building on save (only when the storage is `symfony-config`). 

@ayoob-lfc could you please try using `symfony-config` for other supported features e.g. `image thumbnails` to understand if this is really specific to data-hub or general issue on your end?

**Comment by ayoob-lfc** [comment]
Hi @dvesh3 your right, the same thing happened with thumbnails. Do you have any leads on why this issue occurs? Its with a fresh install of Pimcore Skeleton via Docker.

**Comment by ayoob-lfc** [comment]
Seems to be an issue when Symfony container is building on save (only when the storage is symfony-config)
