### ISSUE TITLE
[Bug]: Querying by fullpath gives internal server error

### ISSUE THREAD

**Issue by prateeksahus** [pimcore/data-hub#776]
### Expected behavior

should display the product data

### Actual behavior

Throws internal server error
`{
  "errors": [
    {
      "message": "Internal server error",
      "locations": [
        {
          "line": 3,
          "column": 5
        }
      ],
      "path": [
        "getCarListing",
        "edges"
      ]
    }
  ],
  "data": {
    "getCarListing": {
      "edges": null
    }
  }
}`
![Screenshot from 2023-07-28 19-00-25](https://github.com/pimcore/data-hub/assets/72745617/5a26956a-5421-424e-9d74-9e6de4ba4fee)

### Steps to reproduce

In pimcore go to the dathub section
open the graphql playground
Run the query
`{
  getCarListing(fullpaths: "/Product Data/Cars/ac cars/Cobra 427"){
    edges{
      node{
        id
      }
    }
  }
}`

**Comment by dvesh3** [comment]
Fixed by #778
