### ISSUE TITLE
Fix for the creates mutations

### ISSUE THREAD

**Issue by brainsbucket** [pimcore/data-hub#78]
The creates mutations are not working, this is due to a mistake in the class Pimcore\Bundle\DataHubBundle\GraphQL\Mutation\MutationType on line 186

replace : 
`call_user_func_array($resolver, [ $newInstance, $value, $args, $context, $info]);`

By

`call_user_func_array($resolver, [ $value, $args, $context, $info]);`

**Comment by dvesh3** [comment]
thanks a lot!
