### ISSUE TITLE
[Bug]: Can not use $gt, $lt... in filters for Object Bricks

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/data-hub#790]
### Expected behavior

GraphQl should give any success response

### Actual behavior

I get "Internal server error":

![image](https://github.com/pimcore/data-hub/assets/46787382/cef5ce6a-92c2-4de1-911d-59885cc689bc)

### Steps to reproduce

Create the following request for Cars:

```
# Write your query or mutation here
query {
  getCarListing(
    filter: "{\"priceInEUR\": {\"$gt\" :10}}"
  ) {
    edges {
      node {
        priceInEUR
      }
    }
  }
}
```

**Comment by kingjia90** [comment]
Looks like that object bricks are not supported at all in Query
See https://github.com/pimcore/data-hub/blob/1.x/doc/10_GraphQL/04_Query/05_DataObject_Queries.md#supported-data-types

**Comment by kingjia90** [comment]
```
# Write your query or mutation here
query {
  getCarListing(
    filter: "{\"productionYear\": {\"$gt\" :1980}}"
  ) {
    edges {
      node {
        priceInEUR
      }
    }
  }
}# Write your query or mutation here
``` 
would work just fine, so doesn't look having to do with $gt or so

Closing for the moment
