### ISSUE TITLE
[Feature]: Support "equals" filter

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#792]
### Feature description

https://github.com/pimcore/data-hub/blob/dc9862d8732d36102444f842fc0b97e8ee132d33/doc/10_GraphQL/04_Query/10_Filtering.md?plain=1#L3-L5

The webservice logic currently supports:

    $not
    $or
    $and
    $like

and:

    $gt
    $gte
    $lt
    $lte

Request to add:

    $eq

Which works like `=` comparison.

**Comment by abrenoch** [comment]
Hey just fyi this is already possible:

If `like` would be: `field: { '$like' : 'term' }`  
Equal would be: `field: 'term'`

**Comment by NiklasBr** [comment]
This is definitely not possible @abrenoch:

![image](https://github.com/pimcore/data-hub/assets/279826/6fae6cb0-f1ee-49e8-a2ef-2d841f490293)

![image](https://github.com/pimcore/data-hub/assets/279826/253aae3f-009a-40b9-912c-40d947f4b6b1)

**Comment by abrenoch** [comment]
@NiklasBr not like that it isn't!

You need to provide your query via the `filter` variable as a JSON string.

so `filter` would look something like:
`"{\"name\": \"Charger\"}"`

I can post some images if that might help, but I'm away from my dev environment for a couple days.

Edit:
![image](https://github.com/pimcore/data-hub/assets/2146139/374ba47d-fb4d-4b1e-aa88-e2c1237d33f8)

Though testing this matches both 'Charger' and 'charger', so maybe under the hood that is using a `like` operator regardless...
