### ISSUE TITLE
[Bug]: Sending parallel GraphQl mutation request cause 500 Internal Server Error

### ISSUE THREAD

**Issue by ayoob-lfc** [pimcore/data-hub#793]
### Expected behavior

Should get status 200 when sending parallel GraphQl request.

### Actual behavior

I get a 500 Internal Server Error, and the following in dev.log

php.CRITICAL: Fatal Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) {"exception":"[object] (Symfony\\Component\\ErrorHandler\\Error\\OutOfMemoryError(code: 0): Error: Allowed memory size of 268435456 bytes exhausted (tried to allocate 20480 bytes) at /var/www/html/vendor/pimcore/data-hub/src/Configuration.php:152)"} []

### Steps to reproduce

Create multiple large GraphQl mutation request.
Send them all in one go.
You will get 500 Internal Server error.

**Comment by ayoob-lfc** [comment]
FYI if I add the following:

```
        ini_set('memory_limit', '-1');
```

Just before the line:

https://github.com/pimcore/data-hub/blob/dc9862d8732d36102444f842fc0b97e8ee132d33/src/Configuration.php#L151

The error goes away!

**Comment by kingjia90** [comment]
What happens when removing 
https://github.com/pimcore/data-hub/blob/ce780dd420818e49914da373fb869f8865b5060c/src/Configuration.php#L151-L153
?

This encode/decode looks unnecessary and doesn't change the outcome

**Comment by dvesh3** [comment]
@kingjia90 yes, not necessary it seems since we decode it already as associative on save https://github.com/pimcore/data-hub/blob/0550084b4dc5be615dd161512cfee308ee9def35/src/Controller/ConfigController.php#L415

Also on import https://github.com/pimcore/data-hub/blob/6eb04e355b1093e892a432f8e7d4bf435fe7237a/src/Service/ImportService.php#L32

**Comment by dvesh3** [comment]
Fixed by #813
