### ISSUE TITLE
[Bug]: Data Hub (v1.5.4) seems to break when using multiple API Keys in GraphQL API configuration

### ISSUE THREAD

**Issue by khenow1978** [pimcore/data-hub#794]
### Expected behavior

When the user configures a GraphQL API to use several API Keys it's supposed to accept any of these key as authentification and returns the JSON result of the query.

<img width="336" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/0cbbb533-4c16-42ee-ba15-ecef58270e49">

### Actual behavior

Within the GraphiQL Playground all Keys are smashed together to one large key and the API doesn't work correctly:

<img width="591" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/e35acc99-266f-46bf-bb61-76c85a3359d3">

The Playground mentions this error message:

<img width="339" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/398621bb-3666-4a99-821a-c194352707ca">

I have undone these changes in order to return to the state before but that doesn't work either. In fact NO API works anymore.. even if I create a new one with only one key. They all return HTML code instead of JSON.

So I did some further testing with a small Python script I wrote for this purpose:

<img width="609" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/23cd25fa-0f5f-476b-ae8d-1b0c2bb56529">

As you can see it returns HTML code (that is in fact the Login Page from the Portal Engine) although I sent a proper query. When I exchange the transport with the production system API it works fine. 

Even the connection itself isn't working properly anymore. In production when I forget to send the API Key I receive HTTP 400 but in the dev environment the result is always HTTP 200. That's not making a lot of sense to me.

I have upgrade from v1.5.4 to v1.5.8 in order to see if this resolves the issue. It didn't. Currently we are using Pimcore 10.5.14. The only short term solution would be to install Pimcore from scratch as Dev environment and start all over and see if the issue occurs once again.

### Steps to reproduce

- Create a new GraphQL API
- Add several API Keys to the security section
- Save the API

- Try to use the GraphiQL Playground OR
- Try to access the API from an external source

**Comment by khenow1978** [comment]
After I've installed Pimcore once again, I've tried to reproduce the error but it didn't happen. Now the behaviour is as expected besides one issue which remains. Let's say you've created an API with 3 Keys:
<img width="428" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/af74fde5-b3e3-4547-a80a-f85a6ab7bf36">

Now, when you start the playground this happens:
<img width="706" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/31f52352-6da4-41fe-97cc-98668f94a0f3">

All 3 Keys are smashed together to one string rather than an array (is this even possible as X-API-KEY??) and you get a permission error (Importan. NOT a DocType error). The solution is to take one of the 3 Keys from the API and replace the wrong key with the correct one:

<img width="595" alt="image" src="https://github.com/pimcore/data-hub/assets/92732594/e2e7b3ee-aee4-4ada-a1fc-84f845b65d90">

Now it works.. I'm not sure if this is an expected behaviour because everytime you want to use the playground you have to keep in mind to replace the API Key..

**Comment by dvesh3** [comment]
Fixed by #795
