### ISSUE TITLE
[Improvement]: Use 'getThumbnail()' instead of 'getThumbnailConfig()'

### ISSUE THREAD

**Issue by aryaantony92** [pimcore/data-hub#804]
### Improvement description

Related to https://github.com/pimcore/pimcore/pull/15869

- [x] https://github.com/pimcore/data-hub/blob/ce780dd420818e49914da373fb869f8865b5060c/src/GraphQL/Resolver/AssetType.php#L196

**Comment by blankse** [comment]
@aryaantony92 I created a PR https://github.com/pimcore/data-hub/pull/805

**Comment by aryaantony92** [comment]
@blankse Thanks!

**Comment by aryaantony92** [comment]
Fixed by https://github.com/pimcore/data-hub/pull/805
