### ISSUE TITLE
Feature request: Allow filtering via input types

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#81]
Today the only way(?) that we can use filtering is via [Filter Listings](https://github.com/pimcore/data-hub/blob/master/doc/graphl/Filtering.md), however, I would like to move these filters into Query variables, like this:

```gql
query news(published: Boolean, $first: Int, $filter: Filter) {
    ...
}
variables: {
    "published": true,
    "first": 5,
    "filter": What goes here?
}
```

However, I can't figure out how to do it and I have come to the conclusion that it is probably not possible with today's solution, is it because the dollar sign?

**Comment by weisswurstkanone** [comment]
Can you give a more detailed example of what your goal would be ?

**Comment by NiklasBr** [comment]
Today, note that the filter is a hard-coded string:

```graphql
query news(published: Boolean, first: 3 filter: "{\"o_modificationDate\": {\"$gte\": 123456789}}") { ... }
```

There is currently no way to dynamically change a variable due to the `filter` design.

what I want, in short:

```graphql
query news(published: Boolean, first: 3 filter: Filter) { ... }

variables {
  "filter": {
    o_modificationDate: {
      gte: 123456789
    }
  }
}
```

The filter is now an object, or any kind of InputObject.

**Comment by weisswurstkanone** [comment]
ok I see ... PRs are warmly appreciated :-)

**Comment by nerdsklickpark** [comment]
I know this may not be the finest solution, but you could replace the filter variable like this. Don't you?

```graphql
query News($filter: String!) {
  news(filter: $filter) {
    ...
  }
}
```

**Comment by NiklasBr** [comment]
@nerdsklickpark That's effectively the same thing I wrote in my previous comment. Does not help unfortunately. Filtering via a schema-dependent string is not a good solution.
