### ISSUE TITLE
[Bug]: GraphQl - query for asset meta data returns an exception

### ISSUE THREAD

**Issue by lukmzig** [pimcore/data-hub#811]
### Expected behavior

List of asset meta data is returned

### Actual behavior

Exception is thrown ( "Expected a value of type String but received: [[\"object\",12]]. String cannot represent value: [[\"object\",12]]")

### Steps to reproduce

1. Go to https://demo.pimcore.com/
2. Open graphQl **assets** configuration and add _Asset Listing_ read permission in the Schema Definition and save configuration
4. Open playground or go to https://demo.pimcore.com/pimcore-datahub-webservices/explorer/assets?apikey=9e265983fbd2dc42b8f7cdb841c82807
5. Add Query to list asset meta data with data e.g
`{
  getAssetListing {
    totalCount
    edges {
      node {
       ... on asset { 
      		id
        	fullpath
        metadata(ignore_language: true) { name type data}
      	}
      }
    }
  }
}`
6. Exception is returned (with debugger exception states:  "Expected a value of type String but received: [[\"object\",12]]. String cannot represent value: [[\"object\",12]]")

**Comment by kingjia90** [comment]
Resolved by #816 and https://github.com/pimcore/asset-metadata-class-definitions/pull/148
