### ISSUE TITLE
[Bug][Data loss]: if passing an invalid asset.id, fullpath to object mutation GraphQL query, the assets are silently discarded

### ISSUE THREAD

**Issue by dkarlovi** [pimcore/data-hub#823]
### Expected behavior

Error reported before any mutation is done. Same thing happens with unknown IDs, it just ignores them.

### Actual behavior

Any unknown assets silently discarded.

### Steps to reproduce

1. create class `Product` with input `SKU` and many to one assets called `Images`
2. add an object 123 with a few images
3. run this (see #822 why the path contains a hostname):
```gql
mutation {
  updateProduct(
    id: 123
    input: {
      SKU: "ABC"
      Images: [
        {
          fullpath: "https://example.com/Brands/loxeal_logo.png"
          type: "asset"
        }
      ]
    }
  ) {
    output {
      id
    }
    message
    success
  }
}
```
4. it responds with success and the SKU is correctly persisted, but images are empty (and any previous images are deleted)

**Comment by dkarlovi** [comment]
It seems this applies to any relation, not just assets, including one to one. If you pass gibberish to it, it ignores it and just stores null, but it should actually validate the proposed changes before saving.

**Comment by kingjia90** [comment]
@dkarlovi Please have a look and try out if #825 resolves the described problem
Thank you in advance

**Comment by kingjia90** [comment]
Fixed by https://github.com/pimcore/data-hub/pull/825
