### ISSUE TITLE
sortBy, database fieldnames and system column names

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#84]
Consider the schema:

```
categoryEdge
id: ID
classname: String
name: String
metaDescription: String
description: String
published: Boolean
fullpath: String
image_thumbnail_html: String
```
With the query:
```gql
query mycategoryquery($published: Boolean, $sortby: String, $sortOrder: String) {
  getCategoryListing(published: $published, sortBy: $sortby, sortOrder: $sortOrder) {
    edges {
      node {
        name
        fullpath
      }
    }
  }
}
```
With variables:

```json
{
  "published": false,
  "sortby": "name",
  "sortOrder": "ASC"
}
```

This works fine, but when I add the System column **Full Path** to the schema it is not clear how to sort by it, I had assumed that it would be `fullpath` but that is not the case, instead it is not `o_path` either...

To even *know* this I need to know that the GraphQL server is a Pimcore server and I need to intimately aware of the underlying database schema. I understand that this is a work in progress, but I am not convinced this is a good idea once this bundle becomes more mature and stable.

So, to the question: I want to improve this. But how?

Should we automatically add the DB column name to the schema definition (i.e. append it to the description somehow)?

Or should we have a "translator" that allows the client to `"sortby": "fullpath"` in the variables object and then in `GraphQL/Resolver/QueryType.php` look up the true column name for the field definition?

**Comment by NiklasBr** [comment]
I got a half-baked solution working by changing:

https://github.com/pimcore/data-hub/blob/2d56b21534a0f58fb8e57a2b3fc0cd0abcb60fcf/src/GraphQL/Query/QueryType.php#L203

to 

```php
                    'sortBy' => ['type' => Type::listOf(Type::string())],
```

and query:

```gql
query mycategoryquery($published: Boolean, $sortby: [String], $sortOrder: String) {
  getCategoryListing(first: 8, published: $published, sortBy: $sortby, sortOrder: $sortOrder) {
    edges {
      node {
        name
        fullpath
      }
    }
  }
}
```
and variables:

```json
{
  "published": false,
  "sortby": [
    "o_path",
    "o_key"
  ],
  "sortOrder": "ASC"
}
```

But this solution still requires knowledge about the database schema unfortunately.

**Comment by weisswurstkanone** [comment]
I guess then sortOrder should be a list of string as well.

**Comment by NiklasBr** [comment]
True.

Would you consider this change to result in an acceptable API? Might have to live with it for a while...

**Comment by weisswurstkanone** [comment]
Hi, do you want to create a PR? Otherwise we will put it on the todo list ;-)

**Comment by NiklasBr** [comment]
I can create a PR today, but I was just asking if you think it is a good idea? :)

API designs like this might have to live a long time, and I was just thinking maybe you had some thoughts about it.

**Comment by weisswurstkanone** [comment]
Well, I think we cannot meet every expectation. Either you do it in a generic way, i.e. generate a schema on the fly and live with the consequences or add some "magic" which again could be hard to understand. One thing we shouldn't force the user to do is to invest a lot of manual work.

However, for system fields I could imagine some kind of layer. On the oder side, system fields are system specific anyway. Either we support and document them or we don't consider them at all.

But: I clearly see your point: this stuff should be long living.

Any other opinions on that?

**Comment by NiklasBr** [comment]
> Any other opinions on that?

Not really. I did some casual research into how others do it, and it seems that `Enums` are quite common, such as [this example](https://github.com/howtographql/graphql-js/blob/master/src/schema.graphql).

So in the end it seems complex arguments are common and I feel confident that this change will not be too odd.
