### ISSUE TITLE
[Bug]: Codeception tests fail

### ISSUE THREAD

**Issue by ghost** [pimcore/data-hub#843]
### Expected behavior

Tests pass

### Actual behavior

Please see e.g.

- https://github.com/pimcore/data-hub/actions/runs/8166344173 
- https://github.com/pimcore/data-hub/actions/runs/8135371096

### Steps to reproduce

Start workflows

**Comment by kingjia90** [comment]
Resolved by https://github.com/pimcore/data-hub/pull/842
