### ISSUE TITLE
[Bug]: [ERROR] Bundle PimcoreDataHubBundle can not be installed 

### ISSUE THREAD

**Issue by gitmini** [pimcore/data-hub#847]
### Expected behavior

install Pimcore Datahub,  execute a command: bin/console pimcore:bundle:install PimcoreDataHubBundle
![image](https://github.com/pimcore/data-hub/assets/24379359/2619981f-e81f-4d08-96eb-1365039372d7)

### Actual behavior

Report an error： [ERROR] Bundle PimcoreDataHubBundle can not be installed  

### Steps to reproduce

1.Install the required dependencies:
composer require pimcore/data-hub

2.config/bundles.php file. added The following lines :
use Pimcore\Bundle\DataHubBundle\PimcoreDataHubBundle;
// ...

return [
    // ...
    PimcoreDataHubBundle::class => ['all' => true],
    // ...
];

3.Install the bundle:
bin/console pimcore:bundle:install PimcoreDataHubBundle

Report an error： [ERROR] Bundle PimcoreDataHubBundle can not be installed  

Can anyone tell me how to solve this problem?

**Comment by Corepex** [comment]
@gitmini, is it possible that the install command was already executed? 

To check a bundle's current status, execute the following command: `bin/console p:b:l`.
If needed, you can reinstall the bundle by executing `bin/console p:b:u PimcoreDataHubBundle` and `bin/console p:b:i PimcoreDataHubBundle`
