### ISSUE TITLE
[Bug]: modificationDate

### ISSUE THREAD

**Issue by andrewa17github** [pimcore/data-hub#849]
### Expected behavior

Previous versions of datahub allowed modicationDate to be passed as an input in the mutation.

### Actual behavior

The latest version does not allow this with error on attempting a mutation with input of modificationDate using a timestamp, this is a problem to perform third party system delta updates with larger datasets to make sure no data is missed and also not repeat processing the same object due to a newer modification date.

`
        )

            [0] => stdClass Object

                (

                    [message] => Field "modificationDate" is not defined by type "UpdateProductInput".

                    [locations] => Array

                        (

                            [0] => stdClass Object

                                (

                                    [line] => 1

                                    [column] => 53

                                )

                        )

                    [extensions] => stdClass Object

                        (

                            [file] => /.../vendor/webonyx/graphql-php/src/Validator/Rules/ValuesOfCorrectType.php

                            [line] => 117

                        )

                )

        )`

### Steps to reproduce

`$mutation = 'updateProduct(id: '.$productMaster->id.', input: {modificationDate: ' . $startDtm . '}) {success,message,output{id,key,published} }';`

**Comment by mcop1** [comment]
Hello,

thank you for creating the ticket. To be honest, if the modificationDate was updateable before, then, in my opinion, that was a bug. After internally discussions, we decided that we dont want to change the behavior. 
To solve your problem, we suggest to add a datetime field as timestamp and set it to invisible, then use that field to indicate when the import last run.
