### ISSUE TITLE
[Feature]: PHP 8.3 support?

### ISSUE THREAD

**Issue by tmannherz** [pimcore/data-hub#864]
### Feature description

Are you planning to support PHP 8.3? Pimcore core supports it as of a couple months ago but the PHP version in this repo's compose.json file is currently locked to <=8.2: `"php": "~8.0.0 || ~8.1.0 || ~8.2.0"`.

https://github.com/pimcore/pimcore/pull/16589

**Comment by blankse** [comment]
I already created a PR for this: https://github.com/pimcore/data-hub/pull/840
