### ISSUE TITLE
[Improvement]: Can $in be added as a logic operator for Query filters?

### ISSUE THREAD

**Issue by jonathan-dejong** [pimcore/data-hub#870]
### Improvement description

I've got this scenario where I have a select field containing a bunch of site names with site ids as values. 

I would like to be able to filter my query so that I can get the objects where the value of this field is either null OR one of the values is a specific ID that I pass to the filter. 

I believe it would be something like this, in this example I'm getting the ProductSimple objects if the ProductSites select field contains 1,2 or 4 as values. 

`getProductSimpleListing(filter: "{ \"$or\": [{\"ProductSites\": \"null\"}, {\"ProductSites\": {\"$in\": [\"1,2,4\"]}}], }") {`

However `$in` is not a supported operator so this simply gives me an Internal server error. 
At least that is what I think is happening.. 
Because this is the old docs:
https://pimcore.com/docs/pimcore/6.9/Development_Documentation/Web_Services/Query_Filters.html

And in the new docs, I've not been able to find a similar reference. 

I know that I can use `$like` BUT that gives false positives. 

`\"$or\": [{\"ProductSites\": \"null\"}, {\"ProductSites\": {\"$like\": \"%1%\"}}]`

This will return results where productSites contains a value of 12, 21, 201 etc. 

As a sidenote/question: 
I don't think this way of checking for null works either, but I am not sure how to do it.. if anyone knows I'd gladly take your input!

**Comment by jonathan-dejong** [comment]
This is the best I've been able to achieve right now. 

`filter: "{ \"$or\": [ { \"ProductSites\": null }, { \"ProductSites\": { \"$like\": \"%11%\" } } ] }"`

This seems to work for checking null and a LIKE for the ID.. which does still give false positives but it's the best option it seems until such time that IN is a valid operator.

**Comment by fashxp** [comment]
No, $in is not implemented. Only `$not`, `$or`, `$and` and `$like` are supported. 

We are thinking about moving to PQL for filtering, see https://github.com/pimcore/data-hub/issues/891 and https://pimcore.com/docs/platform/Generic_Data_Index/Searching_For_Data_In_Index/Pimcore_Query_Language/

Actually, there is also not something like `IN`, but syntax still should be much more convenient.
