### ISSUE TITLE
[Bug]: Playground autoComplete or Type Box doesn't disappear.

### ISSUE THREAD

**Issue by BojanHribernik** [pimcore/data-hub#873]
### Expected behavior

GraphQL Playground autoComplete box disappears.

### Actual behavior

GraphQL Playground autoComplete box does not disappear.

This is a [known bug](https://github.com/graphql/graphql-playground/issues/1429) in Playground. When they roll out a fix for this, Pimcore DataHub should upgrade ASAP ;) 

![Screenshot from 2024-08-06 09-39-36](https://github.com/user-attachments/assets/b676088f-fabd-4338-a9e2-4bcfaa989c4f)

### Steps to reproduce

Open GraphQL Playground in latest version of Google Chrome, write a query and press Ctrl+Space to open autoComplete - it will never disappear.

Firefox does not have this problem.

I am using
- Ubuntu 24.04
- Chrome Version 127.0.6533.88 (Official Build) (64-bit)

**Comment by iysun** [comment]
I have the same problem in Chrome and Edge, but Firefox is fine

**Comment by ayoob-lfc** [comment]
I have the same issue

**Comment by ilnytskyistrix** [comment]
I also faced this issue

**Comment by kingjia90** [comment]
Will be fixed by https://github.com/pimcore/data-hub/pull/893
Please apply the changes and give it a try, TIA
