### ISSUE TITLE
Lowercasing image fields always, is it really required?

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#9]
Maybe a bug?

When I'm creating an image field in the Schema called `mainImageThumbnail` I noticed that it became `mainimagethumbnail`.

There is likely a good reason for this, but it is a bit odd when `creationDate`, and some other fields can retain their camelcasing.

"Main Image Thumbnail" &rarr; "main_image_thumbnail" works (I personally prefers snakes, but our coding style asks for camels, which is why I ask)

**Comment by weisswurstkanone** [comment]
Can you provide a screenshot of your schema definition? You probably talking about an operator, right ?

**Comment by NiklasBr** [comment]
![Skärmbild (127)](https://user-images.githubusercontent.com/279826/56788327-6f1cf180-67ff-11e9-93b4-d06d74cc5227.png)

**Comment by weisswurstkanone** [comment]
Actually there is no specific reason for that. Will remove that and just replace special characters.

**Comment by weisswurstkanone** [comment]
todo: search for 2 occurences of $label = strtolower($label) and adapt accordingly

**Comment by weisswurstkanone** [comment]
changed to:
"MAINIMAGETHUMBNAIL" => "mAINIMAGETHUMBNAIL"
"MAIN IMAGE&THUMBNAIL" => "mAIN_IMAGE_THUMBNAIL"
