### ISSUE TITLE
CSV Export Support

### ISSUE THREAD

**Issue by brusch** [pimcore/data-hub#93]

**Comment by weisswurstkanone** [comment]
Use data-hub-file-extension as an addition instead. See https://pimcore.com/docs/data-hub-file-export/current/

**Comment by daniele-sarnari** [comment]
> Use data-hub-file-extension as an addition instead. See https://pimcore.com/docs/data-hub-file-export/current/

Hello Josef, why doesn't pimcore/data-hub officially support files as export method while it does in the link you provided?
I wonder where/how can I enable this feature.

**Comment by dvesh3** [comment]
@DrewLiberty Hi, Data Hub File Export is an add-on extension, which comes under Pimcore enterprise edition. You can read about enterprise Edition [here](https://pimcore.com/en/platform/enterprise-edition)

**Comment by sdouma** [comment]
@dvesh3 
Seems pretty relevant to state in the docs it is part of enterprise.

**Comment by dvesh3** [comment]
@sdouma already there:
![image](https://user-images.githubusercontent.com/5137917/178927430-fab162b3-1c39-4199-a746-fd009efd4dcb.png)![image](https://user-images.githubusercontent.com/5137917/178927302-f2ceec9c-b061-428c-a056-655b05f63af6.png)

**Comment by snmabaur** [comment]
Hi
I tried to install this package and get the following error

` Could not find a matching version of package pimcore/data-hub-file-export. Check the package spelling, your version constraint and that the pa  
  ckage is available in a stability which matches your minimum-stability (stable).`

Is this package not available anymore? 

Thanks and cheers

**Comment by dvesh3** [comment]
Hi @snmabaur this is an [enterprise extension](https://pimcore.com/en/platform/enterprise-edition). if you have enterprise subscription then please contact [enterprise-support@pimcore.com](mailto:enterprise-support@pimcore.com)

**Comment by snmabaur** [comment]
Aaah that makes sense, thanks for your reply
