### ISSUE TITLE
Configuration verbosity problems

### ISSUE THREAD

**Issue by NiklasBr** [pimcore/data-hub#97]
Every time the `datahub-configurations.php` file is saved a lot of (what seems to be) unnecessary fields change, for example

```
"key" => "#5d5a91383afe1"
```
and
```
"displayfield-2452-inputEl" => "API key required for web service access (min length: 16)"
```

Are these required for the config to work or can the file be generated without them?

**Comment by weisswurstkanone** [comment]
"displayfield-2452-inputEl" is not needed. It should be excluded from form submission.

Regarding the key: It is required. However, the only requirement is that it must be unique.

**Comment by NiklasBr** [comment]
That's just the description and id of the key field, the content (actual API key) does not change.

**Comment by weisswurstkanone** [comment]
it is just a unique identifier for the field. used internally only.

**Comment by NiklasBr** [comment]
Is it possible to avoid changing it? It "pollutes" (:)) the commit logs when checking in the file

**Comment by weisswurstkanone** [comment]
We could try to completely avoid writing it and regenerate a unique ID whenever the configuration is read. Do you wanna give it a try ?

**Comment by NiklasBr** [comment]
Maybe, I'll see if/when I can get some time to give it a try.
